#ifndef RT_CODE_H
#define RT_CODE_H

#define RT_CODE_BASE_FATAL		-100
#define RT_CODE_BASE_COMMON		-200
#define RT_CODE_BASE_SHELL		-300	// in rt_shell.x
#define RT_CODE_BASE_MTD		-400	// in rt_mtd.x
#define RT_CODE_BASE_FS			-500	// file system

// ----------------------------------------------------------------------------
// VERY IMPORTANT!!!
//  the below are compatible with rts_errno.h by rename RTS_XXX to RT_XXX.
//  since rtscore is ported in the project, please keep these error code defined
//  value same with rts_errno.h
// ----------------------------------------------------------------------------
#define RT_OK						0
#define RT_FAIL						-1
#define RT_E_NULL_POINT				-10
#define RT_E_NO_MEMORY				-11
#define RT_E_NOT_REALIZED			-12
#define RT_E_EXIST					-13
#define RT_E_NOT_EXIST				-14
#define RT_E_NOT_FOUND				-15
#define RT_E_NOT_REGISTERED			-16
#define RT_E_NOT_READY				-17
#define RT_E_EMPTY					-18
#define RT_E_NOT_EMPTY				-19
#define RT_E_FULL					-20
#define RT_E_INVALID_ARG			-21
#define RT_E_INVALID_TYPE			-22
#define RT_E_NOT_MATCH				-23
#define RT_E_OPEN_FAIL				-24
#define RT_E_CLOSE_FAIL				-25
#define RT_E_NOT_OPEN				-26
#define RT_E_GET_FAIL				-27
#define RT_E_SET_FAIL				-28
#define RT_E_NOT_SUPPORT			-29
#define RT_E_INITIALIZED			-30
#define RT_E_NOT_INITIALIZED		-31
#define RT_E_INUSE					-32
#define RT_E_WRITE_FAIL				-33
#define RT_E_READ_FAIL				-34
#define RT_E_LOCK_FAIL				-35
#define RT_E_INVALID_LENGTH			-36
#define RT_E_TIMEOUT				-37
#define RT_E_THREAD_FAIL			-38
#define RT_E_OVERFLOW				-39
#define RT_E_BIG					-40
#define RT_E_PERM					-41
#define RT_E_NO_ENT					-42
#define RT_E_IO						-43
#define RT_E_AGAIN					-44
#define RT_E_NO_DEV					-45
#define RT_E_NO_SYS					-46
#define RT_E_IOCTL					-47
#define RT_E_LESS_DATA				-48
#define RT_E_OUT_OF_RANGE			-49
#define RT_E_MMAP_FAIL				-50
#define RT_E_MUNMAP_FAIL			-51
#define RT_E_INVALID_DATA			-52
#define RT_E_NO_REALIZED			-53
#define RT_E_INVALID_VERSION		-54
#define RT_E_UNKNOWN				-55
#define RT_E_RECEIVE_FAIL			-56
#define RT_E_SEND_FAIL				-57
#define RT_E_DISCONNECT				-58
#define RT_E_SAVE_FAIL				-59
#define RT_E_CMP_FAIL				-60
#define RT_E_ERASE_FAIL				-61
#define RT_E_RESET_FAIL				-62
#define RT_E_DISABLE				-63
#define RT_E_NOT_EQUAL				-64
#define RT_E_EQUAL					-65
#define RT_E_CMD_ERROR				-66
#define RT_E_INVALID_CMD			-67
#define RT_E_MISMATCH				-68
#define RT_E_BUF_OVERFLOW			-69
#define RT_E_NOT_CROSS				-70
#define RT_E_NOT_PARALLEL			-71
#define RT_E_PARALLEL				-72
#define RT_E_CONFILCT				-73
#define RT_E_BUSY					-74
#define RT_E_CHANGED				-75

// fatal (serious) error
#define RT_E_INTERNAL_ERR		(RT_CODE_BASE_FATAL -  1)	// program internal error (programmer's error)
#define RT_E_HW_ERR				(RT_CODE_BASE_FATAL -  2)

// common error
#define RT_E_INIT_FAIL			(RT_CODE_BASE_COMMON -  1)
#define RT_E_NOT_INIT			(RT_CODE_BASE_COMMON -  2)
#define RT_E_ALREADY_INIT		(RT_CODE_BASE_COMMON -  3)
#define RT_E_ALREADY_OPEN		(RT_CODE_BASE_COMMON -  4)
#define RT_E_CREATE_FAIL		(RT_CODE_BASE_COMMON -  5)
#define RT_E_DELETE_FAIL		(RT_CODE_BASE_COMMON -  6)
#define RT_E_OPERATE_FAIL		(RT_CODE_BASE_COMMON -  7)
#define RT_E_LENGTH_MISMATCH	(RT_CODE_BASE_COMMON -  8)
#define RT_E_OP_NOT_ALLOW		(RT_CODE_BASE_COMMON -  9)
#define RT_E_NOT_ENOUGH_BUF		(RT_CODE_BASE_COMMON - 10)
#define RT_E_HW_NOT_INIT		(RT_CODE_BASE_COMMON - 11)
#define RT_E_ALREADY_DEINIT		(RT_CODE_BASE_COMMON - 12)
#define RT_E_ALREADY_START		(RT_CODE_BASE_COMMON - 13)
#define RT_E_ALREADY_STOP		(RT_CODE_BASE_COMMON - 14)
#define RT_E_WRONG_ALIGNMENT	(RT_CODE_BASE_COMMON - 15)
#define RT_E_NOT_START			(RT_CODE_BASE_COMMON - 16)
#define RT_E_DEINIT_FAIL		(RT_CODE_BASE_COMMON - 17)
#define	RT_E_NULL_OBJECT		(RT_CODE_BASE_COMMON - 18)
#define	RT_E_NULL_STRING		(RT_CODE_BASE_COMMON - 19)
#define RT_E_ALREADY_CREATE		(RT_CODE_BASE_COMMON - 20)
#define RT_E_ENCODE_FAIL		(RT_CODE_BASE_COMMON - 21)
#define RT_E_DECODE_FAIL		(RT_CODE_BASE_COMMON - 21)

#define RT_E_INVALID_PRECOND	(RT_CODE_BASE_COMMON - 50)	// invalid pre-condition
#define RT_E_INVALID_ENV_VAR	(RT_CODE_BASE_COMMON - 51)
#define RT_E_INVALID_PATH		(RT_CODE_BASE_COMMON - 52)
#define RT_E_INVALID_FORMAT		(RT_CODE_BASE_COMMON - 53)
#define RT_E_INVALID_SIZE		(RT_CODE_BASE_COMMON - 54)
#define RT_E_INVALID_ID			(RT_CODE_BASE_COMMON - 55)
#define RT_E_INVALID_STATE		(RT_CODE_BASE_COMMON - 56)
#define RT_E_INVALID_INDEX		(RT_CODE_BASE_COMMON - 57)
#define RT_E_INVALID_MODE		(RT_CODE_BASE_COMMON - 58)

// NOTE: plz ref to FRESULT in /drv/fs/plat_fatfs/r0.10c/include/ff.h
#define FRESULT_TO_RT_CODE(x)	((x) ? RT_CODE_BASE_FS-(x) : 0)
#define RT_CODE_TO_FRESULT(x)	((x) ? RT_CODE_BASE_FS-(x) : 0)
// for 1~19, plz do not modify!!
#define RT_E_FS_DISK_ERR			(RT_CODE_BASE_FS -  1)	// (1) A hard error occurred in the low level disk I/O layer
#define RT_E_FS_INT_ERR				(RT_CODE_BASE_FS -  2)	// (2) Assertion failed
#define RT_E_FS_NOT_READY			(RT_CODE_BASE_FS -  3)	// (3) The physical drive cannot work
#define RT_E_FS_NO_FILE				(RT_CODE_BASE_FS -  4)	// (4) Could not find the file
#define RT_E_FS_NO_PATH				(RT_CODE_BASE_FS -  5)	// (5) Could not find the path
#define RT_E_FS_INVALID_NAME		(RT_CODE_BASE_FS -  6)	// (6) The path name format is invalid
#define RT_E_FS_DENIED				(RT_CODE_BASE_FS -  7)	// (7) Access denied due to prohibited access or directory full
#define RT_E_FS_EXIST				(RT_CODE_BASE_FS -  8)	// (8) Access denied due to prohibited access
#define RT_E_FS_INVALID_OBJECT		(RT_CODE_BASE_FS -  9)	// (9) The file/directory object is invalid
#define RT_E_FS_WRITE_PROTECTED		(RT_CODE_BASE_FS - 10)	// (10) The physical drive is write protected
#define RT_E_FS_INVALID_DRIVE		(RT_CODE_BASE_FS - 11)	// (11) The logical drive number is invalid
#define RT_E_FS_NOT_ENABLED			(RT_CODE_BASE_FS - 12)	// (12) The volume has no work area
#define RT_E_FS_NO_FILESYSTEM		(RT_CODE_BASE_FS - 13)	// (13) There is no valid FAT volume
#define RT_E_FS_MKFS_ABORTED		(RT_CODE_BASE_FS - 14)	// (14) The f_mkfs() aborted due to any parameter error
#define RT_E_FS_TIMEOUT				(RT_CODE_BASE_FS - 15)	// (15) Could not get a grant to access the volume within defined period
#define RT_E_FS_LOCKED				(RT_CODE_BASE_FS - 16)	// (16) The operation is rejected according to the file sharing policy
#define RT_E_FS_NOT_ENOUGH_CORE		(RT_CODE_BASE_FS - 17)	// (17) LFN working buffer could not be allocated
#define RT_E_FS_TOO_MANY_OPEN_FILES	(RT_CODE_BASE_FS - 18)	// (18) Number of open files > _FS_SHARE
#define RT_E_FS_INVALID_PARAMETER	(RT_CODE_BASE_FS - 19)	// (19) Given parameter is invalid
//
#define RT_E_FS_REG_DISK_DRV		(RT_CODE_BASE_FS - 101)
#define RT_E_FS_MOUNT				(RT_CODE_BASE_FS - 102)
#define RT_E_FS_EOF					(RT_CODE_BASE_FS - 103)

// Err bit define
#define ERR_NEG_BIT_OFFSET 31 //1 bit 31
#define ERR_GROUP_BIT_OFFSET 27 //4 bit 30:27
#define ERR_SUB_GROUP_BIT_OFFSET 21 //6 bit 26:21
#define ERR_SUB_ID_BIT_OFFSET 9 //12 bit 20:9
#define ERR_TASK_ID 5 //4 bit 8:5
#define ERR_RSV		0 //5 bit 4:0

// Err - group id
#define ERR_GROUP_VOE		(1 << ERR_NEG_BIT_OFFSET)|(1 << ERR_GROUP_BIT_OFFSET)
#define ERR_GROUP_ISP		(1 << ERR_NEG_BIT_OFFSET)|(2 << ERR_GROUP_BIT_OFFSET)
#define ERR_GROUP_DRV		(1 << ERR_NEG_BIT_OFFSET)|(3 << ERR_GROUP_BIT_OFFSET)
#define ERR_GROUP_MOD		(1 << ERR_NEG_BIT_OFFSET)|(4 << ERR_GROUP_BIT_OFFSET)
#define ERR_GROUP_OSD		(1 << ERR_NEG_BIT_OFFSET)|(5 << ERR_GROUP_BIT_OFFSET)
#define ERR_GROUP_ENC		(1 << ERR_NEG_BIT_OFFSET)|(6 << ERR_GROUP_BIT_OFFSET)

// Err - Sub group id
#define ERR_SUB_GROUP_VOE_FLOW	(1 << ERR_SUB_GROUP_BIT_OFFSET)

#define ERR_SUB_GROUP_ISP_TOP	(1 << ERR_SUB_GROUP_BIT_OFFSET)

#define ERR_SUB_GROUP_DRV_ZOOM	(1 << ERR_SUB_GROUP_BIT_OFFSET)
#define ERR_SUB_GROUP_DRV_I2C	(2 << ERR_SUB_GROUP_BIT_OFFSET)
#define ERR_SUB_GROUP_DRV_VIDEO	(3 << ERR_SUB_GROUP_BIT_OFFSET)

#define ERR_SUB_GROUP_MOD_CONTROL	(1 << ERR_SUB_GROUP_BIT_OFFSET)
#define ERR_SUB_GROUP_MOD_INTERFACE	(2 << ERR_SUB_GROUP_BIT_OFFSET)
#define ERR_SUB_GROUP_MOD_AE		(3 << ERR_SUB_GROUP_BIT_OFFSET)
#define ERR_SUB_GROUP_MOD_AWB		(4 << ERR_SUB_GROUP_BIT_OFFSET)
#define ERR_SUB_GROUP_MOD_AF		(5 << ERR_SUB_GROUP_BIT_OFFSET)
#define ERR_SUB_GROUP_MOD_BLC		(6 << ERR_SUB_GROUP_BIT_OFFSET)
#define ERR_SUB_GROUP_MOD_CCM		(7 << ERR_SUB_GROUP_BIT_OFFSET)
#define ERR_SUB_GROUP_MOD_CROP		(8 << ERR_SUB_GROUP_BIT_OFFSET)
#define ERR_SUB_GROUP_MOD_DEHAZE	(9 << ERR_SUB_GROUP_BIT_OFFSET)
#define ERR_SUB_GROUP_MOD_EEH		(10<< ERR_SUB_GROUP_BIT_OFFSET)
#define ERR_SUB_GROUP_MOD_FLICK		(11<< ERR_SUB_GROUP_BIT_OFFSET)
#define ERR_SUB_GROUP_MOD_GAMMA		(12<< ERR_SUB_GROUP_BIT_OFFSET)
#define ERR_SUB_GROUP_MOD_GLOBAL	(13<< ERR_SUB_GROUP_BIT_OFFSET)
#define ERR_SUB_GROUP_MOD_INTP		(14<< ERR_SUB_GROUP_BIT_OFFSET)
#define ERR_SUB_GROUP_MOD_IQ		(15<< ERR_SUB_GROUP_BIT_OFFSET)
#define ERR_SUB_GROUP_MOD_LDC		(16<< ERR_SUB_GROUP_BIT_OFFSET)
#define ERR_SUB_GROUP_MOD_MASK		(17<< ERR_SUB_GROUP_BIT_OFFSET)
#define ERR_SUB_GROUP_MOD_MCROP		(18<< ERR_SUB_GROUP_BIT_OFFSET)
#define ERR_SUB_GROUP_MOD_MD		(19<< ERR_SUB_GROUP_BIT_OFFSET)
#define ERR_SUB_GROUP_MOD_MLSC		(20<< ERR_SUB_GROUP_BIT_OFFSET)
#define ERR_SUB_GROUP_MOD_NLSC		(21<< ERR_SUB_GROUP_BIT_OFFSET)
#define ERR_SUB_GROUP_MOD_RAWSTAT	(22<< ERR_SUB_GROUP_BIT_OFFSET)
#define ERR_SUB_GROUP_MOD_RGB2YUV	(23<< ERR_SUB_GROUP_BIT_OFFSET)
#define ERR_SUB_GROUP_MOD_SNR		(24<< ERR_SUB_GROUP_BIT_OFFSET)
#define ERR_SUB_GROUP_MOD_SPE		(25<< ERR_SUB_GROUP_BIT_OFFSET)
#define ERR_SUB_GROUP_MOD_STATIS	(26<< ERR_SUB_GROUP_BIT_OFFSET)
#define ERR_SUB_GROUP_MOD_TNR		(27<< ERR_SUB_GROUP_BIT_OFFSET)
#define ERR_SUB_GROUP_MOD_TM		(28<< ERR_SUB_GROUP_BIT_OFFSET)
#define ERR_SUB_GROUP_MOD_UVTUNE	(29<< ERR_SUB_GROUP_BIT_OFFSET)
#define ERR_SUB_GROUP_MOD_WDR		(30<< ERR_SUB_GROUP_BIT_OFFSET)
#define ERR_SUB_GROUP_MOD_YGAMMA	(31<< ERR_SUB_GROUP_BIT_OFFSET)
#define ERR_SUB_GROUP_MOD_YGC		(32<< ERR_SUB_GROUP_BIT_OFFSET)
#define ERR_SUB_GROUP_MOD_SENSOR	(33<< ERR_SUB_GROUP_BIT_OFFSET)

#define ERR_SUB_GROUP_OSD_API	(1 << ERR_SUB_GROUP_BIT_OFFSET)

#define ERR_SUB_GROUP_ENC_HEVC	(1 << ERR_SUB_GROUP_BIT_OFFSET)
#define ERR_SUB_GROUP_ENC_JPEG	(2 << ERR_SUB_GROUP_BIT_OFFSET)

//VOE
#define ERR_ID_VOE_CREATE_SEMAPHORE_FAIL	ERR_GROUP_VOE|ERR_SUB_GROUP_VOE_FLOW|(1 << ERR_SUB_ID_BIT_OFFSET)
#define ERR_ID_VOE_INVALID_PARAM_EXT_SYNC	ERR_GROUP_VOE|ERR_SUB_GROUP_VOE_FLOW|(2 << ERR_SUB_ID_BIT_OFFSET)
#define ERR_ID_VOE_NOT_SUPPORT_12M			ERR_GROUP_VOE|ERR_SUB_GROUP_VOE_FLOW|(3 << ERR_SUB_ID_BIT_OFFSET)
#define ERR_ID_VOE_ISP_SOC_START_FAIL		ERR_GROUP_VOE|ERR_SUB_GROUP_VOE_FLOW|(4 << ERR_SUB_ID_BIT_OFFSET)
#define ERR_ID_VOE_ISP_MALLOC_FAIL			ERR_GROUP_VOE|ERR_SUB_GROUP_VOE_FLOW|(5 << ERR_SUB_ID_BIT_OFFSET)
#define ERR_ID_VOE_ISP_BRING_UP_TIMEOUT		ERR_GROUP_VOE|ERR_SUB_GROUP_VOE_FLOW|(6 << ERR_SUB_ID_BIT_OFFSET)
#define ERR_ID_VOE_CREATE_ENC_TASK_FAIL		ERR_GROUP_VOE|ERR_SUB_GROUP_VOE_FLOW|(7 << ERR_SUB_ID_BIT_OFFSET)
#define ERR_ID_VOE_CREATE_OSD_TASK_FAIL		ERR_GROUP_VOE|ERR_SUB_GROUP_VOE_FLOW|(8 << ERR_SUB_ID_BIT_OFFSET)
#define ERR_ID_VOE_CREATE_OUT_TASK_FAIL		ERR_GROUP_VOE|ERR_SUB_GROUP_VOE_FLOW|(9<< ERR_SUB_ID_BIT_OFFSET)
#define ERR_ID_VOE_MALLOC_RC_FRAME_TBL_FAIL	ERR_GROUP_VOE|ERR_SUB_GROUP_VOE_FLOW|(10<< ERR_SUB_ID_BIT_OFFSET)
#define ERR_ID_VOE_MALLOC_ENC_OUTBUF_FAIL	ERR_GROUP_VOE|ERR_SUB_GROUP_VOE_FLOW|(11<< ERR_SUB_ID_BIT_OFFSET)
#define ERR_ID_VOE_MALLOC_JPEG_BUF_FAIL		ERR_GROUP_VOE|ERR_SUB_GROUP_VOE_FLOW|(12<< ERR_SUB_ID_BIT_OFFSET)
#define ERR_ID_VOE_MALLOC_VIDEO_BUF_FAIL	ERR_GROUP_VOE|ERR_SUB_GROUP_VOE_FLOW|(13<< ERR_SUB_ID_BIT_OFFSET)
#define ERR_ID_VOE_ENC_OPEN_FAIL			ERR_GROUP_VOE|ERR_SUB_GROUP_VOE_FLOW|(14<< ERR_SUB_ID_BIT_OFFSET)
#define ERR_ID_VOE_JPEG_OPEN_FAIL			ERR_GROUP_VOE|ERR_SUB_GROUP_VOE_FLOW|(15<< ERR_SUB_ID_BIT_OFFSET)

#define ERR_ID_VOE_CH_NOT_OPEN				ERR_GROUP_VOE|ERR_SUB_GROUP_VOE_FLOW|(16<< ERR_SUB_ID_BIT_OFFSET)
#define ERR_ID_VOE_ISP_STREAM_CLOSE_FAIL	ERR_GROUP_VOE|ERR_SUB_GROUP_VOE_FLOW|(17<< ERR_SUB_ID_BIT_OFFSET)
#define ERR_ID_VOE_OSD_DEINIT_FAIL			ERR_GROUP_VOE|ERR_SUB_GROUP_VOE_FLOW|(18<< ERR_SUB_ID_BIT_OFFSET)
#define ERR_ID_VOE_ENC_RELEASE_FAIL			ERR_GROUP_VOE|ERR_SUB_GROUP_VOE_FLOW|(19<< ERR_SUB_ID_BIT_OFFSET)
#define ERR_ID_VOE_JPEG_RELEASE_FAIL		ERR_GROUP_VOE|ERR_SUB_GROUP_VOE_FLOW|(20<< ERR_SUB_ID_BIT_OFFSET)
#define ERR_ID_VOE_ISP_BUF_RELEASE_FAIL		ERR_GROUP_VOE|ERR_SUB_GROUP_VOE_FLOW|(21<< ERR_SUB_ID_BIT_OFFSET)

#define ERR_ID_VOE_ENC_RC_RUNNING			ERR_GROUP_VOE|ERR_SUB_GROUP_VOE_FLOW|(22 << ERR_SUB_ID_BIT_OFFSET)
#define ERR_ID_VOE_ENC_RC_ISPFPS_OUT_RANGE	ERR_GROUP_VOE|ERR_SUB_GROUP_VOE_FLOW|(23 << ERR_SUB_ID_BIT_OFFSET)
#define ERR_ID_VOE_ENC_RC_GET_REALFPS_FAIL	ERR_GROUP_VOE|ERR_SUB_GROUP_VOE_FLOW|(24 << ERR_SUB_ID_BIT_OFFSET)

#define ERR_ID_VOE_VERIFY_ADDR_NULL			ERR_GROUP_VOE|ERR_SUB_GROUP_VOE_FLOW|(25 << ERR_SUB_ID_BIT_OFFSET)
#define ERR_ID_VOE_VERIFY_NLSC_NULL			ERR_GROUP_VOE|ERR_SUB_GROUP_VOE_FLOW|(26 << ERR_SUB_ID_BIT_OFFSET)

//main_isp
#define ERR_ID_ISP_MFD_PROBE_FAIL		ERR_GROUP_ISP|ERR_SUB_GROUP_ISP_TOP|(1 << ERR_SUB_ID_BIT_OFFSET)
#define ERR_ID_ISP_ZOOM_PROBE_FAIL		ERR_GROUP_ISP|ERR_SUB_GROUP_ISP_TOP|(2 << ERR_SUB_ID_BIT_OFFSET)
#define ERR_ID_ISP_PROBE_FAIL			ERR_GROUP_ISP|ERR_SUB_GROUP_ISP_TOP|(3 << ERR_SUB_ID_BIT_OFFSET)
#define ERR_ID_ISP_VERIFY_PROBE_FAIL	ERR_GROUP_ISP|ERR_SUB_GROUP_ISP_TOP|(4 << ERR_SUB_ID_BIT_OFFSET)
#define ERR_ID_ISP_SOC_PROBE_FAIL		ERR_GROUP_ISP|ERR_SUB_GROUP_ISP_TOP|(5 << ERR_SUB_ID_BIT_OFFSET)
#define ERR_ID_ISP_MD_PROBE_FAIL		ERR_GROUP_ISP|ERR_SUB_GROUP_ISP_TOP|(6 << ERR_SUB_ID_BIT_OFFSET)

//isp_iq
#define ERR_ID_ISP_IQ_MALLOC_FAIL				ERR_GROUP_ISP|ERR_SUB_GROUP_ISP_TOP|(7 << ERR_SUB_ID_BIT_OFFSET)
#define ERR_ID_ISP_IQ_ID_NOT_SUPPORT			ERR_GROUP_ISP|ERR_SUB_GROUP_ISP_TOP|(8 << ERR_SUB_ID_BIT_OFFSET)
#define ERR_ID_ISP_IQ_PB_DECODE_FAIL			ERR_GROUP_ISP|ERR_SUB_GROUP_ISP_TOP|(9 << ERR_SUB_ID_BIT_OFFSET)
#define ERR_ID_ISP_IQ_MAGIC_VERSION_FAIL		ERR_GROUP_ISP|ERR_SUB_GROUP_ISP_TOP|(10<< ERR_SUB_ID_BIT_OFFSET)
#define ERR_ID_ISP_IQ_APPLY_CALIBRATION_FAIL	ERR_GROUP_ISP|ERR_SUB_GROUP_ISP_TOP|(11<< ERR_SUB_ID_BIT_OFFSET)

//v4l2
#define ERR_ID_ISP_V4l2_FMT_NOT_SUPPORT		ERR_GROUP_ISP|ERR_SUB_GROUP_ISP_TOP|(12<< ERR_SUB_ID_BIT_OFFSET)
#define ERR_ID_ISP_V4l2_FPS_NOT_SUPPORT		ERR_GROUP_ISP|ERR_SUB_GROUP_ISP_TOP|(13<< ERR_SUB_ID_BIT_OFFSET)

//hal_isp
#define ERR_ID_ISP_VERIFY_REOPEN_FAIL	ERR_GROUP_ISP|ERR_SUB_GROUP_ISP_TOP|(14 << ERR_SUB_ID_BIT_OFFSET)

//mod_sensor
#define ERR_ID_MOD_SENSOR_EXP_OUT_RANGE				ERR_GROUP_MOD|ERR_SUB_GROUP_MOD_SENSOR|(1 << ERR_SUB_ID_BIT_OFFSET)
#define ERR_ID_MOD_SENSOR_CHECK_MOD_FAIL			ERR_GROUP_MOD|ERR_SUB_GROUP_MOD_SENSOR|(2 << ERR_SUB_ID_BIT_OFFSET)
#define ERR_ID_MOD_SENSOR_CHECK_I2C_FORMAT_FAIL		ERR_GROUP_MOD|ERR_SUB_GROUP_MOD_SENSOR|(3 << ERR_SUB_ID_BIT_OFFSET)
#define ERR_ID_MOD_SENSOR_CHECK_GPIO_FAIL			ERR_GROUP_MOD|ERR_SUB_GROUP_MOD_SENSOR|(4 << ERR_SUB_ID_BIT_OFFSET)
#define ERR_ID_MOD_SENSOR_CHECK_SIZE_OUT_RANGE 		ERR_GROUP_MOD|ERR_SUB_GROUP_MOD_SENSOR|(5 << ERR_SUB_ID_BIT_OFFSET)
#define ERR_ID_MOD_SENSOR_CHECK_CLOCK_OUT_RANGE 	ERR_GROUP_MOD|ERR_SUB_GROUP_MOD_SENSOR|(6 << ERR_SUB_ID_BIT_OFFSET)
#define ERR_ID_MOD_SENSOR_NOT_SUPPORT_SHORT_EXP 	ERR_GROUP_MOD|ERR_SUB_GROUP_MOD_SENSOR|(7 << ERR_SUB_ID_BIT_OFFSET)
#define ERR_ID_MOD_SENSOR_FPS_OUT_RANGE				ERR_GROUP_MOD|ERR_SUB_GROUP_MOD_SENSOR|(8 << ERR_SUB_ID_BIT_OFFSET)
#define ERR_ID_MOD_SENSOR_HDR_RATIO_ERR				ERR_GROUP_MOD|ERR_SUB_GROUP_MOD_SENSOR|(9 << ERR_SUB_ID_BIT_OFFSET)

//mod_ae
#define ERR_ID_MOD_AE_CHECK_ALGO_VER_FAIL		ERR_GROUP_MOD|ERR_SUB_GROUP_MOD_AE|(1 << ERR_SUB_ID_BIT_OFFSET)
#define ERR_ID_MOD_AE_CHECK_AE_EXP_GAIN_FAIL	ERR_GROUP_MOD|ERR_SUB_GROUP_MOD_AE|(2 << ERR_SUB_ID_BIT_OFFSET)
#define ERR_ID_MOD_AE_AE_FPS_OUT_RANGE			ERR_GROUP_MOD|ERR_SUB_GROUP_MOD_AE|(3 << ERR_SUB_ID_BIT_OFFSET)
#define ERR_ID_MOD_AE_INVALID_MODE				ERR_GROUP_MOD|ERR_SUB_GROUP_MOD_AE|(4 << ERR_SUB_ID_BIT_OFFSET)
#define ERR_ID_MOD_AE_HDR_MODE_OUT_RANGE		ERR_GROUP_MOD|ERR_SUB_GROUP_MOD_AE|(5 << ERR_SUB_ID_BIT_OFFSET)
#define ERR_ID_MOD_AE_EXP_TOO_SHORT				ERR_GROUP_MOD|ERR_SUB_GROUP_MOD_AE|(6 << ERR_SUB_ID_BIT_OFFSET)

//drv i2c
#define ERR_ID_DRV_I2C_WRITE_FAIL		ERR_GROUP_DRV|ERR_SUB_GROUP_DRV_I2C|(1 << ERR_SUB_ID_BIT_OFFSET)
#define ERR_ID_DRV_I2C_READ_FAIL		ERR_GROUP_DRV|ERR_SUB_GROUP_DRV_I2C|(2 << ERR_SUB_ID_BIT_OFFSET)

//drv zoom
#define ERR_ID_DRV_ZOOM_ROI_OUT_RANGE					ERR_GROUP_DRV|ERR_SUB_GROUP_DRV_ZOOM|(1 << ERR_SUB_ID_BIT_OFFSET)
#define ERR_ID_DRV_ZOOM_SCALE_DW_OUT_RANGE				ERR_GROUP_DRV|ERR_SUB_GROUP_DRV_ZOOM|(2 << ERR_SUB_ID_BIT_OFFSET)
#define ERR_ID_DRV_ZOOM_SCALE_UP_OUT_RANGE				ERR_GROUP_DRV|ERR_SUB_GROUP_DRV_ZOOM|(3 << ERR_SUB_ID_BIT_OFFSET)
#define ERR_ID_DRV_ZOOM_1SIDE_UP_1SIDE_DW				ERR_GROUP_DRV|ERR_SUB_GROUP_DRV_ZOOM|(4 << ERR_SUB_ID_BIT_OFFSET)
#define ERR_ID_DRV_ZOOM_SCALE_UP_OTHER_CH_ROI_OUT_RANGE	ERR_GROUP_DRV|ERR_SUB_GROUP_DRV_ZOOM|(5 << ERR_SUB_ID_BIT_OFFSET)
#define ERR_ID_DRV_ZOOM_SCALE_UP_CH0_CHANGE_CROP_ROI	ERR_GROUP_DRV|ERR_SUB_GROUP_DRV_ZOOM|(6 << ERR_SUB_ID_BIT_OFFSET)
#define ERR_ID_DRV_ZOOM_STREAM_RUN_BEFORE_ZOOM_IN		ERR_GROUP_DRV|ERR_SUB_GROUP_DRV_ZOOM|(7 << ERR_SUB_ID_BIT_OFFSET)

//drv video
#define ERR_ID_DRV_VIDEO_INVALID_FRAME_SIZE		ERR_GROUP_DRV|ERR_SUB_GROUP_DRV_VIDEO|(1 << ERR_SUB_ID_BIT_OFFSET)
#define ERR_ID_DRV_VIDEO_INVALID_FPS			ERR_GROUP_DRV|ERR_SUB_GROUP_DRV_VIDEO|(2 << ERR_SUB_ID_BIT_OFFSET)
#define ERR_ID_DRV_VIDEO_INVALID_FMT			ERR_GROUP_DRV|ERR_SUB_GROUP_DRV_VIDEO|(3 << ERR_SUB_ID_BIT_OFFSET)
#define ERR_ID_DRV_VIDEO_INVALID_CROP_SIZE		ERR_GROUP_DRV|ERR_SUB_GROUP_DRV_VIDEO|(4 << ERR_SUB_ID_BIT_OFFSET)

//osd api
#define ERR_ID_OSD_API_MALLOC_FAIL			ERR_GROUP_OSD|ERR_SUB_GROUP_OSD_API|(1 << ERR_SUB_ID_BIT_OFFSET)
#define ERR_ID_OSD_API_SET_PROFILE_FAIL		ERR_GROUP_OSD|ERR_SUB_GROUP_OSD_API|(2 << ERR_SUB_ID_BIT_OFFSET)
#define ERR_ID_OSD_API_PROBE_FAIL			ERR_GROUP_OSD|ERR_SUB_GROUP_OSD_API|(3 << ERR_SUB_ID_BIT_OFFSET)
#define ERR_ID_OSD_API_HW_NOT_INIT			ERR_GROUP_OSD|ERR_SUB_GROUP_OSD_API|(4 << ERR_SUB_ID_BIT_OFFSET)
#define ERR_ID_OSD_API_ALREADY_DEINIT		ERR_GROUP_OSD|ERR_SUB_GROUP_OSD_API|(5 << ERR_SUB_ID_BIT_OFFSET)
#define ERR_ID_OSD_API_FREE_BUF_FAIL		ERR_GROUP_OSD|ERR_SUB_GROUP_OSD_API|(6 << ERR_SUB_ID_BIT_OFFSET)
#define ERR_ID_OSD_API_BLOCK_NOT_ENABLE		ERR_GROUP_OSD|ERR_SUB_GROUP_OSD_API|(7 << ERR_SUB_ID_BIT_OFFSET)
#define ERR_ID_OSD_API_FRAME_NOT_ALIGN		ERR_GROUP_OSD|ERR_SUB_GROUP_OSD_API|(8 << ERR_SUB_ID_BIT_OFFSET)
#define ERR_ID_OSD_API_ENCODE_FAIL			ERR_GROUP_OSD|ERR_SUB_GROUP_OSD_API|(9 << ERR_SUB_ID_BIT_OFFSET)
#define ERR_ID_OSD_API_INVALID_CH			ERR_GROUP_OSD|ERR_SUB_GROUP_OSD_API|(10<< ERR_SUB_ID_BIT_OFFSET)
#define ERR_ID_OSD_API_BLOCK_NUM_ZERO		ERR_GROUP_OSD|ERR_SUB_GROUP_OSD_API|(11<< ERR_SUB_ID_BIT_OFFSET)

#define ERR_ID_OSD_API_WRONG_AREA			ERR_GROUP_OSD|ERR_SUB_GROUP_OSD_API|(12<< ERR_SUB_ID_BIT_OFFSET)
#define ERR_ID_OSD_API_COOR_ODD				ERR_GROUP_OSD|ERR_SUB_GROUP_OSD_API|(13<< ERR_SUB_ID_BIT_OFFSET)
#define ERR_ID_OSD_API_FMT_NOT_SUPPORT		ERR_GROUP_OSD|ERR_SUB_GROUP_OSD_API|(14<< ERR_SUB_ID_BIT_OFFSET)
#define ERR_ID_OSD_API_BLOCK_IDX_INVALID	ERR_GROUP_OSD|ERR_SUB_GROUP_OSD_API|(15<< ERR_SUB_ID_BIT_OFFSET)

#endif	// RT_CODE_H
