#ifndef _VERIFY_H_INC_
#define _VERIFY_H_INC_

#include <stdint.h>
#include "isp_reg_lib.h"

#define ARRAY_SIZE(array) (sizeof(array) / sizeof(array[0]))

#define VERIFY_REG_BASE 0xB000
#define VERIFY_SEL (VERIFY_REG_BASE + 0x0000)
#define VERIFY_CTRL (VERIFY_REG_BASE + 0x0004)
#define VERIFY_Y_DDR_ADDR0 (VERIFY_REG_BASE + 0x0008)
#define VERIFY_Y_DDR_ADDR1 (VERIFY_REG_BASE + 0x000C)
#define VERIFY_UV_DDR_ADDR0 (VERIFY_REG_BASE + 0x0010)
#define VERIFY_UV_DDR_ADDR1 (VERIFY_REG_BASE + 0x0014)
#define VERIFY_DDR_ADDR_SEL (VERIFY_REG_BASE + 0x0018)
#define VERIFY_Y_DDR_LEN (VERIFY_REG_BASE + 0x001C)
#define VERIFY_UV_DDR_LEN (VERIFY_REG_BASE + 0x0020)
#define VERIFY_FRAME_NUM (VERIFY_REG_BASE + 0x0024)
#define VERIFY_FRAME_FORMAT (VERIFY_REG_BASE + 0x0028)
#define VERIFY_FRAME_SIZE (VERIFY_REG_BASE + 0x002C)
#define VERIFY_FRAME_CONFG0 (VERIFY_REG_BASE + 0x0030)
#define VERIFY_FRAME_CONFG1 (VERIFY_REG_BASE + 0x0034)
#define VERIFY_INT_EN (VERIFY_REG_BASE + 0x0038)
#define VERIFY_INT_FLAG (VERIFY_REG_BASE + 0x003C)
#define VERIFY_START_FLAG (VERIFY_REG_BASE + 0x0040)
#define VERIFY_STOP_FLAG (VERIFY_REG_BASE + 0x0044)

enum verify_mode {
	VERIFY_RAW12_LOCATION,
	VERIFY_RAW14_LOCATION,
	VERIFY_RGB_LOCATION,
	VERIFY_YUV444_LOCATION,
	VERIFY_YUV422_LOCATION,
	VERIFY_ZOOM_LOCATION,
	VERIFY_AI_LOCATION,
};

#endif /* _VERIFY_H_INC_ */

