#ifndef _RTS_CAMERA_ISP_REGS_H
#define _RTS_CAMERA_ISP_REGS_H

#define SYS_REG_BASE 0x0000
#define SYS_CONTROL0 (SYS_REG_BASE + 0x0000)
#define SYS_INT_EN0 (SYS_REG_BASE + 0x0010)
#define SYS_INT_FLAG0 (SYS_REG_BASE + 0x0014)
#define SYS_IDLE (SYS_REG_BASE + 0x0028)
#define SYS_DATA_DELAY (SYS_REG_BASE + 0x0040)
#define SYS_IMAGE_SEL0 (SYS_REG_BASE + 0x0048)
#define SYS_IMAGE_MODE_SEL (SYS_REG_BASE + 0x0064)
#define SYS_STATIS_CTRL (SYS_REG_BASE + 0x006C)
#define SYS_IMAGE_AI_CHAN_SEL (SYS_REG_BASE + 0x0078)

#define AE_REG_BASE 0xBC00
#define AE_GAIN (AE_REG_BASE + 0x0080)
#define AE_GAIN_CTRL (AE_REG_BASE + 0x0088)

#define AWB_REG_BASE 0xC000
#define AWB_FINE_WP_NUM (AWB_REG_BASE + 0x0088)
#define AWB_FINE_SUM_R (AWB_REG_BASE + 0x008C)
#define AWB_FINE_SUM_G (AWB_REG_BASE + 0x0090)
#define AWB_FINE_SUM_B (AWB_REG_BASE + 0x0094)
#define AWB_WP_NUM (AWB_REG_BASE + 0x00C0)

#define AF_REG_BASE 0x5C00
#define AF_NUM0 (AF_REG_BASE + 0x0030)
#define AF_NUM1 (AF_REG_BASE + 0x0034)
#define AF_SUM0 (AF_REG_BASE + 0x00AC)
#define AF_SUM1 (AF_REG_BASE + 0x00B0)

#define FLICK_REG_BASE 0xA000
#define FLICK_CTRL (FLICK_REG_BASE + 0x0000)
#define FLICK_FFT_RESUT_SUM2_127 (FLICK_REG_BASE + 0x0010)
#define FLICK_FFT_RESUT_SUM2_9 (FLICK_REG_BASE + 0x0014)

#define MCROP_REG_BASE 0x4C00
#define MCROP_START_X (MCROP_REG_BASE + 0x0000)
#define MCROP_START_Y (MCROP_REG_BASE + 0x0004)
#define MCROP_FRAME_WIDTH (MCROP_REG_BASE + 0x0008)
#define MCROP_FRAME_HEIGHT (MCROP_REG_BASE + 0x000C)
#define MCROP_REG_LOAD (MCROP_REG_BASE + 0x0010)

#define ZOOM_REG_BASE 0x10000
#define ZOOM_CH0_CTRL (ZOOM_REG_BASE + 0x0000)
#define ZOOM_CH0_CROP_START (ZOOM_REG_BASE + 0x0004)
#define ZOOM_CH0_OUTPUT_SIZE (ZOOM_REG_BASE + 0x0008)
#define ZOOM_CH0_COEF0 (ZOOM_REG_BASE + 0x0010)
#define ZOOM_CH0_COEF1 (ZOOM_REG_BASE + 0x0014)
#define ZOOM_CH0_COEF2 (ZOOM_REG_BASE + 0x0018)
#define ZOOM_CH0_COEF3 (ZOOM_REG_BASE + 0x001C)
#define ZOOM_CH0_COEF4 (ZOOM_REG_BASE + 0x0020)
#define ZOOM_CH0_SCALE_UP_EN (ZOOM_REG_BASE + 0x002C)
#define ZOOM_CH0_STEP_V (ZOOM_REG_BASE + 0x0048)
#define ZOOM_CH0_STEP_H (ZOOM_REG_BASE + 0x004C)
#define ZOOM_CH0_REG_LOAD (ZOOM_REG_BASE + 0x0024)
#define ZOOM_CH_REG_OFFSET 0x80

#define STATIS_REG_BASE 0xb800
#define STATIS_CTRL (STATIS_REG_BASE + 0x0000)
#define STATIS_DDR_ADDR (STATIS_REG_BASE + 0x000C)
#define STATIS_DDR_LEN (STATIS_REG_BASE + 0x0010)
#define STATIS_BUF_SIZE (STATIS_REG_BASE + 0x0014)
#define STATIS_BLOCK_EN (STATIS_REG_BASE + 0x0020)

#define TNR_REG_BASE 0x5800
#define TNR_CTRL (TNR_REG_BASE + 0x0000)
#define TNR_STREAM_BUF_CFG (TNR_REG_BASE + 0x03D0)

#define IVE_REG_BASE 0x11000
#define IVE_ENABLE (IVE_REG_BASE + 0x0000)
#define IVE_NORM_MEAN (IVE_REG_BASE + 0x0004)
#define IVE_NORM_SCALE (IVE_REG_BASE + 0x0008)
#define IVE_QUANT_LEN (IVE_REG_BASE + 0x000C)
#define IVE_ASYM_INV_SCALE (IVE_REG_BASE + 0x0010)
#define IVE_ASYM_ZERO_POINT (IVE_REG_BASE + 0x0014)

/* SYS_IMAGE_SEL0 */
#define SEL_FINAL_OUTPUT 0x0
/* ZOOM_CH0_CTRL */
#define ENABLE_ZOOM 0x1
#define DISABLE_ZOOM 0x2
/* ZOOM_CH0_REG_LOAD */
#define LOAD_ZOOM_PARAM 0x1
/* SYS_INT_EN0 */
#define AWB_STATIS_INT BIT(0)
#define AF_STATIS_INT BIT(1)
#define AE_STATIS_INT BIT(3)
#define FRAME_START_INT BIT(4)
#define FRAME_END_INT BIT(5)
#define DATA_START_INT BIT(6)
#define DATA_END_INT BIT(7)
#define FLICK_STATIS_INT BIT(8)
#define RAW_STATIS_INT BIT(9)
#define Y_STATIS_INT BIT(10)
#define STATIS_STREAM_INT BIT(11)
#define STATIS_ALL_INT (AWB_STATIS_INT | AF_STATIS_INT |  AE_STATIS_INT | \
			RAW_STATIS_INT | Y_STATIS_INT | STATIS_STREAM_INT)
/* STATIS_CTRL */
#define STATIS_STREAM_EN 0x1

#endif /* _RTS_CAMERA_ISP_REGS_H */

