#ifndef _ISP_REG_FIXP_H_INC_
#define _ISP_REG_FIXP_H_INC_

#include <isp_reg_lib.h>

#define FIXP_REG_BASE 0x0800

#define FIXP_FRAME_WIDTH (FIXP_REG_BASE + 0x0000)
#define FIXP_FRAME_HEIGHT (FIXP_REG_BASE + 0x0004)
#define FIXP_DUMMY_PIX (FIXP_REG_BASE + 0x0008)
#define FIXP_DUMMY_LINE (FIXP_REG_BASE + 0x000C)
#define FIXP_SPEED_CTRL (FIXP_REG_BASE + 0x0010)
#define FIXP_FRAME_NUM (FIXP_REG_BASE + 0x0014)
#define FIXP_NOISE_MASK (FIXP_REG_BASE + 0x0018)
#define FIXP_RND_INTI_VAL (FIXP_REG_BASE + 0x001C)
#define FIXP_CTRL (FIXP_REG_BASE + 0x0020)
#define BLOCK_START_X (FIXP_REG_BASE + 0x0028)
#define BLOCK_START_Y (FIXP_REG_BASE + 0x002C)
#define BLOCK_WIDTH (FIXP_REG_BASE + 0x0030)
#define BLOCK_HEIGHT (FIXP_REG_BASE + 0x0034)
#define MARGIN_WIDTH (FIXP_REG_BASE + 0x0038)
#define MARGIN_HEIGHT (FIXP_REG_BASE + 0x003C)

/* FIXP_FRAME_WIDTH 0x0000 */
#define FIXP_FRAME_WIDTH_OFFSET 0
#define FIXP_FRAME_WIDTH_BITS 16
#define FIXP_FRAME_WIDTH_MASK (((1 << 16) - 1) << 0)
/* FIXP_FRAME_HEIGHT 0x0004 */
#define FIXP_FRAME_HEIGHT_OFFSET 0
#define FIXP_FRAME_HEIGHT_BITS 16
#define FIXP_FRAME_HEIGHT_MASK (((1 << 16) - 1) << 0)
/* FIXP_DUMMY_PIX 0x0008 */
#define FIXP_DMY_PIX_OFFSET 0
#define FIXP_DMY_PIX_BITS 16
#define FIXP_DMY_PIX_MASK (((1 << 16) - 1) << 0)
/* FIXP_DUMMY_LINE 0x000C */
#define FIXP_DMY_LINE_OFFSET 0
#define FIXP_DMY_LINE_BITS 16
#define FIXP_DMY_LINE_MASK (((1 << 16) - 1) << 0)
/* FIXP_SPEED_CTRL 0x0010 */
#define FIXP_SPEED_MULT_OFFSET 0
#define FIXP_SPEED_MULT_BITS 3
#define FIXP_SPEED_MULT_MASK (((1 << 3) - 1) << 0)
#define FIXP_SPEED_DIV_OFFSET 3
#define FIXP_SPEED_DIV_BITS 5
#define FIXP_SPEED_DIV_MASK (((1 << 5) - 1) << 3)
/* FIXP_FRAME_NUM 0x0014 */
#define FIXP_FRAME_NUM_OFFSET 0
#define FIXP_FRAME_NUM_BITS 8
#define FIXP_FRAME_NUM_MASK (((1 << 8) - 1) << 0)
/* FIXP_NOISE_MASK 0x0018 */
#define FIXP_NOISE_MASK_OFFSET 0
#define FIXP_NOISE_MASK_BITS 16
#define FIXP_NOISE_MASK_MASK (((1 << 16) - 1) << 0)
/* FIXP_RND_INTI_VAL 0x001C */
/* FIXP_CTRL 0x0020 */
#define FIXP_BLACK_WHITE_SIZE_OFFSET 0
#define FIXP_BLACK_WHITE_SIZE_BITS 4
#define FIXP_BLACK_WHITE_SIZE_MASK (((1 << 4) - 1) << 0)
#define FIXP_PIC_MODE_OFFSET 4
#define FIXP_PIC_MODE_BITS 2
#define FIXP_PIC_MODE_MASK (((1 << 2) - 1) << 4)
#define FIXP_YUV_SEL_OFFSET 6
#define FIXP_YUV_SEL_BITS 1
#define FIXP_YUV_SEL_MASK (((1 << 1) - 1) << 6)
#define FIXP_SSOR_RUN_OFFSET 7
#define FIXP_SSOR_RUN_BITS 1
#define FIXP_SSOR_RUN_MASK (((1 << 1) - 1) << 7)
#define FIXP_GOING_OFFSET 8
#define FIXP_GOING_BITS 1
#define FIXP_GOING_MASK (((1 << 1) - 1) << 8)
/* BLOCK_START_X 0x0028 */
#define BLOCK_START_X_OFFSET 0
#define BLOCK_START_X_BITS 12
#define BLOCK_START_X_MASK (((1 << 12) - 1) << 0)
/* BLOCK_START_Y 0x002C */
#define BLOCK_START_Y_OFFSET 0
#define BLOCK_START_Y_BITS 12
#define BLOCK_START_Y_MASK (((1 << 12) - 1) << 0)
/* BLOCK_WIDTH 0x0030 */
#define BLOCK_WIDTH_OFFSET 0
#define BLOCK_WIDTH_BITS 12
#define BLOCK_WIDTH_MASK (((1 << 12) - 1) << 0)
/* BLOCK_HEIGHT 0x0034 */
#define BLOCK_HEIGHT_OFFSET 0
#define BLOCK_HEIGHT_BITS 12
#define BLOCK_HEIGHT_MASK (((1 << 12) - 1) << 0)
/* MARGIN_WIDTH 0x0038 */
#define MARGIN_WIDTH_OFFSET 0
#define MARGIN_WIDTH_BITS 12
#define MARGIN_WIDTH_MASK (((1 << 12) - 1) << 0)
/* MARGIN_HEIGHT 0x003C */
#define MARGIN_HEIGHT_OFFSET 0
#define MARGIN_HEIGHT_BITS 12
#define MARGIN_HEIGHT_MASK (((1 << 12) - 1) << 0)

#endif /* _ISP_REG_FIXP_H_INC_ */

