#ifndef _ISP_REG_MIPIIN_H_INC_
#define _ISP_REG_MIPIIN_H_INC_

#include <isp_reg.h>
#include <isp_reg_base.h>

#define MIPI_APHY_REG0 (MIPIIN_REG_BASE + 0x0000)
#define MIPI_APHY_REG1 (MIPIIN_REG_BASE + 0x0004)
#define MIPI_APHY_REG2 (MIPIIN_REG_BASE + 0x0008)
#define MIPI_APHY_REG3 (MIPIIN_REG_BASE + 0x000C)
#define MIPI_APHY_REG4 (MIPIIN_REG_BASE + 0x0010)
#define MIPI_APHY_REG5 (MIPIIN_REG_BASE + 0x0014)
#define MIPI_APHY_REG6 (MIPIIN_REG_BASE + 0x0018)
#define MIPI_APHY_REG7 (MIPIIN_REG_BASE + 0x001C)
#define MIPI_APHY_REG8 (MIPIIN_REG_BASE + 0x0020)
#define MIPI_APHY_REG9 (MIPIIN_REG_BASE + 0x0024)
#define MIPI_APHY_REG10 (MIPIIN_REG_BASE + 0x0028)
#define MIPI_APHY_REG11 (MIPIIN_REG_BASE + 0x002C)
#define MIPI_APHY_REG14 (MIPIIN_REG_BASE + 0x0038)
#define MIPI_APHY_REG15 (MIPIIN_REG_BASE + 0x003C)
#define MIPI_APHY_REG16 (MIPIIN_REG_BASE + 0x0040)
#define MIPI_APHY_REG17 (MIPIIN_REG_BASE + 0x0044)
#define MIPI_APHY_REG18 (MIPIIN_REG_BASE + 0x0048)
#define MIPI_APHY_REG19 (MIPIIN_REG_BASE + 0x004C)
#define MIPI_APHY_REG20 (MIPIIN_REG_BASE + 0x0050)
#define MIPI_APHY_REG21 (MIPIIN_REG_BASE + 0x0054)
#define MIPI_APHY_REG22 (MIPIIN_REG_BASE + 0x0058)
#define MIPI_APHY_REG23 (MIPIIN_REG_BASE + 0x005C)
#define MIPI_APHY_REG24 (MIPIIN_REG_BASE + 0x0060)
#define MIPI_APHY_REG25 (MIPIIN_REG_BASE + 0x0064)
#define MIPI_APHY_REG26 (MIPIIN_REG_BASE + 0x0068)
#define MIPI_APHY_REG27 (MIPIIN_REG_BASE + 0x006C)
#define MIPI_DPHY_RXPRE_LANE (MIPIIN_REG_BASE + 0x0100)
#define MIPI_DPHY_RXPOS_LANE (MIPIIN_REG_BASE + 0x0104)
#define MIPI_DPHY_PWDB (MIPIIN_REG_BASE + 0x0108)
#define MIPI_DPHY_LANE_EN (MIPIIN_REG_BASE + 0x010C)
#define MIPI_DPHY_VC0_DATA_FORMAT (MIPIIN_REG_BASE + 0x0110)
#define MIPI_DPHY_VC1_DATA_FORMAT (MIPIIN_REG_BASE + 0x0114)
#define MIPI_DPHY_VC2_DATA_FORMAT (MIPIIN_REG_BASE + 0x0118)
#define MIPI_DPHY_VC3_DATA_FORMAT (MIPIIN_REG_BASE + 0x011C)
#define MIPI_DPHY_DEG_SEL (MIPIIN_REG_BASE + 0x0120)
#define MIPI_DPHY_LANE_CTRL (MIPIIN_REG_BASE + 0x0124)
#define MIPI_DPHY_CFG0 (MIPIIN_REG_BASE + 0x0128)
#define MIPI_DPHY_HSTERM0 (MIPIIN_REG_BASE + 0x012C)
#define MIPI_DPHY_HSTERM1 (MIPIIN_REG_BASE + 0x0130)
#define MIPI_DPHY_LANE_SEL (MIPIIN_REG_BASE + 0x0134)
#define MIPI_DPHY_HSCLK_SEL (MIPIIN_REG_BASE + 0x0138)
#define MIPI_DPHY_INTP_EN (MIPIIN_REG_BASE + 0x013C)
#define MIPI_DPHY_INTP_FLAG (MIPIIN_REG_BASE + 0x0140)
#define MIPI_DPHY_ECC_CNT_L (MIPIIN_REG_BASE + 0x0144)
#define MIPI_DPHY_CHECK (MIPIIN_REG_BASE + 0x0148)
#define MIPI_DPHY_CRC_CNT_L (MIPIIN_REG_BASE + 0x014C)
#define MIPI_DPHY_FRM_SIZE (MIPIIN_REG_BASE + 0x0150)
#define MIPI_DPHY_TERM_CFG (MIPIIN_REG_BASE + 0x0154)
#define MIPI_DPHY_DIVSEL (MIPIIN_REG_BASE + 0x0158)
#define MIPI_DPHY_WKUP_H (MIPIIN_REG_BASE + 0x015C)
#define MIPI_DPHY_DBG_MODE (MIPIIN_REG_BASE + 0x0160)
#define MIPI_DPHY_ESCAPE0 (MIPIIN_REG_BASE + 0x0164)
#define MIPI_DPHY_ESCAPE1 (MIPIIN_REG_BASE + 0x0168)
#define MIPI_DUMMY_REG0 (MIPIIN_REG_BASE + 0x016C)
#define MIPI_DUMMY_REG1 (MIPIIN_REG_BASE + 0x0170)
#define MIPI_DUMMY_REG2 (MIPIIN_REG_BASE + 0x0174)
#define MIPI_DPHY_HS_TERM_BITS_EN (MIPIIN_REG_BASE + 0x0178)
#define MIPI_DPHY_HS_TERM_BITS_LANE0 (MIPIIN_REG_BASE + 0x017C)
#define MIPI_DPHY_HS_TERM_BITS_LANE1 (MIPIIN_REG_BASE + 0x0180)
#define MIPI_DPHY_HS_TERM_BITS_LANE2 (MIPIIN_REG_BASE + 0x0184)
#define MIPI_DPHY_HS_TERM_BITS_LANE3 (MIPIIN_REG_BASE + 0x0188)
#define MIPI_DPHY_DIV16CNT_RST_TERM_SEL (MIPIIN_REG_BASE + 0x018C)
#define MIPI_DPHY_DIV16CNT_RST_SEL (MIPIIN_REG_BASE + 0x0190)
#define MIPI_DPHY_MERGE_OVERFLOW_CNT (MIPIIN_REG_BASE + 0x0194)
#define MIPI_DPHY_FRAME_CNT (MIPIIN_REG_BASE + 0x0198)
#define MIPI_DPHY_LINE_CNT (MIPIIN_REG_BASE + 0x019C)
#define MIPI_DPHY_PIX_CNT (MIPIIN_REG_BASE + 0x01A0)
#define MIPI_DPHY_FRAME_HEIGHT (MIPIIN_REG_BASE + 0x01A4)
#define MIPI_DPHY_FRAME_WIDTH (MIPIIN_REG_BASE + 0x01A8)
#define MIPI_DPHY_STACNT_EN (MIPIIN_REG_BASE + 0x01AC)
#define MIPI_DPHY_INPUT_MODE (MIPIIN_REG_BASE + 0x01B0)
#define MIPI_DPHY_MAX_SRT_EXP (MIPIIN_REG_BASE + 0x01B4)
#define MIPI_DPHY_FID (MIPIIN_REG_BASE + 0x01B8)

/* MIPI_APHY_REG0 0x0000 */
#define R50_CAL_RG_OFFSET 0
#define R50_CAL_RG_BITS 6
#define R50_CAL_RG_MASK (((1 << 6) - 1) << 0)
#define HS_CM_OFFSET 8
#define HS_CM_BITS 3
#define HS_CM_MASK (((1 << 3) - 1) << 8)
/* MIPI_APHY_REG1 0x0004 */
#define EN_R50_AUTO_CAL_RG_OFFSET 0
#define EN_R50_AUTO_CAL_RG_BITS 1
#define EN_R50_AUTO_CAL_RG_MASK (((1 << 1) - 1) << 0)
#define EN_R50_CAL_RG_OFFSET 1
#define EN_R50_CAL_RG_BITS 1
#define EN_R50_CAL_RG_MASK (((1 << 1) - 1) << 1)
#define EN_AUTO_OSK_OFFSET 2
#define EN_AUTO_OSK_BITS 1
#define EN_AUTO_OSK_MASK (((1 << 1) - 1) << 2)
#define EN_SKW_OFFSET 7
#define EN_SKW_BITS 1
#define EN_SKW_MASK (((1 << 1) - 1) << 7)
/* MIPI_APHY_REG2 0x0008 */
#define PWDB_OSK_OFFSET 2
#define PWDB_OSK_BITS 1
#define PWDB_OSK_MASK (((1 << 1) - 1) << 2)
#define PDBH_K_OFFSET 3
#define PDBH_K_BITS 1
#define PDBH_K_MASK (((1 << 1) - 1) << 3)
#define LGTH_D0_OFFSET 4
#define LGTH_D0_BITS 3
#define LGTH_D0_MASK (((1 << 3) - 1) << 4)
/* MIPI_APHY_REG3 0x000C */
#define HSAMP0_RL_RG_OFFSET 0
#define HSAMP0_RL_RG_BITS 6
#define HSAMP0_RL_RG_MASK (((1 << 6) - 1) << 0)
/* MIPI_APHY_REG4 0x0010 */
#define HSAMP1_RL_RG_OFFSET 0
#define HSAMP1_RL_RG_BITS 6
#define HSAMP1_RL_RG_MASK (((1 << 6) - 1) << 0)
/* MIPI_APHY_REG5 0x0014 */
#define HSAMP2_RL_RG_OFFSET 0
#define HSAMP2_RL_RG_BITS 6
#define HSAMP2_RL_RG_MASK (((1 << 6) - 1) << 0)
/* MIPI_APHY_REG6 0x0018 */
#define HSAMP3_RL_RG_OFFSET 0
#define HSAMP3_RL_RG_BITS 6
#define HSAMP3_RL_RG_MASK (((1 << 6) - 1) << 0)
/* MIPI_APHY_REG7 0x001C */
#define SDATA1_SKW_RG_OFFSET 0
#define SDATA1_SKW_RG_BITS 4
#define SDATA1_SKW_RG_MASK (((1 << 4) - 1) << 0)
#define SDATA0_SKW_RG_OFFSET 4
#define SDATA0_SKW_RG_BITS 4
#define SDATA0_SKW_RG_MASK (((1 << 4) - 1) << 4)
/* MIPI_APHY_REG8 0x0020 */
#define SDATA3_SKW_RG_OFFSET 0
#define SDATA3_SKW_RG_BITS 4
#define SDATA3_SKW_RG_MASK (((1 << 4) - 1) << 0)
#define SDATA2_SKW_RG_OFFSET 4
#define SDATA2_SKW_RG_BITS 4
#define SDATA2_SKW_RG_MASK (((1 << 4) - 1) << 4)
/* MIPI_APHY_REG9 0x0024 */
#define SCLK1_SKW_RG_OFFSET 0
#define SCLK1_SKW_RG_BITS 4
#define SCLK1_SKW_RG_MASK (((1 << 4) - 1) << 0)
#define SCLK0_SKW_RG_OFFSET 4
#define SCLK0_SKW_RG_BITS 4
#define SCLK0_SKW_RG_MASK (((1 << 4) - 1) << 4)
/* MIPI_APHY_REG10 0x0028 */
#define SCLK3_SKW_RG_OFFSET 0
#define SCLK3_SKW_RG_BITS 4
#define SCLK3_SKW_RG_MASK (((1 << 4) - 1) << 0)
#define SCLK2_SKW_RG_OFFSET 4
#define SCLK2_SKW_RG_BITS 4
#define SCLK2_SKW_RG_MASK (((1 << 4) - 1) << 4)
/* MIPI_APHY_REG11 0x002C */
#define HSAMPCK_RL_RG_OFFSET 0
#define HSAMPCK_RL_RG_BITS 6
#define HSAMPCK_RL_RG_MASK (((1 << 6) - 1) << 0)
/* MIPI_APHY_REG14 0x0038 */
#define LPAMP_REF_OFFSET 0
#define LPAMP_REF_BITS 4
#define LPAMP_REF_MASK (((1 << 4) - 1) << 0)
/* MIPI_APHY_REG15 0x003C */
#define SEL_DIV_RG_OFFSET 0
#define SEL_DIV_RG_BITS 2
#define SEL_DIV_RG_MASK (((1 << 2) - 1) << 0)
#define SEL0_PWDB_DEMUX_OFFSET 2
#define SEL0_PWDB_DEMUX_BITS 2
#define SEL0_PWDB_DEMUX_MASK (((1 << 2) - 1) << 2)
/* MIPI_APHY_REG16 0x0040 */
#define HSAMP3_RL_2RG_OFFSET 0
#define HSAMP3_RL_2RG_BITS 6
#define HSAMP3_RL_2RG_MASK (((1 << 6) - 1) << 0)
/* MIPI_APHY_REG17 0x0044 */
#define HSAMP2_RL_2RG_OFFSET 0
#define HSAMP2_RL_2RG_BITS 6
#define HSAMP2_RL_2RG_MASK (((1 << 6) - 1) << 0)
/* MIPI_APHY_REG18 0x0048 */
#define HSAMP1_RL_2RG_OFFSET 0
#define HSAMP1_RL_2RG_BITS 6
#define HSAMP1_RL_2RG_MASK (((1 << 6) - 1) << 0)
/* MIPI_APHY_REG19 0x004C */
#define HSAMP0_RL_2RG_OFFSET 0
#define HSAMP0_RL_2RG_BITS 6
#define HSAMP0_RL_2RG_MASK (((1 << 6) - 1) << 0)
/* MIPI_APHY_REG20 0x0050 */
#define HSAMPCK_RL_2RG_OFFSET 0
#define HSAMPCK_RL_2RG_BITS 5
#define HSAMPCK_RL_2RG_MASK (((1 << 5) - 1) << 0)
/* MIPI_APHY_REG21 0x0054 */
#define CLK1_DLY_CODE_2RG_OFFSET 0
#define CLK1_DLY_CODE_2RG_BITS 4
#define CLK1_DLY_CODE_2RG_MASK (((1 << 4) - 1) << 0)
#define CLK0_DLY_CODE_2RG_OFFSET 4
#define CLK0_DLY_CODE_2RG_BITS 4
#define CLK0_DLY_CODE_2RG_MASK (((1 << 4) - 1) << 4)
/* MIPI_APHY_REG22 0x0058 */
#define CLK3_DLY_CODE_2RG_OFFSET 0
#define CLK3_DLY_CODE_2RG_BITS 4
#define CLK3_DLY_CODE_2RG_MASK (((1 << 4) - 1) << 0)
#define CLK2_DLY_CODE_2RG_OFFSET 4
#define CLK2_DLY_CODE_2RG_BITS 4
#define CLK2_DLY_CODE_2RG_MASK (((1 << 4) - 1) << 4)
/* MIPI_APHY_REG23 0x005C */
#define DATA1_DLY_CODE_2RG_OFFSET 0
#define DATA1_DLY_CODE_2RG_BITS 4
#define DATA1_DLY_CODE_2RG_MASK (((1 << 4) - 1) << 0)
#define DATA0_DLY_CODE_2RG_OFFSET 4
#define DATA0_DLY_CODE_2RG_BITS 4
#define DATA0_DLY_CODE_2RG_MASK (((1 << 4) - 1) << 4)
/* MIPI_APHY_REG24 0x0060 */
#define DATA3_DLY_CODE_2RG_OFFSET 0
#define DATA3_DLY_CODE_2RG_BITS 4
#define DATA3_DLY_CODE_2RG_MASK (((1 << 4) - 1) << 0)
#define DATA2_DLY_CODE_2RG_OFFSET 4
#define DATA2_DLY_CODE_2RG_BITS 4
#define DATA2_DLY_CODE_2RG_MASK (((1 << 4) - 1) << 4)
/* MIPI_APHY_REG25 0x0064 */
#define R50_CAL_2RG_OFFSET 0
#define R50_CAL_2RG_BITS 6
#define R50_CAL_2RG_MASK (((1 << 6) - 1) << 0)
#define R50_CAL_OK_2RG_OFFSET 6
#define R50_CAL_OK_2RG_BITS 1
#define R50_CAL_OK_2RG_MASK (((1 << 1) - 1) << 6)
/* MIPI_APHY_REG26 0x0068 */
#define LANE_OK_OFFSET 0
#define LANE_OK_BITS 4
#define LANE_OK_MASK (((1 << 4) - 1) << 0)
/* MIPI_APHY_REG27 0x006C */
#define RT_POW1_OFFSET 0
#define RT_POW1_BITS 1
#define RT_POW1_MASK (((1 << 1) - 1) << 0)
/* MIPI_DPHY_RXPRE_LANE 0x0100 */
#define RXPRE_LANE_OFFSET 0
#define RXPRE_LANE_BITS 8
#define RXPRE_LANE_MASK (((1 << 8) - 1) << 0)
/* MIPI_DPHY_RXPOS_LANE 0x0104 */
#define RXPOS_LANE_OFFSET 0
#define RXPOS_LANE_BITS 8
#define RXPOS_LANE_MASK (((1 << 8) - 1) << 0)
/* MIPI_DPHY_PWDB 0x0108 */
#define LANE0_PWDB_OFFSET 0
#define LANE0_PWDB_BITS 1
#define LANE0_PWDB_MASK (((1 << 1) - 1) << 0)
#define LANE1_PWDB_OFFSET 1
#define LANE1_PWDB_BITS 1
#define LANE1_PWDB_MASK (((1 << 1) - 1) << 1)
#define LANE2_PWDB_OFFSET 2
#define LANE2_PWDB_BITS 1
#define LANE2_PWDB_MASK (((1 << 1) - 1) << 2)
#define LANE3_PWDB_OFFSET 3
#define LANE3_PWDB_BITS 1
#define LANE3_PWDB_MASK (((1 << 1) - 1) << 3)
/* MIPI_DPHY_LANE_EN 0x010C */
#define LANE0_EN_OFFSET 0
#define LANE0_EN_BITS 1
#define LANE0_EN_MASK (((1 << 1) - 1) << 0)
#define LANE1_EN_OFFSET 1
#define LANE1_EN_BITS 1
#define LANE1_EN_MASK (((1 << 1) - 1) << 1)
#define LANE2_EN_OFFSET 2
#define LANE2_EN_BITS 1
#define LANE2_EN_MASK (((1 << 1) - 1) << 2)
#define LANE3_EN_OFFSET 3
#define LANE3_EN_BITS 1
#define LANE3_EN_MASK (((1 << 1) - 1) << 3)
/* MIPI_DPHY_VC0_DATA_FORMAT 0x0110 */
#define DEC_ID0_OFFSET 0
#define DEC_ID0_BITS 8
#define DEC_ID0_MASK (((1 << 8) - 1) << 0)
#define DEC_FORMAT0_OFFSET 8
#define DEC_FORMAT0_BITS 3
#define DEC_FORMAT0_MASK (((1 << 3) - 1) << 8)
#define YUV_SRC_SEL0_OFFSET 16
#define YUV_SRC_SEL0_BITS 2
#define YUV_SRC_SEL0_MASK (((1 << 2) - 1) << 16)
/* MIPI_DPHY_VC1_DATA_FORMAT 0x0114 */
#define DEC_ID1_OFFSET 0
#define DEC_ID1_BITS 8
#define DEC_ID1_MASK (((1 << 8) - 1) << 0)
#define DEC_FORMAT1_OFFSET 8
#define DEC_FORMAT1_BITS 3
#define DEC_FORMAT1_MASK (((1 << 3) - 1) << 8)
#define YUV_SRC_SEL1_OFFSET 16
#define YUV_SRC_SEL1_BITS 2
#define YUV_SRC_SEL1_MASK (((1 << 2) - 1) << 16)
/* MIPI_DPHY_VC2_DATA_FORMAT 0x0118 */
#define DEC_ID2_OFFSET 0
#define DEC_ID2_BITS 8
#define DEC_ID2_MASK (((1 << 8) - 1) << 0)
#define DEC_FORMAT2_OFFSET 8
#define DEC_FORMAT2_BITS 3
#define DEC_FORMAT2_MASK (((1 << 3) - 1) << 8)
#define YUV_SRC_SEL2_OFFSET 16
#define YUV_SRC_SEL2_BITS 2
#define YUV_SRC_SEL2_MASK (((1 << 2) - 1) << 16)
/* MIPI_DPHY_VC3_DATA_FORMAT 0x011C */
#define DEC_ID3_OFFSET 0
#define DEC_ID3_BITS 8
#define DEC_ID3_MASK (((1 << 8) - 1) << 0)
#define DEC_FORMAT3_OFFSET 8
#define DEC_FORMAT3_BITS 3
#define DEC_FORMAT3_MASK (((1 << 3) - 1) << 8)
#define YUV_SRC_SEL3_OFFSET 16
#define YUV_SRC_SEL3_BITS 2
#define YUV_SRC_SEL3_MASK (((1 << 2) - 1) << 16)
/* MIPI_DPHY_DEG_SEL 0x0120 */
#define DEGLITCH_CFG_OFFSET 0
#define DEGLITCH_CFG_BITS 5
#define DEGLITCH_CFG_MASK (((1 << 5) - 1) << 0)
/* MIPI_DPHY_LANE_CTRL 0x0124 */
#define SRST_OFFSET 0
#define SRST_BITS 1
#define SRST_MASK (((1 << 1) - 1) << 0)
#define TRANS_MODE_SEL_OFFSET 4
#define TRANS_MODE_SEL_BITS 1
#define TRANS_MODE_SEL_MASK (((1 << 1) - 1) << 4)
/* MIPI_DPHY_CFG0 0x0128 */
#define CLK_LANE_EN_OFFSET 0
#define CLK_LANE_EN_BITS 1
#define CLK_LANE_EN_MASK (((1 << 1) - 1) << 0)
#define ECC_EN_OFFSET 1
#define ECC_EN_BITS 1
#define ECC_EN_MASK (((1 << 1) - 1) << 1)
#define CRC16_EN_OFFSET 2
#define CRC16_EN_BITS 1
#define CRC16_EN_MASK (((1 << 1) - 1) << 2)
#define BIT_SWP_OFFSET 3
#define BIT_SWP_BITS 1
#define BIT_SWP_MASK (((1 << 1) - 1) << 3)
#define PIX_DIN_MIPI_SEL_OFFSET 4
#define PIX_DIN_MIPI_SEL_BITS 1
#define PIX_DIN_MIPI_SEL_MASK (((1 << 1) - 1) << 4)
/* MIPI_DPHY_HSTERM0 0x012C */
#define HL_INTERVAL_0_OFFSET 0
#define HL_INTERVAL_0_BITS 4
#define HL_INTERVAL_0_MASK (((1 << 4) - 1) << 0)
#define HL_INTERVAL_1_OFFSET 4
#define HL_INTERVAL_1_BITS 4
#define HL_INTERVAL_1_MASK (((1 << 4) - 1) << 4)
/* MIPI_DPHY_HSTERM1 0x0130 */
#define HL_INTERVAL_2_OFFSET 0
#define HL_INTERVAL_2_BITS 4
#define HL_INTERVAL_2_MASK (((1 << 4) - 1) << 0)
#define HL_INTERVAL_3_OFFSET 4
#define HL_INTERVAL_3_BITS 4
#define HL_INTERVAL_3_MASK (((1 << 4) - 1) << 4)
/* MIPI_DPHY_LANE_SEL 0x0134 */
#define LANE0_SEL_OFFSET 0
#define LANE0_SEL_BITS 2
#define LANE0_SEL_MASK (((1 << 2) - 1) << 0)
#define LANE1_SEL_OFFSET 2
#define LANE1_SEL_BITS 2
#define LANE1_SEL_MASK (((1 << 2) - 1) << 2)
#define LANE2_SEL_OFFSET 4
#define LANE2_SEL_BITS 2
#define LANE2_SEL_MASK (((1 << 2) - 1) << 4)
#define LANE3_SEL_OFFSET 6
#define LANE3_SEL_BITS 2
#define LANE3_SEL_MASK (((1 << 2) - 1) << 6)
/* MIPI_DPHY_HSCLK_SEL 0x0138 */
#define HSCLK_SEL_LANE0_OFFSET 0
#define HSCLK_SEL_LANE0_BITS 1
#define HSCLK_SEL_LANE0_MASK (((1 << 1) - 1) << 0)
#define HSCLK_SEL_LANE1_OFFSET 1
#define HSCLK_SEL_LANE1_BITS 1
#define HSCLK_SEL_LANE1_MASK (((1 << 1) - 1) << 1)
#define HSCLK_SEL_LANE2_OFFSET 2
#define HSCLK_SEL_LANE2_BITS 1
#define HSCLK_SEL_LANE2_MASK (((1 << 1) - 1) << 2)
#define HSCLK_SEL_LANE3_OFFSET 3
#define HSCLK_SEL_LANE3_BITS 1
#define HSCLK_SEL_LANE3_MASK (((1 << 1) - 1) << 3)
/* MIPI_DPHY_INTP_EN 0x013C */
#define ECC_ERR_INTEN_OFFSET 0
#define ECC_ERR_INTEN_BITS 1
#define ECC_ERR_INTEN_MASK (((1 << 1) - 1) << 0)
#define ECC_COR_INTEN_OFFSET 1
#define ECC_COR_INTEN_BITS 1
#define ECC_COR_INTEN_MASK (((1 << 1) - 1) << 1)
#define CRC16_ERR_INTEN_OFFSET 2
#define CRC16_ERR_INTEN_BITS 1
#define CRC16_ERR_INTEN_MASK (((1 << 1) - 1) << 2)
#define CLK_ULPS_INTEN_OFFSET 3
#define CLK_ULPS_INTEN_BITS 1
#define CLK_ULPS_INTEN_MASK (((1 << 1) - 1) << 3)
#define ESC_CMD_LANE0_INTEN_OFFSET 4
#define ESC_CMD_LANE0_INTEN_BITS 1
#define ESC_CMD_LANE0_INTEN_MASK (((1 << 1) - 1) << 4)
#define ESC_CMD_LANE1_INTEN_OFFSET 5
#define ESC_CMD_LANE1_INTEN_BITS 1
#define ESC_CMD_LANE1_INTEN_MASK (((1 << 1) - 1) << 5)
#define ESC_CMD_LANE2_INTEN_OFFSET 6
#define ESC_CMD_LANE2_INTEN_BITS 1
#define ESC_CMD_LANE2_INTEN_MASK (((1 << 1) - 1) << 6)
#define ESC_CMD_LANE3_INTEN_OFFSET 7
#define ESC_CMD_LANE3_INTEN_BITS 1
#define ESC_CMD_LANE3_INTEN_MASK (((1 << 1) - 1) << 7)
/* MIPI_DPHY_INTP_FLAG 0x0140 */
#define ECC_ERR_ST_OFFSET 0
#define ECC_ERR_ST_BITS 1
#define ECC_ERR_ST_MASK (((1 << 1) - 1) << 0)
#define ECC_COR_ST_OFFSET 1
#define ECC_COR_ST_BITS 1
#define ECC_COR_ST_MASK (((1 << 1) - 1) << 1)
#define CRC16_ERR_ST_OFFSET 2
#define CRC16_ERR_ST_BITS 1
#define CRC16_ERR_ST_MASK (((1 << 1) - 1) << 2)
#define CLK_ULPS_INT_N_OFFSET 3
#define CLK_ULPS_INT_N_BITS 1
#define CLK_ULPS_INT_N_MASK (((1 << 1) - 1) << 3)
#define ESC_CMD_LANE0_ST_OFFSET 4
#define ESC_CMD_LANE0_ST_BITS 1
#define ESC_CMD_LANE0_ST_MASK (((1 << 1) - 1) << 4)
#define ESC_CMD_LANE1_ST_OFFSET 5
#define ESC_CMD_LANE1_ST_BITS 1
#define ESC_CMD_LANE1_ST_MASK (((1 << 1) - 1) << 5)
#define ESC_CMD_LANE2_ST_OFFSET 6
#define ESC_CMD_LANE2_ST_BITS 1
#define ESC_CMD_LANE2_ST_MASK (((1 << 1) - 1) << 6)
#define ESC_CMD_LANE3_ST_OFFSET 7
#define ESC_CMD_LANE3_ST_BITS 1
#define ESC_CMD_LANE3_ST_MASK (((1 << 1) - 1) << 7)
/* MIPI_DPHY_ECC_CNT_L 0x0144 */
#define ECC_CNT_OFFSET 0
#define ECC_CNT_BITS 16
#define ECC_CNT_MASK (((1 << 16) - 1) << 0)
/* MIPI_DPHY_CHECK 0x0148 */
#define ECC_ERR_OFFSET 0
#define ECC_ERR_BITS 4
#define ECC_ERR_MASK (((1 << 4) - 1) << 0)
#define ECC_COR_OFFSET 8
#define ECC_COR_BITS 4
#define ECC_COR_MASK (((1 << 4) - 1) << 8)
#define CRC16_ERR_OFFSET 16
#define CRC16_ERR_BITS 4
#define CRC16_ERR_MASK (((1 << 4) - 1) << 16)
/* MIPI_DPHY_CRC_CNT_L 0x014C */
#define CRC_CNT_OFFSET 0
#define CRC_CNT_BITS 16
#define CRC_CNT_MASK (((1 << 16) - 1) << 0)
/* MIPI_DPHY_FRM_SIZE 0x0150 */
#define FRAME_WIDTH_OFFSET 0
#define FRAME_WIDTH_BITS 13
#define FRAME_WIDTH_MASK (((1 << 13) - 1) << 0)
#define FRAME_HEIGHT_OFFSET 16
#define FRAME_HEIGHT_BITS 12
#define FRAME_HEIGHT_MASK (((1 << 12) - 1) << 16)
/* MIPI_DPHY_TERM_CFG 0x0154 */
#define LANE0_TERM_EN_CFG_OFFSET 0
#define LANE0_TERM_EN_CFG_BITS 1
#define LANE0_TERM_EN_CFG_MASK (((1 << 1) - 1) << 0)
#define LANE1_TERM_EN_CFG_OFFSET 1
#define LANE1_TERM_EN_CFG_BITS 1
#define LANE1_TERM_EN_CFG_MASK (((1 << 1) - 1) << 1)
#define LANE2_TERM_EN_CFG_OFFSET 2
#define LANE2_TERM_EN_CFG_BITS 1
#define LANE2_TERM_EN_CFG_MASK (((1 << 1) - 1) << 2)
#define LANE3_TERM_EN_CFG_OFFSET 3
#define LANE3_TERM_EN_CFG_BITS 1
#define LANE3_TERM_EN_CFG_MASK (((1 << 1) - 1) << 3)
#define CLK_TERM_EN_CFG_OFFSET 4
#define CLK_TERM_EN_CFG_BITS 1
#define CLK_TERM_EN_CFG_MASK (((1 << 1) - 1) << 4)
/* MIPI_DPHY_DIVSEL 0x0158 */
#define DIV_SEL_OFFSET 0
#define DIV_SEL_BITS 2
#define DIV_SEL_MASK (((1 << 2) - 1) << 0)
#define DRST_SEL_OFFSET 2
#define DRST_SEL_BITS 1
#define DRST_SEL_MASK (((1 << 1) - 1) << 2)
/* MIPI_DPHY_WKUP_H 0x015C */
#define WAKEUP_TM_OFFSET 0
#define WAKEUP_TM_BITS 12
#define WAKEUP_TM_MASK (((1 << 12) - 1) << 0)
/* MIPI_DPHY_DBG_MODE 0x0160 */
#define MIPI_DBG_SEL_OFFSET 0
#define MIPI_DBG_SEL_BITS 4
#define MIPI_DBG_SEL_MASK (((1 << 4) - 1) << 0)
#define MIPI_DBG_MODE_OFFSET 7
#define MIPI_DBG_MODE_BITS 1
#define MIPI_DBG_MODE_MASK (((1 << 1) - 1) << 7)
/* MIPI_DPHY_ESCAPE0 0x0164 */
#define ESC_CMD_0_REG_OFFSET 0
#define ESC_CMD_0_REG_BITS 8
#define ESC_CMD_0_REG_MASK (((1 << 8) - 1) << 0)
/* MIPI_DPHY_ESCAPE1 0x0168 */
#define ESC_CMD_1_REG_OFFSET 0
#define ESC_CMD_1_REG_BITS 8
#define ESC_CMD_1_REG_MASK (((1 << 8) - 1) << 0)
/* MIPI_DUMMY_REG0 0x016C */
#define MIPI_DUMMY0_OFFSET 0
#define MIPI_DUMMY0_BITS 8
#define MIPI_DUMMY0_MASK (((1 << 8) - 1) << 0)
/* MIPI_DUMMY_REG1 0x0170 */
#define MIPI_DUMMY1_OFFSET 0
#define MIPI_DUMMY1_BITS 8
#define MIPI_DUMMY1_MASK (((1 << 8) - 1) << 0)
/* MIPI_DUMMY_REG2 0x0174 */
#define MIPI_DUMMY2_OFFSET 0
#define MIPI_DUMMY2_BITS 8
#define MIPI_DUMMY2_MASK (((1 << 8) - 1) << 0)
/* MIPI_DPHY_HS_TERM_BITS_EN 0x0178 */
#define LANE0_DROP_BITS_EN_OFFSET 0
#define LANE0_DROP_BITS_EN_BITS 1
#define LANE0_DROP_BITS_EN_MASK (((1 << 1) - 1) << 0)
#define LANE1_DROP_BITS_EN_OFFSET 1
#define LANE1_DROP_BITS_EN_BITS 1
#define LANE1_DROP_BITS_EN_MASK (((1 << 1) - 1) << 1)
#define LANE2_DROP_BITS_EN_OFFSET 2
#define LANE2_DROP_BITS_EN_BITS 1
#define LANE2_DROP_BITS_EN_MASK (((1 << 1) - 1) << 2)
#define LANE3_DROP_BITS_EN_OFFSET 3
#define LANE3_DROP_BITS_EN_BITS 1
#define LANE3_DROP_BITS_EN_MASK (((1 << 1) - 1) << 3)
/* MIPI_DPHY_HS_TERM_BITS_LANE0 0x017C */
#define LANE0_DROP_BITS_SEL_OFFSET 0
#define LANE0_DROP_BITS_SEL_BITS 16
#define LANE0_DROP_BITS_SEL_MASK (((1 << 16) - 1) << 0)
/* MIPI_DPHY_HS_TERM_BITS_LANE1 0x0180 */
#define LANE1_DROP_BITS_SEL_OFFSET 0
#define LANE1_DROP_BITS_SEL_BITS 16
#define LANE1_DROP_BITS_SEL_MASK (((1 << 16) - 1) << 0)
/* MIPI_DPHY_HS_TERM_BITS_LANE2 0x0184 */
#define LANE2_DROP_BITS_SEL_OFFSET 0
#define LANE2_DROP_BITS_SEL_BITS 16
#define LANE2_DROP_BITS_SEL_MASK (((1 << 16) - 1) << 0)
/* MIPI_DPHY_HS_TERM_BITS_LANE3 0x0188 */
#define LANE3_DROP_BITS_SEL_OFFSET 0
#define LANE3_DROP_BITS_SEL_BITS 16
#define LANE3_DROP_BITS_SEL_MASK (((1 << 16) - 1) << 0)
/* MIPI_DPHY_DIV16CNT_RST_TERM_SEL 0x018C */
#define LANE0_DIV16CNT_RST_TERM_SEL_OFFSET 0
#define LANE0_DIV16CNT_RST_TERM_SEL_BITS 1
#define LANE0_DIV16CNT_RST_TERM_SEL_MASK (((1 << 1) - 1) << 0)
#define LANE1_DIV16CNT_RST_TERM_SEL_OFFSET 1
#define LANE1_DIV16CNT_RST_TERM_SEL_BITS 1
#define LANE1_DIV16CNT_RST_TERM_SEL_MASK (((1 << 1) - 1) << 1)
#define LANE2_DIV16CNT_RST_TERM_SEL_OFFSET 2
#define LANE2_DIV16CNT_RST_TERM_SEL_BITS 1
#define LANE2_DIV16CNT_RST_TERM_SEL_MASK (((1 << 1) - 1) << 2)
#define LANE3_DIV16CNT_RST_TERM_SEL_OFFSET 3
#define LANE3_DIV16CNT_RST_TERM_SEL_BITS 1
#define LANE3_DIV16CNT_RST_TERM_SEL_MASK (((1 << 1) - 1) << 3)
/* MIPI_DPHY_DIV16CNT_RST_SEL 0x0190 */
#define LANE0_DIV16CNT_RST_SEL_OFFSET 0
#define LANE0_DIV16CNT_RST_SEL_BITS 2
#define LANE0_DIV16CNT_RST_SEL_MASK (((1 << 2) - 1) << 0)
#define LANE1_DIV16CNT_RST_SEL_OFFSET 2
#define LANE1_DIV16CNT_RST_SEL_BITS 2
#define LANE1_DIV16CNT_RST_SEL_MASK (((1 << 2) - 1) << 2)
#define LANE2_DIV16CNT_RST_SEL_OFFSET 4
#define LANE2_DIV16CNT_RST_SEL_BITS 2
#define LANE2_DIV16CNT_RST_SEL_MASK (((1 << 2) - 1) << 4)
#define LANE3_DIV16CNT_RST_SEL_OFFSET 6
#define LANE3_DIV16CNT_RST_SEL_BITS 2
#define LANE3_DIV16CNT_RST_SEL_MASK (((1 << 2) - 1) << 6)
/* MIPI_DPHY_MERGE_OVERFLOW_CNT 0x0194 */
#define MERGE_OVFL_CNT_OFFSET 0
#define MERGE_OVFL_CNT_BITS 8
#define MERGE_OVFL_CNT_MASK (((1 << 8) - 1) << 0)
/* MIPI_DPHY_FRAME_CNT 0x0198 */
#define FRAME_CNT_CH0_OFFSET 0
#define FRAME_CNT_CH0_BITS 8
#define FRAME_CNT_CH0_MASK (((1 << 8) - 1) << 0)
#define FRAME_CNT_CH1_OFFSET 8
#define FRAME_CNT_CH1_BITS 8
#define FRAME_CNT_CH1_MASK (((1 << 8) - 1) << 8)
/* MIPI_DPHY_LINE_CNT 0x019C */
#define LINE_CNT_CH0_OFFSET 0
#define LINE_CNT_CH0_BITS 12
#define LINE_CNT_CH0_MASK (((1 << 12) - 1) << 0)
#define LINE_CNT_CH1_OFFSET 16
#define LINE_CNT_CH1_BITS 12
#define LINE_CNT_CH1_MASK (((1 << 12) - 1) << 16)
/* MIPI_DPHY_PIX_CNT 0x01A0 */
#define PIX_CNT_CH0_OFFSET 0
#define PIX_CNT_CH0_BITS 12
#define PIX_CNT_CH0_MASK (((1 << 12) - 1) << 0)
#define PIX_CNT_CH1_OFFSET 16
#define PIX_CNT_CH1_BITS 12
#define PIX_CNT_CH1_MASK (((1 << 12) - 1) << 16)
/* MIPI_DPHY_FRAME_HEIGHT 0x01A4 */
#define FRAME_HEIGHT_CH0_OFFSET 0
#define FRAME_HEIGHT_CH0_BITS 12
#define FRAME_HEIGHT_CH0_MASK (((1 << 12) - 1) << 0)
#define FRAME_HEIGHT_CH1_OFFSET 16
#define FRAME_HEIGHT_CH1_BITS 12
#define FRAME_HEIGHT_CH1_MASK (((1 << 12) - 1) << 16)
/* MIPI_DPHY_FRAME_WIDTH 0x01A8 */
#define FRAME_WIDTH_CH0_OFFSET 0
#define FRAME_WIDTH_CH0_BITS 12
#define FRAME_WIDTH_CH0_MASK (((1 << 12) - 1) << 0)
#define FRAME_WIDTH_CH1_OFFSET 16
#define FRAME_WIDTH_CH1_BITS 12
#define FRAME_WIDTH_CH1_MASK (((1 << 12) - 1) << 16)
/* MIPI_DPHY_STACNT_EN 0x01AC */
#define STACNT_EN_OFFSET 0
#define STACNT_EN_BITS 1
#define STACNT_EN_MASK (((1 << 1) - 1) << 0)
/* MIPI_DPHY_INPUT_MODE 0x01B0 */
#define MIPI_IN_MODE_OFFSET 0
#define MIPI_IN_MODE_BITS 2
#define MIPI_IN_MODE_MASK (((1 << 2) - 1) << 0)
/* MIPI_DPHY_MAX_SRT_EXP 0x01B4 */
#define MAX_SRT_EXP_OFFSET 0
#define MAX_SRT_EXP_BITS 12
#define MAX_SRT_EXP_MASK (((1 << 12) - 1) << 0)
/* MIPI_DPHY_FID 0x01B8 */
#define FID_CH0_OFFSET 0
#define FID_CH0_BITS 3
#define FID_CH0_MASK (((1 << 3) - 1) << 0)
#define FID_CH1_OFFSET 8
#define FID_CH1_BITS 3
#define FID_CH1_MASK (((1 << 3) - 1) << 8)

#endif /* _ISP_REG_MIPIIN_H_INC_ */

