#ifndef _ISP_REG_INTP_H_INC_
#define _ISP_REG_INTP_H_INC_

#include <isp_reg.h>
#include <isp_reg_base.h>

#define INTP_BLOCK_EN (INTP_REG_BASE + 0x0000)
#define INTP_EDGE_PARAM0 (INTP_REG_BASE + 0x0004)
#define INTP_EDGE_PARAM1 (INTP_REG_BASE + 0x0008)
#define INTP_EDGE_PARAM2 (INTP_REG_BASE + 0x000C)
#define INTP_EDGE_PARAM3 (INTP_REG_BASE + 0x0010)
#define INTP_EDGE_PARAM4 (INTP_REG_BASE + 0x0014)
#define INTP_EDGE_PARAM5 (INTP_REG_BASE + 0x0018)
#define INTP_EDGE_PARAM6 (INTP_REG_BASE + 0x001C)
#define INTP_W_PARAM (INTP_REG_BASE + 0x0020)
#define INTP_EDGE_THD (INTP_REG_BASE + 0x0024)
#define INTP_EDGE_THD_SEL (INTP_REG_BASE + 0x0028)
#define INTP_RGB_FALSE (INTP_REG_BASE + 0x002C)
#define INTP_THIN_THD (INTP_REG_BASE + 0x0030)
#define INTP_MOIRE_RGB (INTP_REG_BASE + 0x0034)
#define INTP_MOIRE_THRESHOLD (INTP_REG_BASE + 0x0038)
#define INTP_MOIRE_NUM_R (INTP_REG_BASE + 0x003C)
#define INTP_MOIRE_NUM_G (INTP_REG_BASE + 0x0040)
#define INTP_MOIRE_NUM_B (INTP_REG_BASE + 0x0044)
#define INTP_MOIRE_SUM_R (INTP_REG_BASE + 0x0048)
#define INTP_MOIRE_SUM_G (INTP_REG_BASE + 0x004C)
#define INTP_MOIRE_SUM_B (INTP_REG_BASE + 0x0050)
#define INTP_EDGE_SMOOTH_ILOC (INTP_REG_BASE + 0x0054)
#define INTP_EDGE_SMOOTH_ILOC_MAX (INTP_REG_BASE + 0x0058)
#define INTP_LPF_RGB_BLEND (INTP_REG_BASE + 0x005C)
#define INTP_SYNC (INTP_REG_BASE + 0x0060)
#define INTP_EDGE_RATE_THD0 (INTP_REG_BASE + 0x0064)
#define INTP_EDGE_RATE_THD1 (INTP_REG_BASE + 0x0068)
#define INTP_EDGE_SLOPE (INTP_REG_BASE + 0x006C)
#define INTP_SHARPEN_RATIO (INTP_REG_BASE + 0x0070)
#define INTP_SHARPEN (INTP_REG_BASE + 0x0074)
#define DRC_CTRL (INTP_REG_BASE + 0x0078)
#define DRC_FEATURE_MAP1 (INTP_REG_BASE + 0x007C)
#define DRC_FEATURE_MAP2 (INTP_REG_BASE + 0x0080)
#define DRC_FEATURE_MAP3 (INTP_REG_BASE + 0x0084)
#define DRC_FEATURE_MAP4 (INTP_REG_BASE + 0x0088)
#define DRC_FEATURE_MAP5 (INTP_REG_BASE + 0x008C)
#define DRC_FEATURE_MAP6 (INTP_REG_BASE + 0x0090)
#define DRC_FEATURE_MAP7 (INTP_REG_BASE + 0x0094)
#define DRC_FEATURE_MAP8 (INTP_REG_BASE + 0x0098)
#define DRC_CC_BC_RATE (INTP_REG_BASE + 0x009C)
#define DRC_ORG_BLENDING_VALUE0 (INTP_REG_BASE + 0x00A0)
#define DRC_ORG_BLENDING_VALUE1 (INTP_REG_BASE + 0x00A4)
#define DRC_DARK_REGION_ENHANCEMENT0 (INTP_REG_BASE + 0x00A8)
#define DRC_DARK_REGION_ENHANCEMENT1 (INTP_REG_BASE + 0x00AC)
#define DRC_DARK_REGION_ENHANCEMENT2 (INTP_REG_BASE + 0x00B0)
#define DRC_LOCAL_DIFF (INTP_REG_BASE + 0x00B4)
#define DRC_DYNAMIC_RANGE (INTP_REG_BASE + 0x00B8)
#define DRC_LOCAL_CONTRAST0 (INTP_REG_BASE + 0x00BC)
#define DRC_LOCAL_CONTRAST1 (INTP_REG_BASE + 0x00C0)
#define DRC_HF_ADDITION_GRADIENT0 (INTP_REG_BASE + 0x00C4)
#define DRC_HF_ADDITION_GRADIENT1 (INTP_REG_BASE + 0x00C8)
#define DRC_BFILTER_WIN (INTP_REG_BASE + 0x00CC)
#define DRC_FRAME_SIZE (INTP_REG_BASE + 0x00D0)
#define DRC_DEALY_NUM (INTP_REG_BASE + 0x00D4)
#define DRC_DRC_SAT_THD (INTP_REG_BASE + 0x00D8)
#define DRC_DRC_UPDATE (INTP_REG_BASE + 0x00DC)
#define DRC_RATIO_CP (INTP_REG_BASE + 0x00E0)
#define DRC_RATIO_BP (INTP_REG_BASE + 0x00E4)
#define DRC_VAR (INTP_REG_BASE + 0x0108)

/* INTP_BLOCK_EN 0x0000 */
#define INTP_SMOOTH_AREA_DCT_PRI_EN_OFFSET 0
#define INTP_SMOOTH_AREA_DCT_PRI_EN_BITS 1
#define INTP_SMOOTH_AREA_DCT_PRI_EN_MASK (((1 << 1) - 1) << 0)
#define ALPHA_BLENDING_SHOW_EN_OFFSET 1
#define ALPHA_BLENDING_SHOW_EN_BITS 1
#define ALPHA_BLENDING_SHOW_EN_MASK (((1 << 1) - 1) << 1)
#define SMOOTH_AREA_LP_EN_OFFSET 2
#define SMOOTH_AREA_LP_EN_BITS 1
#define SMOOTH_AREA_LP_EN_MASK (((1 << 1) - 1) << 2)
#define LOC_EN_OFFSET 3
#define LOC_EN_BITS 1
#define LOC_EN_MASK (((1 << 1) - 1) << 3)
#define EDGE_DIR_SHOW_EN_OFFSET 4
#define EDGE_DIR_SHOW_EN_BITS 1
#define EDGE_DIR_SHOW_EN_MASK (((1 << 1) - 1) << 4)
#define MOIRE_EN_OFFSET 5
#define MOIRE_EN_BITS 1
#define MOIRE_EN_MASK (((1 << 1) - 1) << 5)
#define INTP_BLEND_EN_OFFSET 6
#define INTP_BLEND_EN_BITS 1
#define INTP_BLEND_EN_MASK (((1 << 1) - 1) << 6)
#define FILTER_LOG_MODE_EN_OFFSET 7
#define FILTER_LOG_MODE_EN_BITS 1
#define FILTER_LOG_MODE_EN_MASK (((1 << 1) - 1) << 7)
#define INTP_THD_ADJUSTMENT_EN_OFFSET 8
#define INTP_THD_ADJUSTMENT_EN_BITS 1
#define INTP_THD_ADJUSTMENT_EN_MASK (((1 << 1) - 1) << 8)
/* INTP_EDGE_PARAM0 0x0004 */
#define INTP_EDGE_DETECT_B1_OFFSET 0
#define INTP_EDGE_DETECT_B1_BITS 4
#define INTP_EDGE_DETECT_B1_MASK (((1 << 4) - 1) << 0)
/* INTP_EDGE_PARAM1 0x0008 */
#define INTP_EDGE_DETECT_K1_OFFSET 0
#define INTP_EDGE_DETECT_K1_BITS 5
#define INTP_EDGE_DETECT_K1_MASK (((1 << 5) - 1) << 0)
/* INTP_EDGE_PARAM2 0x000C */
#define INTP_EDGE_DETECT_B2_OFFSET 0
#define INTP_EDGE_DETECT_B2_BITS 4
#define INTP_EDGE_DETECT_B2_MASK (((1 << 4) - 1) << 0)
/* INTP_EDGE_PARAM3 0x0010 */
#define INTP_EDGE_DETECT_K2_OFFSET 0
#define INTP_EDGE_DETECT_K2_BITS 5
#define INTP_EDGE_DETECT_K2_MASK (((1 << 5) - 1) << 0)
/* INTP_EDGE_PARAM4 0x0014 */
#define INTP_EDGE_DETECT_K3_OFFSET 0
#define INTP_EDGE_DETECT_K3_BITS 5
#define INTP_EDGE_DETECT_K3_MASK (((1 << 5) - 1) << 0)
/* INTP_EDGE_PARAM5 0x0018 */
#define INTP_EDGE_DETECT_K4_OFFSET 0
#define INTP_EDGE_DETECT_K4_BITS 5
#define INTP_EDGE_DETECT_K4_MASK (((1 << 5) - 1) << 0)
/* INTP_EDGE_PARAM6 0x001C */
#define INTP_EDGE_DETECT_K5_OFFSET 0
#define INTP_EDGE_DETECT_K5_BITS 5
#define INTP_EDGE_DETECT_K5_MASK (((1 << 5) - 1) << 0)
/* INTP_W_PARAM 0x0020 */
#define INTP_W1_OFFSET 0
#define INTP_W1_BITS 6
#define INTP_W1_MASK (((1 << 6) - 1) << 0)
#define INTP_W2_OFFSET 8
#define INTP_W2_BITS 6
#define INTP_W2_MASK (((1 << 6) - 1) << 8)
#define INTP_W3_OFFSET 16
#define INTP_W3_BITS 6
#define INTP_W3_MASK (((1 << 6) - 1) << 16)
/* INTP_EDGE_THD 0x0024 */
#define INTP_EDGE_THD_OFFSET 0
#define INTP_EDGE_THD_BITS 7
#define INTP_EDGE_THD_MASK (((1 << 7) - 1) << 0)
/* INTP_EDGE_THD_SEL 0x0028 */
#define INTP_DARK_ADJUSTMENT_SELECT_OFFSET 0
#define INTP_DARK_ADJUSTMENT_SELECT_BITS 2
#define INTP_DARK_ADJUSTMENT_SELECT_MASK (((1 << 2) - 1) << 0)
#define INTP_BRIGHT_ADJUSTMENT_SELECT_OFFSET 2
#define INTP_BRIGHT_ADJUSTMENT_SELECT_BITS 2
#define INTP_BRIGHT_ADJUSTMENT_SELECT_MASK (((1 << 2) - 1) << 2)
/* INTP_RGB_FALSE 0x002C */
#define FCRD_SM_OFFSET 0
#define FCRD_SM_BITS 7
#define FCRD_SM_MASK (((1 << 7) - 1) << 0)
#define FCRD_MAX_OFFSET 8
#define FCRD_MAX_BITS 7
#define FCRD_MAX_MASK (((1 << 7) - 1) << 8)
/* INTP_THIN_THD 0x0030 */
#define INTP_GRGB_DIFF_THD_OFFSET 0
#define INTP_GRGB_DIFF_THD_BITS 6
#define INTP_GRGB_DIFF_THD_MASK (((1 << 6) - 1) << 0)
/* INTP_MOIRE_RGB 0x0034 */
#define MOIRE_G_AFFECT_RB_OFFSET 0
#define MOIRE_G_AFFECT_RB_BITS 6
#define MOIRE_G_AFFECT_RB_MASK (((1 << 6) - 1) << 0)
#define MOIRE_B_RATE_OFFSET 8
#define MOIRE_B_RATE_BITS 8
#define MOIRE_B_RATE_MASK (((1 << 8) - 1) << 8)
#define MOIRE_R_RATE_OFFSET 16
#define MOIRE_R_RATE_BITS 8
#define MOIRE_R_RATE_MASK (((1 << 8) - 1) << 16)
/* INTP_MOIRE_THRESHOLD 0x0038 */
#define MOIRE_MAX_OFFSET 0
#define MOIRE_MAX_BITS 7
#define MOIRE_MAX_MASK (((1 << 7) - 1) << 0)
#define MOIRE_THD_OFFSET 8
#define MOIRE_THD_BITS 5
#define MOIRE_THD_MASK (((1 << 5) - 1) << 8)
/* INTP_MOIRE_NUM_R 0x003C */
#define MOIRE_NUM_R_SYNC_OFFSET 0
#define MOIRE_NUM_R_SYNC_BITS 22
#define MOIRE_NUM_R_SYNC_MASK (((1 << 22) - 1) << 0)
/* INTP_MOIRE_NUM_G 0x0040 */
#define MOIRE_NUM_G_SYNC_OFFSET 0
#define MOIRE_NUM_G_SYNC_BITS 22
#define MOIRE_NUM_G_SYNC_MASK (((1 << 22) - 1) << 0)
/* INTP_MOIRE_NUM_B 0x0044 */
#define MOIRE_NUM_B_SYNC_OFFSET 0
#define MOIRE_NUM_B_SYNC_BITS 22
#define MOIRE_NUM_B_SYNC_MASK (((1 << 22) - 1) << 0)
/* INTP_MOIRE_SUM_R 0x0048 */
/* INTP_MOIRE_SUM_G 0x004C */
/* INTP_MOIRE_SUM_B 0x0050 */
/* INTP_EDGE_SMOOTH_ILOC 0x0054 */
#define INTP_SMOOTH_RATE_OFFSET 0
#define INTP_SMOOTH_RATE_BITS 4
#define INTP_SMOOTH_RATE_MASK (((1 << 4) - 1) << 0)
#define LOC_RATE_OFFSET 16
#define LOC_RATE_BITS 14
#define LOC_RATE_MASK (((1 << 14) - 1) << 16)
/* INTP_EDGE_SMOOTH_ILOC_MAX 0x0058 */
#define LOC_MAX_OFFSET 0
#define LOC_MAX_BITS 6
#define LOC_MAX_MASK (((1 << 6) - 1) << 0)
/* INTP_LPF_RGB_BLEND 0x005C */
#define INTP_EDGE_THD_OFFSET_OFFSET 0
#define INTP_EDGE_THD_OFFSET_BITS 3
#define INTP_EDGE_THD_OFFSET_MASK (((1 << 3) - 1) << 0)
/* INTP_SYNC 0x0060 */
#define INTP_REG_LOAD_OFFSET 0
#define INTP_REG_LOAD_BITS 1
#define INTP_REG_LOAD_MASK (((1 << 1) - 1) << 0)
/* INTP_EDGE_RATE_THD0 0x0064 */
#define EDGE_THD0_PTS_OFFSET 0
#define EDGE_THD0_PTS_BITS 17
#define EDGE_THD0_PTS_MASK (((1 << 17) - 1) << 0)
/* INTP_EDGE_RATE_THD1 0x0068 */
#define EDGE_THD1_PTS_OFFSET 0
#define EDGE_THD1_PTS_BITS 17
#define EDGE_THD1_PTS_MASK (((1 << 17) - 1) << 0)
/* INTP_EDGE_SLOPE 0x006C */
#define EDGE_SLOPE_OFFSET 0
#define EDGE_SLOPE_BITS 22
#define EDGE_SLOPE_MASK (((1 << 22) - 1) << 0)
/* INTP_SHARPEN_RATIO 0x0070 */
#define ENHANCE_RATIO_OFFSET 0
#define ENHANCE_RATIO_BITS 4
#define ENHANCE_RATIO_MASK (((1 << 4) - 1) << 0)
/* INTP_SHARPEN 0x0074 */
#define SHARP_RATE_OFFSET 0
#define SHARP_RATE_BITS 8
#define SHARP_RATE_MASK (((1 << 8) - 1) << 0)
#define SHARP_THD1_OFFSET 8
#define SHARP_THD1_BITS 8
#define SHARP_THD1_MASK (((1 << 8) - 1) << 8)
#define SHARP_THD2_OFFSET 16
#define SHARP_THD2_BITS 8
#define SHARP_THD2_MASK (((1 << 8) - 1) << 16)
/* DRC_CTRL 0x0078 */
#define DRC_DYNAMIC_REFRESH_POS_OFFSET 0
#define DRC_DYNAMIC_REFRESH_POS_BITS 1
#define DRC_DYNAMIC_REFRESH_POS_MASK (((1 << 1) - 1) << 0)
#define DRC_EN_OFFSET 1
#define DRC_EN_BITS 1
#define DRC_EN_MASK (((1 << 1) - 1) << 1)
#define HF_ADDITION_MECHANISM_EN_OFFSET 2
#define HF_ADDITION_MECHANISM_EN_BITS 1
#define HF_ADDITION_MECHANISM_EN_MASK (((1 << 1) - 1) << 2)
#define DYNAMIC_RANGE_AUTO_EN_OFFSET 3
#define DYNAMIC_RANGE_AUTO_EN_BITS 1
#define DYNAMIC_RANGE_AUTO_EN_MASK (((1 << 1) - 1) << 3)
#define DRE_EN_OFFSET 4
#define DRE_EN_BITS 1
#define DRE_EN_MASK (((1 << 1) - 1) << 4)
#define DRC_ORG_BLENDING_MANUAL_EN_OFFSET 5
#define DRC_ORG_BLENDING_MANUAL_EN_BITS 1
#define DRC_ORG_BLENDING_MANUAL_EN_MASK (((1 << 1) - 1) << 5)
#define DRC_ORG_BLENDING_EN_OFFSET 6
#define DRC_ORG_BLENDING_EN_BITS 1
#define DRC_ORG_BLENDING_EN_MASK (((1 << 1) - 1) << 6)
#define CC_BC_BLENDING_MANUAL_EN_OFFSET 7
#define CC_BC_BLENDING_MANUAL_EN_BITS 1
#define CC_BC_BLENDING_MANUAL_EN_MASK (((1 << 1) - 1) << 7)
#define BC_EN_OFFSET 8
#define BC_EN_BITS 1
#define BC_EN_MASK (((1 << 1) - 1) << 8)
#define CC_EN_OFFSET 9
#define CC_EN_BITS 1
#define CC_EN_MASK (((1 << 1) - 1) << 9)
#define DECOMPOSITION_EN_OFFSET 10
#define DECOMPOSITION_EN_BITS 1
#define DECOMPOSITION_EN_MASK (((1 << 1) - 1) << 10)
#define FILTER_MODE_OFFSET 11
#define FILTER_MODE_BITS 1
#define FILTER_MODE_MASK (((1 << 1) - 1) << 11)
#define L_VARIANCE_DEBUG_EN_OFFSET 12
#define L_VARIANCE_DEBUG_EN_BITS 1
#define L_VARIANCE_DEBUG_EN_MASK (((1 << 1) - 1) << 12)
#define EDGE_MAP_DEBUG_EN_OFFSET 13
#define EDGE_MAP_DEBUG_EN_BITS 1
#define EDGE_MAP_DEBUG_EN_MASK (((1 << 1) - 1) << 13)
#define G_SMOOTH_DEBUG_EN_OFFSET 14
#define G_SMOOTH_DEBUG_EN_BITS 1
#define G_SMOOTH_DEBUG_EN_MASK (((1 << 1) - 1) << 14)
#define DRC_UPDATE_EN_OFFSET 15
#define DRC_UPDATE_EN_BITS 1
#define DRC_UPDATE_EN_MASK (((1 << 1) - 1) << 15)
#define DRC_KEEP_EN_OFFSET 16
#define DRC_KEEP_EN_BITS 1
#define DRC_KEEP_EN_MASK (((1 << 1) - 1) << 16)
/* DRC_FEATURE_MAP1 0x007C */
#define FEATURE_VOTE_1_OFFSET 0
#define FEATURE_VOTE_1_BITS 4
#define FEATURE_VOTE_1_MASK (((1 << 4) - 1) << 0)
/* DRC_FEATURE_MAP2 0x0080 */
#define FEATURE_VOTE_2_OFFSET 0
#define FEATURE_VOTE_2_BITS 4
#define FEATURE_VOTE_2_MASK (((1 << 4) - 1) << 0)
/* DRC_FEATURE_MAP3 0x0084 */
#define FEATURE_VOTE_3_OFFSET 0
#define FEATURE_VOTE_3_BITS 4
#define FEATURE_VOTE_3_MASK (((1 << 4) - 1) << 0)
/* DRC_FEATURE_MAP4 0x0088 */
#define FEATURE_VOTE_4_OFFSET 0
#define FEATURE_VOTE_4_BITS 4
#define FEATURE_VOTE_4_MASK (((1 << 4) - 1) << 0)
/* DRC_FEATURE_MAP5 0x008C */
#define FEATURE_VOTE_5_OFFSET 0
#define FEATURE_VOTE_5_BITS 4
#define FEATURE_VOTE_5_MASK (((1 << 4) - 1) << 0)
/* DRC_FEATURE_MAP6 0x0090 */
#define FEATURE_VOTE_6_OFFSET 0
#define FEATURE_VOTE_6_BITS 4
#define FEATURE_VOTE_6_MASK (((1 << 4) - 1) << 0)
/* DRC_FEATURE_MAP7 0x0094 */
#define FEATURE_VOTE_7_OFFSET 0
#define FEATURE_VOTE_7_BITS 4
#define FEATURE_VOTE_7_MASK (((1 << 4) - 1) << 0)
/* DRC_FEATURE_MAP8 0x0098 */
#define FEATURE_VOTE_8_OFFSET 0
#define FEATURE_VOTE_8_BITS 4
#define FEATURE_VOTE_8_MASK (((1 << 4) - 1) << 0)
/* DRC_CC_BC_RATE 0x009C */
#define CC_BC_BLENDING_RATE_OFFSET 0
#define CC_BC_BLENDING_RATE_BITS 12
#define CC_BC_BLENDING_RATE_MASK (((1 << 12) - 1) << 0)
/* DRC_ORG_BLENDING_VALUE0 0x00A0 */
#define DRC_ORG_BLENDING_AUTO_LOW_BOUND_OFFSET 0
#define DRC_ORG_BLENDING_AUTO_LOW_BOUND_BITS 10
#define DRC_ORG_BLENDING_AUTO_LOW_BOUND_MASK (((1 << 10) - 1) << 0)
/* DRC_ORG_BLENDING_VALUE1 0x00A4 */
#define DRC_ORG_BLENDING_MANUAL_RATE_OFFSET 0
#define DRC_ORG_BLENDING_MANUAL_RATE_BITS 4
#define DRC_ORG_BLENDING_MANUAL_RATE_MASK (((1 << 4) - 1) << 0)
/* DRC_DARK_REGION_ENHANCEMENT0 0x00A8 */
#define CONTRAST_LEVEL_OFFSET 0
#define CONTRAST_LEVEL_BITS 8
#define CONTRAST_LEVEL_MASK (((1 << 8) - 1) << 0)
/* DRC_DARK_REGION_ENHANCEMENT1 0x00AC */
#define DRE_RANGE_OFFSET 0
#define DRE_RANGE_BITS 4
#define DRE_RANGE_MASK (((1 << 4) - 1) << 0)
/* DRC_DARK_REGION_ENHANCEMENT2 0x00B0 */
#define DRE_STRENGTH_OFFSET 0
#define DRE_STRENGTH_BITS 4
#define DRE_STRENGTH_MASK (((1 << 4) - 1) << 0)
/* DRC_LOCAL_DIFF 0x00B4 */
#define LOCAL_CONTRAST_DIFF_OFFSET 0
#define LOCAL_CONTRAST_DIFF_BITS 6
#define LOCAL_CONTRAST_DIFF_MASK (((1 << 6) - 1) << 0)
/* DRC_DYNAMIC_RANGE 0x00B8 */
#define DYNAMIC_RANGE_MANUAL_OFFSET 16
#define DYNAMIC_RANGE_MANUAL_BITS 6
#define DYNAMIC_RANGE_MANUAL_MASK (((1 << 6) - 1) << 16)
/* DRC_LOCAL_CONTRAST0 0x00BC */
#define LOCAL_CONTRAST_DARK_RATE_OFFSET 0
#define LOCAL_CONTRAST_DARK_RATE_BITS 6
#define LOCAL_CONTRAST_DARK_RATE_MASK (((1 << 6) - 1) << 0)
/* DRC_LOCAL_CONTRAST1 0x00C0 */
#define LOCAL_CONTRAST_BRIGHT_RATE_OFFSET 0
#define LOCAL_CONTRAST_BRIGHT_RATE_BITS 6
#define LOCAL_CONTRAST_BRIGHT_RATE_MASK (((1 << 6) - 1) << 0)
/* DRC_HF_ADDITION_GRADIENT0 0x00C4 */
#define HF_ADDITION_GRADIENT_LOWEST_WEIGHT_OFFSET 0
#define HF_ADDITION_GRADIENT_LOWEST_WEIGHT_BITS 6
#define HF_ADDITION_GRADIENT_LOWEST_WEIGHT_MASK (((1 << 6) - 1) << 0)
/* DRC_HF_ADDITION_GRADIENT1 0x00C8 */
#define HF_ADDITION_GRADIENT_LOW_OFFSET 0
#define HF_ADDITION_GRADIENT_LOW_BITS 10
#define HF_ADDITION_GRADIENT_LOW_MASK (((1 << 10) - 1) << 0)
/* DRC_BFILTER_WIN 0x00CC */
#define BFILTER_WIN_BC_OFFSET 0
#define BFILTER_WIN_BC_BITS 5
#define BFILTER_WIN_BC_MASK (((1 << 5) - 1) << 0)
#define BFILTER_WIN_CC_OFFSET 8
#define BFILTER_WIN_CC_BITS 5
#define BFILTER_WIN_CC_MASK (((1 << 5) - 1) << 8)
/* DRC_FRAME_SIZE 0x00D0 */
#define FRAME_SIZE_OFFSET 0
#define FRAME_SIZE_BITS 24
#define FRAME_SIZE_MASK (((1 << 24) - 1) << 0)
/* DRC_DEALY_NUM 0x00D4 */
#define FRAME_INTER_SAMPLE_OFFSET 0
#define FRAME_INTER_SAMPLE_BITS 4
#define FRAME_INTER_SAMPLE_MASK (((1 << 4) - 1) << 0)
#define DELAY_IN_NUM_OFFSET 4
#define DELAY_IN_NUM_BITS 4
#define DELAY_IN_NUM_MASK (((1 << 4) - 1) << 4)
#define DELAY_INTER_NUM_OFFSET 8
#define DELAY_INTER_NUM_BITS 4
#define DELAY_INTER_NUM_MASK (((1 << 4) - 1) << 8)
/* DRC_DRC_SAT_THD 0x00D8 */
#define SAT_THD_OFFSET 0
#define SAT_THD_BITS 14
#define SAT_THD_MASK (((1 << 14) - 1) << 0)
/* DRC_DRC_UPDATE 0x00DC */
#define DRC_STEP_OFFSET 0
#define DRC_STEP_BITS 12
#define DRC_STEP_MASK (((1 << 12) - 1) << 0)
/* DRC_RATIO_CP 0x00E0 */
#define HISTCLIM_RATIO_CP_OFFSET 0
#define HISTCLIM_RATIO_CP_BITS 8
#define HISTCLIM_RATIO_CP_MASK (((1 << 8) - 1) << 0)
/* DRC_RATIO_BP 0x00E4 */
#define HISTCLIM_RATIO_BP_OFFSET 0
#define HISTCLIM_RATIO_BP_BITS 8
#define HISTCLIM_RATIO_BP_MASK (((1 << 8) - 1) << 0)
/* DRC_VAR 0x0108 */
#define FINAL_VARIANCE_OFFSET 0
#define FINAL_VARIANCE_BITS 11
#define FINAL_VARIANCE_MASK (((1 << 11) - 1) << 0)

#endif /* _ISP_REG_INTP_H_INC_ */

