#ifndef _ISP_REG_MIPIOUT_H_INC_
#define _ISP_REG_MIPIOUT_H_INC_

#include <isp_reg.h>
#include <isp_reg_base.h>

#define MIPI_TX_EN (MIPIOUT_REG_BASE + 0x0000)
#define MIPI_TX_CHANNEL_CFG (MIPIOUT_REG_BASE + 0x0004)
#define MIPI_TX_LANE_CFG (MIPIOUT_REG_BASE + 0x0008)
#define MIPI_TX_HS_EXIT_TIME (MIPIOUT_REG_BASE + 0x000C)
#define MIPI_TX_INIT_TIME (MIPIOUT_REG_BASE + 0x0010)
#define MIPI_TX_LPX_TIME (MIPIOUT_REG_BASE + 0x0014)
#define MIPI_TX_CLK_POST_TIME (MIPIOUT_REG_BASE + 0x0018)
#define MIPI_TX_CLK_PRPR_TIME (MIPIOUT_REG_BASE + 0x001C)
#define MIPI_TX_CLK_ZERO_TIME (MIPIOUT_REG_BASE + 0x0024)
#define MIPI_TX_CLK_PRE_TIME (MIPIOUT_REG_BASE + 0x0028)
#define MIPI_TX_HS_PRPR_TIME (MIPIOUT_REG_BASE + 0x002C)
#define MIPI_TX_HS_ZERO_TIME (MIPIOUT_REG_BASE + 0x0030)
#define MIPI_TX_TRAIL_TIME (MIPIOUT_REG_BASE + 0x0034)
#define MIPI_TX_VLD_TIME (MIPIOUT_REG_BASE + 0x0038)
#define MIPI_TX_APHY_CTRL_POLAR (MIPIOUT_REG_BASE + 0x003C)
#define MIPI_TX_HS_WKUP_TIME (MIPIOUT_REG_BASE + 0x0040)
#define MIPI_TX_MULTI_LANE (MIPIOUT_REG_BASE + 0x0044)
#define MIPI_TX_LANE_SEL (MIPIOUT_REG_BASE + 0x0048)
#define MIPI_TX_CH0_CFG (MIPIOUT_REG_BASE + 0x004C)
#define MIPI_TX_CH1_CFG (MIPIOUT_REG_BASE + 0x0050)
#define MIPI_TX_START_POINT_CH0 (MIPIOUT_REG_BASE + 0x0054)
#define MIPI_TX_BUFF_FACTOR_CH0 (MIPIOUT_REG_BASE + 0x0058)
#define MIPI_TX_START_POINT_CH1 (MIPIOUT_REG_BASE + 0x005C)
#define MIPI_TX_BUFF_FACTOR_CH1 (MIPIOUT_REG_BASE + 0x0060)
#define MIPI_TX_VC_WAIT_TIME (MIPIOUT_REG_BASE + 0x0064)
#define MIPI_TX_INT_EN (MIPIOUT_REG_BASE + 0x0068)
#define MIPI_TX_INT_SEL (MIPIOUT_REG_BASE + 0x006C)
#define MIPI_TX_FRAME_WIDTH (MIPIOUT_REG_BASE + 0x0070)
#define MIPI_TXCLK_INV (MIPIOUT_REG_BASE + 0x0074)
#define MIPI_TX_BRK_TIME_CH0 (MIPIOUT_REG_BASE + 0x0078)
#define MIPI_TX_SP_FRAME_NUM_CH0 (MIPIOUT_REG_BASE + 0x007C)
#define MIPI_TX_SP_LINE_NUM_START_CH0 (MIPIOUT_REG_BASE + 0x0080)
#define MIPI_TX_SP_LINE_NUM_STEP_CH0 (MIPIOUT_REG_BASE + 0x0084)
#define MIPI_TX_BRK_TIME_CH1 (MIPIOUT_REG_BASE + 0x0090)
#define MIPI_TX_SP_FRAME_NUM_CH1 (MIPIOUT_REG_BASE + 0x0094)
#define MIPI_TX_SP_LINE_NUM_START_CH1 (MIPIOUT_REG_BASE + 0x0098)
#define MIPI_TX_SP_LINE_NUM_STEP_CH1 (MIPIOUT_REG_BASE + 0x009C)
#define MIPI_TX_OVFL_INT (MIPIOUT_REG_BASE + 0x00A0)
#define MIPI_TX_MEM_ERROR_CNT_CLR (MIPIOUT_REG_BASE + 0x00A4)
#define MIPI_TX_TEST (MIPIOUT_REG_BASE + 0x00A8)
#define MIPI_TX_SLB_CTRL (MIPIOUT_REG_BASE + 0x00AC)
#define MIPI_TX_CLR (MIPIOUT_REG_BASE + 0x00B0)
#define MIPI_TX_MAX_CONTENT (MIPIOUT_REG_BASE + 0x00B4)
#define MIPI_TX_MEM_STATE (MIPIOUT_REG_BASE + 0x00B8)
#define MIPI_TX_DROP_FLAG (MIPIOUT_REG_BASE + 0x00BC)
#define MIPI_TX_FRAME_START_END_CNT (MIPIOUT_REG_BASE + 0x00C0)
#define MIPI_TX_MEM_ERROR_CNT (MIPIOUT_REG_BASE + 0x00C4)
#define MIPI_TX_FRAME_CNT (MIPIOUT_REG_BASE + 0x00C8)
#define MIPI_TX_DIN_SEL (MIPIOUT_REG_BASE + 0x00CC)
#define MIPI_TX_CLK_CNT (MIPIOUT_REG_BASE + 0x00D0)
#define MIPI_TX_APHY_CFG_0 (MIPIOUT_REG_BASE + 0x0100)
#define MIPI_TX_APHY_CFG_1 (MIPIOUT_REG_BASE + 0x0104)
#define MIPI_TX_APHY_CFG_2 (MIPIOUT_REG_BASE + 0x0108)
#define MIPI_TX_APHY_CFG_3 (MIPIOUT_REG_BASE + 0x010C)
#define MIPI_TX_APHY_CFG_4 (MIPIOUT_REG_BASE + 0x0110)
#define MIPI_TX_APHY_CFG_5 (MIPIOUT_REG_BASE + 0x0114)
#define MIPI_TX_APHY_CFG_6 (MIPIOUT_REG_BASE + 0x0118)
#define MIPI_TX_APHY_CFG_7 (MIPIOUT_REG_BASE + 0x011C)
#define MIPI_TX_APHY_CFG_8 (MIPIOUT_REG_BASE + 0x0120)
#define MIPI_TX_APHY_CFG_9 (MIPIOUT_REG_BASE + 0x0124)
#define MIPI_TX_APHY_CFG_10 (MIPIOUT_REG_BASE + 0x0128)
#define MIPI_TX_APHY_CFG_11 (MIPIOUT_REG_BASE + 0x012C)
#define MIPI_TX_APHY_CFG_12 (MIPIOUT_REG_BASE + 0x0130)

/* MIPI_TX_EN 0x0000 */
#define MIPI_TX_EN_OFFSET 0
#define MIPI_TX_EN_BITS 1
#define MIPI_TX_EN_MASK (((1 << 1) - 1) << 0)
/* MIPI_TX_CHANNEL_CFG 0x0004 */
#define CHANNEL_EN_OFFSET 0
#define CHANNEL_EN_BITS 2
#define CHANNEL_EN_MASK (((1 << 2) - 1) << 0)
#define CH0_STREAM_SEL_OFFSET 2
#define CH0_STREAM_SEL_BITS 1
#define CH0_STREAM_SEL_MASK (((1 << 1) - 1) << 2)
#define CH1_STREAM_SEL_OFFSET 3
#define CH1_STREAM_SEL_BITS 1
#define CH1_STREAM_SEL_MASK (((1 << 1) - 1) << 3)
#define CH0_FRAME_SYNC_EN_OFFSET 4
#define CH0_FRAME_SYNC_EN_BITS 1
#define CH0_FRAME_SYNC_EN_MASK (((1 << 1) - 1) << 4)
#define CH1_FRAME_SYNC_EN_OFFSET 5
#define CH1_FRAME_SYNC_EN_BITS 1
#define CH1_FRAME_SYNC_EN_MASK (((1 << 1) - 1) << 5)
#define CH0_LINE_SYNC_EN_OFFSET 6
#define CH0_LINE_SYNC_EN_BITS 1
#define CH0_LINE_SYNC_EN_MASK (((1 << 1) - 1) << 6)
#define CH1_LINE_SYNC_EN_OFFSET 7
#define CH1_LINE_SYNC_EN_BITS 1
#define CH1_LINE_SYNC_EN_MASK (((1 << 1) - 1) << 7)
/* MIPI_TX_LANE_CFG 0x0008 */
#define LANE0_EN_OFFSET 0
#define LANE0_EN_BITS 1
#define LANE0_EN_MASK (((1 << 1) - 1) << 0)
#define LANE1_EN_OFFSET 1
#define LANE1_EN_BITS 1
#define LANE1_EN_MASK (((1 << 1) - 1) << 1)
#define LANE2_EN_OFFSET 2
#define LANE2_EN_BITS 1
#define LANE2_EN_MASK (((1 << 1) - 1) << 2)
#define LANE3_EN_OFFSET 3
#define LANE3_EN_BITS 1
#define LANE3_EN_MASK (((1 << 1) - 1) << 3)
#define NONCLK_EN_OFFSET 4
#define NONCLK_EN_BITS 1
#define NONCLK_EN_MASK (((1 << 1) - 1) << 4)
#define BIT_SWP_OFFSET 5
#define BIT_SWP_BITS 1
#define BIT_SWP_MASK (((1 << 1) - 1) << 5)
/* MIPI_TX_HS_EXIT_TIME 0x000C */
#define HS_EXIT_TIME_OFFSET 0
#define HS_EXIT_TIME_BITS 8
#define HS_EXIT_TIME_MASK (((1 << 8) - 1) << 0)
/* MIPI_TX_INIT_TIME 0x0010 */
#define TX_INIT_TIME_OFFSET 0
#define TX_INIT_TIME_BITS 16
#define TX_INIT_TIME_MASK (((1 << 16) - 1) << 0)
/* MIPI_TX_LPX_TIME 0x0014 */
#define TX_LPX_TIME_OFFSET 0
#define TX_LPX_TIME_BITS 8
#define TX_LPX_TIME_MASK (((1 << 8) - 1) << 0)
/* MIPI_TX_CLK_POST_TIME 0x0018 */
#define CLK_POST_TIME_OFFSET 0
#define CLK_POST_TIME_BITS 8
#define CLK_POST_TIME_MASK (((1 << 8) - 1) << 0)
/* MIPI_TX_CLK_PRPR_TIME 0x001C */
#define CLK_PRPR_TIME_OFFSET 0
#define CLK_PRPR_TIME_BITS 8
#define CLK_PRPR_TIME_MASK (((1 << 8) - 1) << 0)
/* MIPI_TX_CLK_ZERO_TIME 0x0024 */
#define CLK_ZERO_TIME_OFFSET 0
#define CLK_ZERO_TIME_BITS 8
#define CLK_ZERO_TIME_MASK (((1 << 8) - 1) << 0)
/* MIPI_TX_CLK_PRE_TIME 0x0028 */
#define CLK_PRE_TIME_OFFSET 0
#define CLK_PRE_TIME_BITS 8
#define CLK_PRE_TIME_MASK (((1 << 8) - 1) << 0)
/* MIPI_TX_HS_PRPR_TIME 0x002C */
#define HS_PRPR_TIME_OFFSET 0
#define HS_PRPR_TIME_BITS 8
#define HS_PRPR_TIME_MASK (((1 << 8) - 1) << 0)
/* MIPI_TX_HS_ZERO_TIME 0x0030 */
#define HS_ZERO_TIME_OFFSET 0
#define HS_ZERO_TIME_BITS 8
#define HS_ZERO_TIME_MASK (((1 << 8) - 1) << 0)
/* MIPI_TX_TRAIL_TIME 0x0034 */
#define TX_TRAIL_TIME_OFFSET 0
#define TX_TRAIL_TIME_BITS 8
#define TX_TRAIL_TIME_MASK (((1 << 8) - 1) << 0)
/* MIPI_TX_VLD_TIME 0x0038 */
#define TX_VLD_TIME_OFFSET 0
#define TX_VLD_TIME_BITS 8
#define TX_VLD_TIME_MASK (((1 << 8) - 1) << 0)
/* MIPI_TX_APHY_CTRL_POLAR 0x003C */
#define WKUP_DAT_CFG_OFFSET 0
#define WKUP_DAT_CFG_BITS 1
#define WKUP_DAT_CFG_MASK (((1 << 1) - 1) << 0)
#define WKUP_CLK_CFG_OFFSET 1
#define WKUP_CLK_CFG_BITS 1
#define WKUP_CLK_CFG_MASK (((1 << 1) - 1) << 1)
#define ENHST_DAT_CFG_OFFSET 2
#define ENHST_DAT_CFG_BITS 1
#define ENHST_DAT_CFG_MASK (((1 << 1) - 1) << 2)
#define ENHST_CLK_CFG_OFFSET 3
#define ENHST_CLK_CFG_BITS 1
#define ENHST_CLK_CFG_MASK (((1 << 1) - 1) << 3)
#define LP_DAT_CFG_OFFSET 4
#define LP_DAT_CFG_BITS 1
#define LP_DAT_CFG_MASK (((1 << 1) - 1) << 4)
#define LP_CLK_CFG_OFFSET 5
#define LP_CLK_CFG_BITS 1
#define LP_CLK_CFG_MASK (((1 << 1) - 1) << 5)
#define HSVLD_DAT_CFG_OFFSET 6
#define HSVLD_DAT_CFG_BITS 1
#define HSVLD_DAT_CFG_MASK (((1 << 1) - 1) << 6)
#define HSVLD_CLK_CFG_OFFSET 7
#define HSVLD_CLK_CFG_BITS 1
#define HSVLD_CLK_CFG_MASK (((1 << 1) - 1) << 7)
#define CLKEDGE_CFG_OFFSET 8
#define CLKEDGE_CFG_BITS 1
#define CLKEDGE_CFG_MASK (((1 << 1) - 1) << 8)
/* MIPI_TX_HS_WKUP_TIME 0x0040 */
#define HS_WKUP_TIME_OFFSET 0
#define HS_WKUP_TIME_BITS 8
#define HS_WKUP_TIME_MASK (((1 << 8) - 1) << 0)
/* MIPI_TX_MULTI_LANE 0x0044 */
#define MULTI_LANE_OFFSET 0
#define MULTI_LANE_BITS 2
#define MULTI_LANE_MASK (((1 << 2) - 1) << 0)
/* MIPI_TX_LANE_SEL 0x0048 */
#define LANE0_SEL_OFFSET 0
#define LANE0_SEL_BITS 2
#define LANE0_SEL_MASK (((1 << 2) - 1) << 0)
#define LANE1_SEL_OFFSET 2
#define LANE1_SEL_BITS 2
#define LANE1_SEL_MASK (((1 << 2) - 1) << 2)
#define LANE2_SEL_OFFSET 4
#define LANE2_SEL_BITS 2
#define LANE2_SEL_MASK (((1 << 2) - 1) << 4)
#define LANE3_SEL_OFFSET 6
#define LANE3_SEL_BITS 2
#define LANE3_SEL_MASK (((1 << 2) - 1) << 6)
/* MIPI_TX_CH0_CFG 0x004C */
#define RAW_EN_CH0_OFFSET 0
#define RAW_EN_CH0_BITS 4
#define RAW_EN_CH0_MASK (((1 << 4) - 1) << 0)
#define JPEG_8BIT_CH0_OFFSET 4
#define JPEG_8BIT_CH0_BITS 1
#define JPEG_8BIT_CH0_MASK (((1 << 1) - 1) << 4)
#define BYTE_SWP_CH0_OFFSET 5
#define BYTE_SWP_CH0_BITS 1
#define BYTE_SWP_CH0_MASK (((1 << 1) - 1) << 5)
#define UV_ORDER_CH0_OFFSET 6
#define UV_ORDER_CH0_BITS 2
#define UV_ORDER_CH0_MASK (((1 << 2) - 1) << 6)
#define DATA_TYPE_CH0_OFFSET 8
#define DATA_TYPE_CH0_BITS 8
#define DATA_TYPE_CH0_MASK (((1 << 8) - 1) << 8)
#define JPEG_FRAME_WIDTH_CH0_OFFSET 16
#define JPEG_FRAME_WIDTH_CH0_BITS 16
#define JPEG_FRAME_WIDTH_CH0_MASK (((1 << 16) - 1) << 16)
/* MIPI_TX_CH1_CFG 0x0050 */
#define RAW_EN_CH1_OFFSET 0
#define RAW_EN_CH1_BITS 4
#define RAW_EN_CH1_MASK (((1 << 4) - 1) << 0)
#define JPEG_8BIT_CH1_OFFSET 4
#define JPEG_8BIT_CH1_BITS 1
#define JPEG_8BIT_CH1_MASK (((1 << 1) - 1) << 4)
#define BYTE_SWP_CH1_OFFSET 5
#define BYTE_SWP_CH1_BITS 1
#define BYTE_SWP_CH1_MASK (((1 << 1) - 1) << 5)
#define UV_ORDER_CH1_OFFSET 6
#define UV_ORDER_CH1_BITS 2
#define UV_ORDER_CH1_MASK (((1 << 2) - 1) << 6)
#define DATA_TYPE_CH1_OFFSET 8
#define DATA_TYPE_CH1_BITS 8
#define DATA_TYPE_CH1_MASK (((1 << 8) - 1) << 8)
#define JPEG_FRAME_WIDTH_CH1_OFFSET 16
#define JPEG_FRAME_WIDTH_CH1_BITS 16
#define JPEG_FRAME_WIDTH_CH1_MASK (((1 << 16) - 1) << 16)
/* MIPI_TX_START_POINT_CH0 0x0054 */
#define TX_START_POINT_CH0_OFFSET 0
#define TX_START_POINT_CH0_BITS 14
#define TX_START_POINT_CH0_MASK (((1 << 14) - 1) << 0)
/* MIPI_TX_BUFF_FACTOR_CH0 0x0058 */
#define TX_BUFF_FACTOR_CH0_OFFSET 0
#define TX_BUFF_FACTOR_CH0_BITS 8
#define TX_BUFF_FACTOR_CH0_MASK (((1 << 8) - 1) << 0)
/* MIPI_TX_START_POINT_CH1 0x005C */
#define TX_START_POINT_CH1_OFFSET 0
#define TX_START_POINT_CH1_BITS 14
#define TX_START_POINT_CH1_MASK (((1 << 14) - 1) << 0)
/* MIPI_TX_BUFF_FACTOR_CH1 0x0060 */
#define TX_BUFF_FACTOR_CH1_OFFSET 0
#define TX_BUFF_FACTOR_CH1_BITS 8
#define TX_BUFF_FACTOR_CH1_MASK (((1 << 8) - 1) << 0)
/* MIPI_TX_VC_WAIT_TIME 0x0064 */
#define VC_WAIT_TIME_OFFSET 0
#define VC_WAIT_TIME_BITS 8
#define VC_WAIT_TIME_MASK (((1 << 8) - 1) << 0)
/* MIPI_TX_INT_EN 0x0068 */
#define CH0_FRAME_START_INT_EN_OFFSET 0
#define CH0_FRAME_START_INT_EN_BITS 1
#define CH0_FRAME_START_INT_EN_MASK (((1 << 1) - 1) << 0)
#define CH0_FRAME_END_INT_EN_OFFSET 1
#define CH0_FRAME_END_INT_EN_BITS 1
#define CH0_FRAME_END_INT_EN_MASK (((1 << 1) - 1) << 1)
#define CH1_FRAME_START_INT_EN_OFFSET 2
#define CH1_FRAME_START_INT_EN_BITS 1
#define CH1_FRAME_START_INT_EN_MASK (((1 << 1) - 1) << 2)
#define CH1_FRAME_END_INT_EN_OFFSET 3
#define CH1_FRAME_END_INT_EN_BITS 1
#define CH1_FRAME_END_INT_EN_MASK (((1 << 1) - 1) << 3)
/* MIPI_TX_INT_SEL 0x006C */
#define CH0_FRAME_START_INT_SEL_OFFSET 0
#define CH0_FRAME_START_INT_SEL_BITS 1
#define CH0_FRAME_START_INT_SEL_MASK (((1 << 1) - 1) << 0)
#define CH0_FRAME_END_INT_SEL_OFFSET 1
#define CH0_FRAME_END_INT_SEL_BITS 1
#define CH0_FRAME_END_INT_SEL_MASK (((1 << 1) - 1) << 1)
#define CH1_FRAME_START_INT_SEL_OFFSET 2
#define CH1_FRAME_START_INT_SEL_BITS 1
#define CH1_FRAME_START_INT_SEL_MASK (((1 << 1) - 1) << 2)
#define CH1_FRAME_END_INT_SEL_OFFSET 3
#define CH1_FRAME_END_INT_SEL_BITS 1
#define CH1_FRAME_END_INT_SEL_MASK (((1 << 1) - 1) << 3)
/* MIPI_TX_FRAME_WIDTH 0x0070 */
#define ISP_FRAME_WIDTH_CH0_OFFSET 0
#define ISP_FRAME_WIDTH_CH0_BITS 16
#define ISP_FRAME_WIDTH_CH0_MASK (((1 << 16) - 1) << 0)
#define ISP_FRAME_WIDTH_CH1_OFFSET 16
#define ISP_FRAME_WIDTH_CH1_BITS 16
#define ISP_FRAME_WIDTH_CH1_MASK (((1 << 16) - 1) << 16)
/* MIPI_TXCLK_INV 0x0074 */
#define TXCLK_INV_OFFSET 0
#define TXCLK_INV_BITS 1
#define TXCLK_INV_MASK (((1 << 1) - 1) << 0)
/* MIPI_TX_BRK_TIME_CH0 0x0078 */
#define DATA_BRK_TIME_CH0_OFFSET 0
#define DATA_BRK_TIME_CH0_BITS 8
#define DATA_BRK_TIME_CH0_MASK (((1 << 8) - 1) << 0)
#define LINE_BRK_TIME_CH0_OFFSET 8
#define LINE_BRK_TIME_CH0_BITS 8
#define LINE_BRK_TIME_CH0_MASK (((1 << 8) - 1) << 8)
#define FRAME_BRK_TIME_CH0_OFFSET 16
#define FRAME_BRK_TIME_CH0_BITS 8
#define FRAME_BRK_TIME_CH0_MASK (((1 << 8) - 1) << 16)
/* MIPI_TX_SP_FRAME_NUM_CH0 0x007C */
#define SP_FRAME_NUM_CTRL_CH0_OFFSET 0
#define SP_FRAME_NUM_CTRL_CH0_BITS 1
#define SP_FRAME_NUM_CTRL_CH0_MASK (((1 << 1) - 1) << 0)
#define SP_FRAME_NUM_MAX_CH0_OFFSET 8
#define SP_FRAME_NUM_MAX_CH0_BITS 16
#define SP_FRAME_NUM_MAX_CH0_MASK (((1 << 16) - 1) << 8)
/* MIPI_TX_SP_LINE_NUM_START_CH0 0x0080 */
#define SP_LINE_NUM_CTRL_CH0_OFFSET 0
#define SP_LINE_NUM_CTRL_CH0_BITS 1
#define SP_LINE_NUM_CTRL_CH0_MASK (((1 << 1) - 1) << 0)
#define SP_LINE_NUM_START_CH0_OFFSET 8
#define SP_LINE_NUM_START_CH0_BITS 16
#define SP_LINE_NUM_START_CH0_MASK (((1 << 16) - 1) << 8)
/* MIPI_TX_SP_LINE_NUM_STEP_CH0 0x0084 */
#define SP_LINE_NUM_STEP_CH0_OFFSET 0
#define SP_LINE_NUM_STEP_CH0_BITS 16
#define SP_LINE_NUM_STEP_CH0_MASK (((1 << 16) - 1) << 0)
/* MIPI_TX_BRK_TIME_CH1 0x0090 */
#define DATA_BRK_TIME_CH1_OFFSET 0
#define DATA_BRK_TIME_CH1_BITS 8
#define DATA_BRK_TIME_CH1_MASK (((1 << 8) - 1) << 0)
#define LINE_BRK_TIME_CH1_OFFSET 8
#define LINE_BRK_TIME_CH1_BITS 8
#define LINE_BRK_TIME_CH1_MASK (((1 << 8) - 1) << 8)
#define FRAME_BRK_TIME_CH1_OFFSET 16
#define FRAME_BRK_TIME_CH1_BITS 8
#define FRAME_BRK_TIME_CH1_MASK (((1 << 8) - 1) << 16)
/* MIPI_TX_SP_FRAME_NUM_CH1 0x0094 */
#define SP_FRAME_NUM_CTRL_CH1_OFFSET 0
#define SP_FRAME_NUM_CTRL_CH1_BITS 1
#define SP_FRAME_NUM_CTRL_CH1_MASK (((1 << 1) - 1) << 0)
#define SP_FRAME_NUM_MAX_CH1_OFFSET 8
#define SP_FRAME_NUM_MAX_CH1_BITS 16
#define SP_FRAME_NUM_MAX_CH1_MASK (((1 << 16) - 1) << 8)
/* MIPI_TX_SP_LINE_NUM_START_CH1 0x0098 */
#define SP_LINE_NUM_CTRL_CH1_OFFSET 0
#define SP_LINE_NUM_CTRL_CH1_BITS 1
#define SP_LINE_NUM_CTRL_CH1_MASK (((1 << 1) - 1) << 0)
#define SP_LINE_NUM_START_CH1_OFFSET 8
#define SP_LINE_NUM_START_CH1_BITS 16
#define SP_LINE_NUM_START_CH1_MASK (((1 << 16) - 1) << 8)
/* MIPI_TX_SP_LINE_NUM_STEP_CH1 0x009C */
#define SP_LINE_NUM_STEP_CH1_OFFSET 0
#define SP_LINE_NUM_STEP_CH1_BITS 16
#define SP_LINE_NUM_STEP_CH1_MASK (((1 << 16) - 1) << 0)
/* MIPI_TX_OVFL_INT 0x00A0 */
#define CH0_OVERFLOW_INT_EN_OFFSET 0
#define CH0_OVERFLOW_INT_EN_BITS 1
#define CH0_OVERFLOW_INT_EN_MASK (((1 << 1) - 1) << 0)
#define CH0_OVERFLOW_INT_SEL_OFFSET 1
#define CH0_OVERFLOW_INT_SEL_BITS 1
#define CH0_OVERFLOW_INT_SEL_MASK (((1 << 1) - 1) << 1)
#define CH1_OVERFLOW_INT_EN_OFFSET 2
#define CH1_OVERFLOW_INT_EN_BITS 1
#define CH1_OVERFLOW_INT_EN_MASK (((1 << 1) - 1) << 2)
#define CH1_OVERFLOW_INT_SEL_OFFSET 3
#define CH1_OVERFLOW_INT_SEL_BITS 1
#define CH1_OVERFLOW_INT_SEL_MASK (((1 << 1) - 1) << 3)
/* MIPI_TX_MEM_ERROR_CNT_CLR 0x00A4 */
#define MEM_ERROR_CNT_CLR_CH0_OFFSET 0
#define MEM_ERROR_CNT_CLR_CH0_BITS 1
#define MEM_ERROR_CNT_CLR_CH0_MASK (((1 << 1) - 1) << 0)
#define MEM_ERROR_CNT_CLR_CH1_OFFSET 1
#define MEM_ERROR_CNT_CLR_CH1_BITS 1
#define MEM_ERROR_CNT_CLR_CH1_MASK (((1 << 1) - 1) << 1)
/* MIPI_TX_TEST 0x00A8 */
#define TEST_EN_OFFSET 0
#define TEST_EN_BITS 1
#define TEST_EN_MASK (((1 << 1) - 1) << 0)
#define TEST_HS_EN_OFFSET 1
#define TEST_HS_EN_BITS 1
#define TEST_HS_EN_MASK (((1 << 1) - 1) << 1)
#define TEST_DAT_MODE_OFFSET 2
#define TEST_DAT_MODE_BITS 1
#define TEST_DAT_MODE_MASK (((1 << 1) - 1) << 2)
#define TEST_HSDAT_ONLY_OFFSET 3
#define TEST_HSDAT_ONLY_BITS 1
#define TEST_HSDAT_ONLY_MASK (((1 << 1) - 1) << 3)
#define PDAT_TST_OFFSET 8
#define PDAT_TST_BITS 8
#define PDAT_TST_MASK (((1 << 8) - 1) << 8)
#define NDAT_TST_OFFSET 16
#define NDAT_TST_BITS 8
#define NDAT_TST_MASK (((1 << 8) - 1) << 16)
#define LPX_TST_OFFSET 24
#define LPX_TST_BITS 8
#define LPX_TST_MASK (((1 << 8) - 1) << 24)
/* MIPI_TX_SLB_CTRL 0x00AC */
#define SLB_EN_OFFSET 0
#define SLB_EN_BITS 1
#define SLB_EN_MASK (((1 << 1) - 1) << 0)
#define FIXP_GOING_OFFSET 1
#define FIXP_GOING_BITS 1
#define FIXP_GOING_MASK (((1 << 1) - 1) << 1)
#define SLB_ERROR_CLR_OFFSET 2
#define SLB_ERROR_CLR_BITS 1
#define SLB_ERROR_CLR_MASK (((1 << 1) - 1) << 2)
#define RECEIVER_CNT_CLR_OFFSET 3
#define RECEIVER_CNT_CLR_BITS 1
#define RECEIVER_CNT_CLR_MASK (((1 << 1) - 1) << 3)
#define FRAME_NUM_OFFSET 8
#define FRAME_NUM_BITS 8
#define FRAME_NUM_MASK (((1 << 8) - 1) << 8)
/* MIPI_TX_CLR 0x00B0 */
#define CH0_OVERFLOW_INT_CLR_OFFSET 0
#define CH0_OVERFLOW_INT_CLR_BITS 1
#define CH0_OVERFLOW_INT_CLR_MASK (((1 << 1) - 1) << 0)
#define CH1_OVERFLOW_INT_CLR_OFFSET 1
#define CH1_OVERFLOW_INT_CLR_BITS 1
#define CH1_OVERFLOW_INT_CLR_MASK (((1 << 1) - 1) << 1)
#define FRAME_DROP_CLR_OFFSET 2
#define FRAME_DROP_CLR_BITS 1
#define FRAME_DROP_CLR_MASK (((1 << 1) - 1) << 2)
#define CH1_FRAME_START_INT_CLR_OFFSET 3
#define CH1_FRAME_START_INT_CLR_BITS 1
#define CH1_FRAME_START_INT_CLR_MASK (((1 << 1) - 1) << 3)
#define CH1_FRAME_END_INT_CLR_OFFSET 4
#define CH1_FRAME_END_INT_CLR_BITS 1
#define CH1_FRAME_END_INT_CLR_MASK (((1 << 1) - 1) << 4)
#define CH0_FRAME_START_INT_CLR_OFFSET 5
#define CH0_FRAME_START_INT_CLR_BITS 1
#define CH0_FRAME_START_INT_CLR_MASK (((1 << 1) - 1) << 5)
#define CH0_FRAME_END_INT_CLR_OFFSET 6
#define CH0_FRAME_END_INT_CLR_BITS 1
#define CH0_FRAME_END_INT_CLR_MASK (((1 << 1) - 1) << 6)
#define CH0_CONTENT_CLR_OFFSET 7
#define CH0_CONTENT_CLR_BITS 1
#define CH0_CONTENT_CLR_MASK (((1 << 1) - 1) << 7)
#define CH1_CONTENT_CLR_OFFSET 8
#define CH1_CONTENT_CLR_BITS 1
#define CH1_CONTENT_CLR_MASK (((1 << 1) - 1) << 8)
/* MIPI_TX_MAX_CONTENT 0x00B4 */
#define MAX_CONTENT_CH0_OFFSET 0
#define MAX_CONTENT_CH0_BITS 14
#define MAX_CONTENT_CH0_MASK (((1 << 14) - 1) << 0)
#define MAX_CONTENT_CH1_OFFSET 16
#define MAX_CONTENT_CH1_BITS 14
#define MAX_CONTENT_CH1_MASK (((1 << 14) - 1) << 16)
/* MIPI_TX_MEM_STATE 0x00B8 */
#define MEM_STATE_CH0_OFFSET 0
#define MEM_STATE_CH0_BITS 4
#define MEM_STATE_CH0_MASK (((1 << 4) - 1) << 0)
#define MEM_STATE_CH1_OFFSET 8
#define MEM_STATE_CH1_BITS 4
#define MEM_STATE_CH1_MASK (((1 << 4) - 1) << 8)
/* MIPI_TX_DROP_FLAG 0x00BC */
#define FRAME_DROP_CH0_FLAG_OFFSET 0
#define FRAME_DROP_CH0_FLAG_BITS 1
#define FRAME_DROP_CH0_FLAG_MASK (((1 << 1) - 1) << 0)
#define FRAME_DROP_CH1_FLAG_OFFSET 1
#define FRAME_DROP_CH1_FLAG_BITS 1
#define FRAME_DROP_CH1_FLAG_MASK (((1 << 1) - 1) << 1)
/* MIPI_TX_FRAME_START_END_CNT 0x00C0 */
#define FRAME_START_CNT_CH0_OFFSET 0
#define FRAME_START_CNT_CH0_BITS 8
#define FRAME_START_CNT_CH0_MASK (((1 << 8) - 1) << 0)
#define FRAME_END_CNT_CH0_OFFSET 8
#define FRAME_END_CNT_CH0_BITS 8
#define FRAME_END_CNT_CH0_MASK (((1 << 8) - 1) << 8)
#define FRAME_START_CNT_CH1_OFFSET 16
#define FRAME_START_CNT_CH1_BITS 8
#define FRAME_START_CNT_CH1_MASK (((1 << 8) - 1) << 16)
#define FRAME_END_CNT_CH1_OFFSET 24
#define FRAME_END_CNT_CH1_BITS 8
#define FRAME_END_CNT_CH1_MASK (((1 << 8) - 1) << 24)
/* MIPI_TX_MEM_ERROR_CNT 0x00C4 */
#define TX_MEM_ERROR_CNT_CH0_OFFSET 0
#define TX_MEM_ERROR_CNT_CH0_BITS 16
#define TX_MEM_ERROR_CNT_CH0_MASK (((1 << 16) - 1) << 0)
#define TX_MEM_ERROR_CNT_CH1_OFFSET 16
#define TX_MEM_ERROR_CNT_CH1_BITS 16
#define TX_MEM_ERROR_CNT_CH1_MASK (((1 << 16) - 1) << 16)
/* MIPI_TX_FRAME_CNT 0x00C8 */
#define FRAME_CNT_CH0_OFFSET 0
#define FRAME_CNT_CH0_BITS 8
#define FRAME_CNT_CH0_MASK (((1 << 8) - 1) << 0)
#define FRAME_CNT_CH1_OFFSET 8
#define FRAME_CNT_CH1_BITS 8
#define FRAME_CNT_CH1_MASK (((1 << 8) - 1) << 8)
#define FRAME_WAIT_CH0_OFFSET 16
#define FRAME_WAIT_CH0_BITS 1
#define FRAME_WAIT_CH0_MASK (((1 << 1) - 1) << 16)
#define FRAME_WAIT_CH1_OFFSET 17
#define FRAME_WAIT_CH1_BITS 1
#define FRAME_WAIT_CH1_MASK (((1 << 1) - 1) << 17)
#define TX_DVP_FRAME_IDLE_OFFSET 18
#define TX_DVP_FRAME_IDLE_BITS 1
#define TX_DVP_FRAME_IDLE_MASK (((1 << 1) - 1) << 18)
/* MIPI_TX_DIN_SEL 0x00CC */
#define ISP_DOUT_OFFSET 0
#define ISP_DOUT_BITS 1
#define ISP_DOUT_MASK (((1 << 1) - 1) << 0)
#define MIPI_TX_IN_SEL_FIXP_OFFSET 1
#define MIPI_TX_IN_SEL_FIXP_BITS 1
#define MIPI_TX_IN_SEL_FIXP_MASK (((1 << 1) - 1) << 1)
#define MIPI_TX_IN_SEL_ISP_OFFSET 2
#define MIPI_TX_IN_SEL_ISP_BITS 1
#define MIPI_TX_IN_SEL_ISP_MASK (((1 << 1) - 1) << 2)
/* MIPI_TX_CLK_CNT 0x00D0 */
#define CLK_CNT_OFFSET 0
#define CLK_CNT_BITS 8
#define CLK_CNT_MASK (((1 << 8) - 1) << 0)
/* MIPI_TX_APHY_CFG_0 0x0100 */
#define REG_AMP_OFFSET 0
#define REG_AMP_BITS 3
#define REG_AMP_MASK (((1 << 3) - 1) << 0)
#define REG_BYPASS_8X_OFFSET 8
#define REG_BYPASS_8X_BITS 1
#define REG_BYPASS_8X_MASK (((1 << 1) - 1) << 8)
#define REG_CK1X_INV_OFFSET 16
#define REG_CK1X_INV_BITS 1
#define REG_CK1X_INV_MASK (((1 << 1) - 1) << 16)
#define REG_CK8X_INV_OFFSET 24
#define REG_CK8X_INV_BITS 1
#define REG_CK8X_INV_MASK (((1 << 1) - 1) << 24)
/* MIPI_TX_APHY_CFG_1 0x0104 */
#define REG_CK8X_LAG_OFFSET 0
#define REG_CK8X_LAG_BITS 1
#define REG_CK8X_LAG_MASK (((1 << 1) - 1) << 0)
#define REG_CK8X_PHS_OFFSET 8
#define REG_CK8X_PHS_BITS 2
#define REG_CK8X_PHS_MASK (((1 << 2) - 1) << 8)
#define REG_CMU_POW_OFFSET 16
#define REG_CMU_POW_BITS 1
#define REG_CMU_POW_MASK (((1 << 1) - 1) << 16)
#define REG_DATA0_DLY_OFFSET 24
#define REG_DATA0_DLY_BITS 5
#define REG_DATA0_DLY_MASK (((1 << 5) - 1) << 24)
/* MIPI_TX_APHY_CFG_2 0x0108 */
#define REG_DATA1_DLY_OFFSET 0
#define REG_DATA1_DLY_BITS 5
#define REG_DATA1_DLY_MASK (((1 << 5) - 1) << 0)
#define REG_DATA2_DLY_OFFSET 8
#define REG_DATA2_DLY_BITS 5
#define REG_DATA2_DLY_MASK (((1 << 5) - 1) << 8)
#define REG_DATA3_DLY_OFFSET 16
#define REG_DATA3_DLY_BITS 5
#define REG_DATA3_DLY_MASK (((1 << 5) - 1) << 16)
#define REG_DATA4_DLY_OFFSET 24
#define REG_DATA4_DLY_BITS 5
#define REG_DATA4_DLY_MASK (((1 << 5) - 1) << 24)
/* MIPI_TX_APHY_CFG_3 0x010C */
#define REG_DEEMP_EN_OFFSET 0
#define REG_DEEMP_EN_BITS 1
#define REG_DEEMP_EN_MASK (((1 << 1) - 1) << 0)
#define REG_EMP_OFFSET 8
#define REG_EMP_BITS 3
#define REG_EMP_MASK (((1 << 3) - 1) << 8)
#define REG_EN_LV_LDO_OFFSET 16
#define REG_EN_LV_LDO_BITS 1
#define REG_EN_LV_LDO_MASK (((1 << 1) - 1) << 16)
#define REG_EN_TX_LDO_OFFSET 24
#define REG_EN_TX_LDO_BITS 1
#define REG_EN_TX_LDO_MASK (((1 << 1) - 1) << 24)
/* MIPI_TX_APHY_CFG_4 0x0110 */
#define REG_IB_EN_OFFSET 0
#define REG_IB_EN_BITS 1
#define REG_IB_EN_MASK (((1 << 1) - 1) << 0)
#define REG_LPLDO_LVL_OFFSET 8
#define REG_LPLDO_LVL_BITS 3
#define REG_LPLDO_LVL_MASK (((1 << 3) - 1) << 8)
#define REG_LP_DRV_OFFSET 16
#define REG_LP_DRV_BITS 2
#define REG_LP_DRV_MASK (((1 << 2) - 1) << 16)
#define REG_MPLL_BIG_CCO_OFFSET 24
#define REG_MPLL_BIG_CCO_BITS 1
#define REG_MPLL_BIG_CCO_MASK (((1 << 1) - 1) << 24)
/* MIPI_TX_APHY_CFG_5 0x0114 */
#define REG_MPLL_DIVN_OFFSET 0
#define REG_MPLL_DIVN_BITS 8
#define REG_MPLL_DIVN_MASK (((1 << 8) - 1) << 0)
#define REG_MPLL_DIV_CYC_OFFSET 8
#define REG_MPLL_DIV_CYC_BITS 1
#define REG_MPLL_DIV_CYC_MASK (((1 << 1) - 1) << 8)
#define REG_MPLL_ICP_OFFSET 16
#define REG_MPLL_ICP_BITS 2
#define REG_MPLL_ICP_MASK (((1 << 2) - 1) << 16)
#define REG_MPLL_LDO_VREF_OFFSET 24
#define REG_MPLL_LDO_VREF_BITS 2
#define REG_MPLL_LDO_VREF_MASK (((1 << 2) - 1) << 24)
/* MIPI_TX_APHY_CFG_6 0x0118 */
#define REG_MPLL_LPF_SR_OFFSET 0
#define REG_MPLL_LPF_SR_BITS 3
#define REG_MPLL_LPF_SR_MASK (((1 << 3) - 1) << 0)
#define REG_MPLL_PDIV_OFFSET 8
#define REG_MPLL_PDIV_BITS 2
#define REG_MPLL_PDIV_MASK (((1 << 2) - 1) << 8)
#define REG_MPLL_PI_BYPASS_OFFSET 16
#define REG_MPLL_PI_BYPASS_BITS 1
#define REG_MPLL_PI_BYPASS_MASK (((1 << 1) - 1) << 16)
#define REG_MPLL_PI_C_OFFSET 24
#define REG_MPLL_PI_C_BITS 1
#define REG_MPLL_PI_C_MASK (((1 << 1) - 1) << 24)
/* MIPI_TX_APHY_CFG_7 0x011C */
#define REG_MPLL_PI_ISEL_OFFSET 0
#define REG_MPLL_PI_ISEL_BITS 2
#define REG_MPLL_PI_ISEL_MASK (((1 << 2) - 1) << 0)
#define REG_MPLL_PI_PH_OFFSET 8
#define REG_MPLL_PI_PH_BITS 5
#define REG_MPLL_PI_PH_MASK (((1 << 5) - 1) << 8)
#define REG_MPLL_TESTEN_OFFSET 16
#define REG_MPLL_TESTEN_BITS 1
#define REG_MPLL_TESTEN_MASK (((1 << 1) - 1) << 16)
#define REG_OVERSHOOT_BP_OFFSET 24
#define REG_OVERSHOOT_BP_BITS 1
#define REG_OVERSHOOT_BP_MASK (((1 << 1) - 1) << 24)
/* MIPI_TX_APHY_CFG_8 0x0120 */
#define REG_PAD0_MODE_OFFSET 0
#define REG_PAD0_MODE_BITS 2
#define REG_PAD0_MODE_MASK (((1 << 2) - 1) << 0)
#define REG_PAD1_MODE_OFFSET 8
#define REG_PAD1_MODE_BITS 2
#define REG_PAD1_MODE_MASK (((1 << 2) - 1) << 8)
#define REG_PAD2_MODE_OFFSET 16
#define REG_PAD2_MODE_BITS 2
#define REG_PAD2_MODE_MASK (((1 << 2) - 1) << 16)
#define REG_PAD3_MODE_OFFSET 24
#define REG_PAD3_MODE_BITS 2
#define REG_PAD3_MODE_MASK (((1 << 2) - 1) << 24)
/* MIPI_TX_APHY_CFG_9 0x0124 */
#define REG_PAD4_MODE_OFFSET 0
#define REG_PAD4_MODE_BITS 2
#define REG_PAD4_MODE_MASK (((1 << 2) - 1) << 0)
#define REG_PAD_STR_OFFSET 8
#define REG_PAD_STR_BITS 1
#define REG_PAD_STR_MASK (((1 << 1) - 1) << 8)
#define REG_RANGE_MODE_OFFSET 16
#define REG_RANGE_MODE_BITS 1
#define REG_RANGE_MODE_MASK (((1 << 1) - 1) << 16)
#define REG_SR_CTRL_OFFSET 24
#define REG_SR_CTRL_BITS 2
#define REG_SR_CTRL_MASK (((1 << 2) - 1) << 24)
/* MIPI_TX_APHY_CFG_10 0x0128 */
#define REG_TXTST_EN_OFFSET 0
#define REG_TXTST_EN_BITS 1
#define REG_TXTST_EN_MASK (((1 << 1) - 1) << 0)
#define REG_TXTST_SEL_OFFSET 8
#define REG_TXTST_SEL_BITS 2
#define REG_TXTST_SEL_MASK (((1 << 2) - 1) << 8)
#define REG_TX_PRECUR_SEL_OFFSET 16
#define REG_TX_PRECUR_SEL_BITS 2
#define REG_TX_PRECUR_SEL_MASK (((1 << 2) - 1) << 16)
#define REG_TX_PRERES_SEL_OFFSET 24
#define REG_TX_PRERES_SEL_BITS 2
#define REG_TX_PRERES_SEL_MASK (((1 << 2) - 1) << 24)
/* MIPI_TX_APHY_CFG_11 0x012C */
#define REG_Z0_TX_OFFSET 0
#define REG_Z0_TX_BITS 4
#define REG_Z0_TX_MASK (((1 << 4) - 1) << 0)
/* MIPI_TX_APHY_CFG_12 0x0130 */
#define REG_PWDB_OFFSET 0
#define REG_PWDB_BITS 1
#define REG_PWDB_MASK (((1 << 1) - 1) << 0)

#endif /* _ISP_REG_MIPIOUT_H_INC_ */

