#ifndef _ISP_REG_FUSION_H_INC_
#define _ISP_REG_FUSION_H_INC_

#include <isp_reg.h>
#include <isp_reg_base.h>

#define FUSION_EXP_RATIO (FS_REG_BASE + 0x0000)
#define FUSION_RATE_MAX_MIN (FS_REG_BASE + 0x0004)
#define FUSION_RATE_LUM_SLOP (FS_REG_BASE + 0x0008)
#define FUSION_LUM_THD (FS_REG_BASE + 0x000C)
#define FUSION_OVEXP_THD (FS_REG_BASE + 0x0010)
#define FUSION_OVEXP_SLOP (FS_REG_BASE + 0x0014)
#define FUSION_STREAM_EN (FS_REG_BASE + 0x0100)
#define FUSION_STREAM_CTRL (FS_REG_BASE + 0x0108)
#define FUSION_STREAM_FRAME_ADDR (FS_REG_BASE + 0x010C)
#define FUSION_STREAM_DDR_LEN (FS_REG_BASE + 0x0110)
#define FUSION_STREAM_START_LINENUM (FS_REG_BASE + 0x0114)
#define FUSION_STREAM_CTRL2 (FS_REG_BASE + 0x0118)
#define FUSION_REG_LOAD (FS_REG_BASE + 0x0200)

/* FUSION_EXP_RATIO 0x0000 */
#define FUSION_EXP_RATIO_OFFSET 0
#define FUSION_EXP_RATIO_BITS 9
#define FUSION_EXP_RATIO_MASK (((1 << 9) - 1) << 0)
#define CLIP_12BIT_OFFSET 12
#define CLIP_12BIT_BITS 1
#define CLIP_12BIT_MASK (((1 << 1) - 1) << 12)
#define CLIP_13BIT_OFFSET 13
#define CLIP_13BIT_BITS 1
#define CLIP_13BIT_MASK (((1 << 1) - 1) << 13)
#define CLIP_14BIT_OFFSET 14
#define CLIP_14BIT_BITS 1
#define CLIP_14BIT_MASK (((1 << 1) - 1) << 14)
#define FS_MODE_OFFSET 16
#define FS_MODE_BITS 2
#define FS_MODE_MASK (((1 << 2) - 1) << 16)
/* FUSION_RATE_MAX_MIN 0x0004 */
#define FUSION_RATE_MIN_OFFSET 0
#define FUSION_RATE_MIN_BITS 9
#define FUSION_RATE_MIN_MASK (((1 << 9) - 1) << 0)
#define FUSION_RATE_MAX_OFFSET 16
#define FUSION_RATE_MAX_BITS 9
#define FUSION_RATE_MAX_MASK (((1 << 9) - 1) << 16)
/* FUSION_RATE_LUM_SLOP 0x0008 */
#define FUSION_RATE_LUM_SLOP_OFFSET 0
#define FUSION_RATE_LUM_SLOP_BITS 20
#define FUSION_RATE_LUM_SLOP_MASK (((1 << 20) - 1) << 0)
/* FUSION_LUM_THD 0x000C */
#define FUSION_LUM_THD0_OFFSET 0
#define FUSION_LUM_THD0_BITS 12
#define FUSION_LUM_THD0_MASK (((1 << 12) - 1) << 0)
#define FUSION_LUM_THD1_OFFSET 16
#define FUSION_LUM_THD1_BITS 12
#define FUSION_LUM_THD1_MASK (((1 << 12) - 1) << 16)
/* FUSION_OVEXP_THD 0x0010 */
#define FUSION_OVEXP_THD0_OFFSET 0
#define FUSION_OVEXP_THD0_BITS 12
#define FUSION_OVEXP_THD0_MASK (((1 << 12) - 1) << 0)
#define FUSION_OVEXP_THD1_OFFSET 16
#define FUSION_OVEXP_THD1_BITS 12
#define FUSION_OVEXP_THD1_MASK (((1 << 12) - 1) << 16)
/* FUSION_OVEXP_SLOP 0x0014 */
#define FUSION_OVEXP_SLOP_OFFSET 0
#define FUSION_OVEXP_SLOP_BITS 13
#define FUSION_OVEXP_SLOP_MASK (((1 << 13) - 1) << 0)
#define FUSION_OVEXP_DATA_SEL_OFFSET 16
#define FUSION_OVEXP_DATA_SEL_BITS 1
#define FUSION_OVEXP_DATA_SEL_MASK (((1 << 1) - 1) << 16)
/* FUSION_STREAM_EN 0x0100 */
#define FUSION_STREAM_EN_OFFSET 0
#define FUSION_STREAM_EN_BITS 1
#define FUSION_STREAM_EN_MASK (((1 << 1) - 1) << 0)
/* FUSION_STREAM_CTRL 0x0108 */
#define FUSION_BURST_LENGTH_SEL_RD_OFFSET 1
#define FUSION_BURST_LENGTH_SEL_RD_BITS 1
#define FUSION_BURST_LENGTH_SEL_RD_MASK (((1 << 1) - 1) << 1)
#define FUSION_DATA_REQ_EN_OFFSET 2
#define FUSION_DATA_REQ_EN_BITS 1
#define FUSION_DATA_REQ_EN_MASK (((1 << 1) - 1) << 2)
/* FUSION_STREAM_FRAME_ADDR 0x010c */
#define FUSION_FRAME_ADDR_OFFSET 4
#define FUSION_FRAME_ADDR_BITS 28
#define FUSION_FRAME_ADDR_MASK (((1 << 28) - 1) << 4)
/* FUSION_STREAM_DDR_LEN 0x0110 */
#define FUSION_DDR_LEN_OFFSET 4
#define FUSION_DDR_LEN_BITS 20
#define FUSION_DDR_LEN_MASK (((1 << 20) - 1) << 0)
/* FUSION_STREAM_START_LINENUM 0x0110 */
#define FUSION_STREAM_START_LINENUM_OFFSET 0
#define FUSION_STREAM_START_LINENUM_BITS 8
#define FUSION_STREAM_START_LINENUM_MASK (((1 << 8) - 1) << 0)
/* FUSION_STREAM_CTRL2 0x0118 */
#define FUSION_CFG_LENGTH_FRAME_END_CLR_EN_OFFSET 0
#define FUSION_CFG_LENGTH_FRAME_END_CLR_EN_BITS 1
#define FUSION_CFG_LENGTH_FRAME_END_CLR_EN_MASK (((1 << 1) - 1) << 0)
#define FUSION_CFG_UNDERFLOW_FRAME_START_EN_OFFSET 1
#define FUSION_CFG_UNDERFLOW_FRAME_START_EN_BITS 1
#define FUSION_CFG_UNDERFLOW_FRAME_START_EN_MASK (((1 << 1) - 1) << 1)
/* FUSION_REG_LOAD 0x0200 */
#define FUSION_REG_LOAD_OFFSET 0
#define FUSION_REG_LOAD_BITS 1
#define FUSION_REG_LOAD_MASK (((1 << 1) - 1) << 0)

#endif /* _ISP_REG_FUSION_H_INC_ */

