#ifndef _ISP_REG_STATIS_H_INC_
#define _ISP_REG_STATIS_H_INC_

#include <isp_reg.h>
#include <isp_reg_base.h>

#define STATIS_CTRL (STATIS_REG_BASE + 0x0000)
#define STATIS_RST (STATIS_REG_BASE + 0x0004)
#define STATIS_BURST_LEN (STATIS_REG_BASE + 0x0008)
#define STATIS_DDR_ADDR (STATIS_REG_BASE + 0x000C)
#define STATIS_DDR_LEN (STATIS_REG_BASE + 0x0010)
#define STATIS_BUFF_SIZE (STATIS_REG_BASE + 0x0014)
#define STATIS_PIX_CNT (STATIS_REG_BASE + 0x0018)
#define STATIS_STATUS (STATIS_REG_BASE + 0x001C)
#define STATIS_BLOCK_EN (STATIS_REG_BASE + 0x0020)
#define STATIS_DMA_STATE (STATIS_REG_BASE + 0x0024)

/* STATIS_CTRL 0x0000 */
#define AEAWBAF_EN_OFFSET 0
#define AEAWBAF_EN_BITS 1
#define AEAWBAF_EN_MASK (((1 << 1) - 1) << 0)
/* STATIS_RST 0x0004 */
#define AEAWBAF_RST_OFFSET 0
#define AEAWBAF_RST_BITS 1
#define AEAWBAF_RST_MASK (((1 << 1) - 1) << 0)
/* STATIS_BURST_LEN 0x0008 */
#define BURST_LENGTH_SEL_AEAWBAF_OFFSET 0
#define BURST_LENGTH_SEL_AEAWBAF_BITS 1
#define BURST_LENGTH_SEL_AEAWBAF_MASK (((1 << 1) - 1) << 0)
/* STATIS_DDR_ADDR 0x000C */
#define FRAME_ADDR_AEAWBAF_OFFSET 4
#define FRAME_ADDR_AEAWBAF_BITS 28
#define FRAME_ADDR_AEAWBAF_MASK (((1 << 28) - 1) << 4)
/* STATIS_DDR_LEN 0x0010 */
#define DDR_LEN_AEAWBAF_OFFSET 4
#define DDR_LEN_AEAWBAF_BITS 20
#define DDR_LEN_AEAWBAF_MASK (((1 << 20) - 1) << 4)
/* STATIS_BUFF_SIZE 0x0014 */
#define BUF_SIZE_AEAWBAF_OFFSET 4
#define BUF_SIZE_AEAWBAF_BITS 12
#define BUF_SIZE_AEAWBAF_MASK (((1 << 12) - 1) << 4)
#define BUF_START_ADDR_AEAWBAF_OFFSET 20
#define BUF_START_ADDR_AEAWBAF_BITS 11
#define BUF_START_ADDR_AEAWBAF_MASK (((1 << 11) - 1) << 20)
/* STATIS_PIX_CNT 0x0018 */
#define PIX_CNT_AEAWBAF_OFFSET 0
#define PIX_CNT_AEAWBAF_BITS 20
#define PIX_CNT_AEAWBAF_MASK (((1 << 20) - 1) << 0)
/* STATIS_STATUS 0x001C */
#define DDR_OVERFLOW_CLR_OFFSET 0
#define DDR_OVERFLOW_CLR_BITS 1
#define DDR_OVERFLOW_CLR_MASK (((1 << 1) - 1) << 0)
#define BUF_OVERFLOW_CLR_OFFSET 1
#define BUF_OVERFLOW_CLR_BITS 1
#define BUF_OVERFLOW_CLR_MASK (((1 << 1) - 1) << 1)
/* STATIS_BLOCK_EN 0x0020 */
#define RAW_STATIS_EN_OFFSET 0
#define RAW_STATIS_EN_BITS 1
#define RAW_STATIS_EN_MASK (((1 << 1) - 1) << 0)
#define AWB_STATIS_EN_OFFSET 1
#define AWB_STATIS_EN_BITS 1
#define AWB_STATIS_EN_MASK (((1 << 1) - 1) << 1)
#define AE_STATIS_EN_OFFSET 2
#define AE_STATIS_EN_BITS 1
#define AE_STATIS_EN_MASK (((1 << 1) - 1) << 2)
#define Y_STATIS_EN_OFFSET 3
#define Y_STATIS_EN_BITS 1
#define Y_STATIS_EN_MASK (((1 << 1) - 1) << 3)
#define AF_STATIS_EN_OFFSET 4
#define AF_STATIS_EN_BITS 1
#define AF_STATIS_EN_MASK (((1 << 1) - 1) << 4)
#define AE0_STATIS_EN_OFFSET 5							/*Short Exp. Path (2DNR)*/
#define AE0_STATIS_EN_BITS 1
#define AE0_STATIS_EN_MASK (((1 << 1) - 1) << 5)
#define AE1_STATIS_EN_OFFSET 6							/*Long Exp. Path (3DNR)*/
#define AE1_STATIS_EN_BITS 1
#define AE1_STATIS_EN_MASK (((1 << 1) - 1) << 6)
/* STATIS_DMA_STATE 0x0024 */
#define RAW_CONFLICT_CLR_OFFSET 0
#define RAW_CONFLICT_CLR_BITS 1
#define RAW_CONFLICT_CLR_MASK (((1 << 1) - 1) << 0)
#define AWB_CONFLICT_CLR_OFFSET 1
#define AWB_CONFLICT_CLR_BITS 1
#define AWB_CONFLICT_CLR_MASK (((1 << 1) - 1) << 1)
#define AE_CONFLICT_CLR_OFFSET 2
#define AE_CONFLICT_CLR_BITS 1
#define AE_CONFLICT_CLR_MASK (((1 << 1) - 1) << 2)
#define Y_CONFLICT_CLR_OFFSET 3
#define Y_CONFLICT_CLR_BITS 1
#define Y_CONFLICT_CLR_MASK (((1 << 1) - 1) << 3)
#define AF_CONFLICT_CLR_OFFSET 4
#define AF_CONFLICT_CLR_BITS 1
#define AF_CONFLICT_CLR_MASK (((1 << 1) - 1) << 4)

#endif /* _ISP_REG_STATIS_H_INC_ */

