#ifndef _ISP_REG_DEHAZE_H_INC_
#define _ISP_REG_DEHAZE_H_INC_

#include <isp_reg.h>
#include <isp_reg_base.h>

#define DEHAZE_FUNC_EN (DEHAZE_REG_BASE + 0x0004)
#define DEHAZE_STATUS (DEHAZE_REG_BASE + 0x0008)
#define DEHAZE_SUBEN (DEHAZE_REG_BASE + 0x000C)
#define DEHAZE_CURVEBLEND_STEP (DEHAZE_REG_BASE + 0x0010)
#define DEHAZE_STORE_BLOCK_CFG (DEHAZE_REG_BASE + 0x0014)
#define DEHAZE_STORE_MEAN_DIVIDE_PARAMETER (DEHAZE_REG_BASE + 0x0018)
#define DEHAZE_STORE_Y_PARAMETER (DEHAZE_REG_BASE + 0x001C)
#define DEHAZE_STORE_SAMPLE_CFG (DEHAZE_REG_BASE + 0x0020)
#define DEHAZE_IPAIR_HAZE_THD (DEHAZE_REG_BASE + 0x0024)
#define DEHAZE_IPAIR_PHASE1_MULT_PARAM (DEHAZE_REG_BASE + 0x0028)
#define DEHAZE_IPAIR_PHASE3_MULT_PARAM_L (DEHAZE_REG_BASE + 0x002C)
#define DEHAZE_HISTO_SUM (DEHAZE_REG_BASE + 0x0030)
#define DEHAZE_HISTO_LIMIT_FACTOR (DEHAZE_REG_BASE + 0x0034)
#define DEHAZE_CURVE_NORMALIZE_FACTOR (DEHAZE_REG_BASE + 0x0038)
#define DEHAZE_CURVE_OLD_FLAG (DEHAZE_REG_BASE + 0x003C)
#define DEHAZE_INTERRUPT_EN (DEHAZE_REG_BASE + 0x0040)
#define DEHAZE_INTERRUPT_FLAG (DEHAZE_REG_BASE + 0x0044)
#define DEHAZE_LEVEL_CTRL (DEHAZE_REG_BASE + 0x0048)
#define DEHAZE_LEVEL_STEP (DEHAZE_REG_BASE + 0x004C)
#define DEHAZE_BLEND_TH (DEHAZE_REG_BASE + 0x0050)
#define DEHAZE_BLEND_HAZE_K (DEHAZE_REG_BASE + 0x0054)
#define DEHAZE_LOC_CFG (DEHAZE_REG_BASE + 0x0058)
#define DEHAZE_DARK_MEAN_WIN (DEHAZE_REG_BASE + 0x005C)
#define DEHAZE_DARK_MEAN_PARAM (DEHAZE_REG_BASE + 0x0060)
#define DEHAZE_GRADIENT_WIN (DEHAZE_REG_BASE + 0x0064)
#define DEHAZE_GRADIENT_MEAN_PARAM (DEHAZE_REG_BASE + 0x0068)
#define DEHAZE_Y_CHANNEL_MAX (DEHAZE_REG_BASE + 0x006C)
#define DEHAZE_GRADIENT_MEAN (DEHAZE_REG_BASE + 0x0070)
#define DEHAZE_AUTO_ENABLE (DEHAZE_REG_BASE + 0x0074)

/* DEHAZE_FUNC_EN 0x0004 */
#define DEHAZE_PARTONE_START_OFFSET 0
#define DEHAZE_PARTONE_START_BITS 1
#define DEHAZE_PARTONE_START_MASK (((1 << 1) - 1) << 0)
#define DEHAZE_PARTTWO_START_OFFSET 1
#define DEHAZE_PARTTWO_START_BITS 1
#define DEHAZE_PARTTWO_START_MASK (((1 << 1) - 1) << 1)
#define AUTO_LIMIT_MAX_EN_OFFSET 2
#define AUTO_LIMIT_MAX_EN_BITS 1
#define AUTO_LIMIT_MAX_EN_MASK (((1 << 1) - 1) << 2)
#define CURVE_AFTER_REFINE_EN_OFFSET 3
#define CURVE_AFTER_REFINE_EN_BITS 1
#define CURVE_AFTER_REFINE_EN_MASK (((1 << 1) - 1) << 3)
#define DEHAZE_BLENDING_EN_OFFSET 4
#define DEHAZE_BLENDING_EN_BITS 1
#define DEHAZE_BLENDING_EN_MASK (((1 << 1) - 1) << 4)
#define DEHAZE_LOC_EN_OFFSET 5
#define DEHAZE_LOC_EN_BITS 1
#define DEHAZE_LOC_EN_MASK (((1 << 1) - 1) << 5)
#define FRAME_STORE_SEL_OFFSET 6
#define FRAME_STORE_SEL_BITS 1
#define FRAME_STORE_SEL_MASK (((1 << 1) - 1) << 6)
/* DEHAZE_STATUS 0x0008 */
#define HISTO_INIT_RUN_PRE_OFFSET 0
#define HISTO_INIT_RUN_PRE_BITS 1
#define HISTO_INIT_RUN_PRE_MASK (((1 << 1) - 1) << 0)
#define HISTO_STATIS_RUN_PRE_OFFSET 1
#define HISTO_STATIS_RUN_PRE_BITS 1
#define HISTO_STATIS_RUN_PRE_MASK (((1 << 1) - 1) << 1)
#define HISTO_REFINE_RUN_PRE_OFFSET 2
#define HISTO_REFINE_RUN_PRE_BITS 1
#define HISTO_REFINE_RUN_PRE_MASK (((1 << 1) - 1) << 2)
#define CURVE_NORMALIZE_RUN_PRE_OFFSET 3
#define CURVE_NORMALIZE_RUN_PRE_BITS 1
#define CURVE_NORMALIZE_RUN_PRE_MASK (((1 << 1) - 1) << 3)
#define CURVE_BACKFILL_RUN_PRE_OFFSET 4
#define CURVE_BACKFILL_RUN_PRE_BITS 1
#define CURVE_BACKFILL_RUN_PRE_MASK (((1 << 1) - 1) << 4)
#define DEHAZE_IPAIR_RUN_OFFSET 5
#define DEHAZE_IPAIR_RUN_BITS 1
#define DEHAZE_IPAIR_RUN_MASK (((1 << 1) - 1) << 5)
#define DEHAZE_UPDATE_RUN_OFFSET 6
#define DEHAZE_UPDATE_RUN_BITS 1
#define DEHAZE_UPDATE_RUN_MASK (((1 << 1) - 1) << 6)
/* DEHAZE_SUBEN 0x000C */
#define PREFRAME_STORE_EN_OFFSET 0
#define PREFRAME_STORE_EN_BITS 1
#define PREFRAME_STORE_EN_MASK (((1 << 1) - 1) << 0)
#define DEHAZE_IPAIR_EN_OFFSET 1
#define DEHAZE_IPAIR_EN_BITS 1
#define DEHAZE_IPAIR_EN_MASK (((1 << 1) - 1) << 1)
#define HISTO_LIMIT_EN_OFFSET 2
#define HISTO_LIMIT_EN_BITS 1
#define HISTO_LIMIT_EN_MASK (((1 << 1) - 1) << 2)
#define HISTO_SMOOTH_EN_OFFSET 3
#define HISTO_SMOOTH_EN_BITS 1
#define HISTO_SMOOTH_EN_MASK (((1 << 1) - 1) << 3)
#define HISTO_MEMINIT_EN_OFFSET 4
#define HISTO_MEMINIT_EN_BITS 1
#define HISTO_MEMINIT_EN_MASK (((1 << 1) - 1) << 4)
#define CURVE_AVILIABLE_OFFSET 5
#define CURVE_AVILIABLE_BITS 1
#define CURVE_AVILIABLE_MASK (((1 << 1) - 1) << 5)
/* DEHAZE_CURVEBLEND_STEP 0x0010 */
#define REGF_CURVEBLEND_STEP_OFFSET 0
#define REGF_CURVEBLEND_STEP_BITS 8
#define REGF_CURVEBLEND_STEP_MASK (((1 << 8) - 1) << 0)
#define FORCE_CURVE_MODE_OFFSET 8
#define FORCE_CURVE_MODE_BITS 1
#define FORCE_CURVE_MODE_MASK (((1 << 1) - 1) << 8)
/* DEHAZE_STORE_BLOCK_CFG 0x0014 */
#define REGF_BLOCK_WIDTH_OFFSET 0
#define REGF_BLOCK_WIDTH_BITS 8
#define REGF_BLOCK_WIDTH_MASK (((1 << 8) - 1) << 0)
#define REGF_BLOCK_HEIGHT_OFFSET 8
#define REGF_BLOCK_HEIGHT_BITS 8
#define REGF_BLOCK_HEIGHT_MASK (((1 << 8) - 1) << 8)
#define REGF_BLOCK_COL_NUM_OFFSET 16
#define REGF_BLOCK_COL_NUM_BITS 8
#define REGF_BLOCK_COL_NUM_MASK (((1 << 8) - 1) << 16)
#define REGF_BLOCK_LINE_NUM_OFFSET 24
#define REGF_BLOCK_LINE_NUM_BITS 8
#define REGF_BLOCK_LINE_NUM_MASK (((1 << 8) - 1) << 24)
/* DEHAZE_STORE_MEAN_DIVIDE_PARAMETER 0x0018 */
#define REGF_DIV_PARAM_OFFSET 0
#define REGF_DIV_PARAM_BITS 16
#define REGF_DIV_PARAM_MASK (((1 << 16) - 1) << 0)
/* DEHAZE_STORE_Y_PARAMETER 0x001C */
#define REGF_MULT_R_OFFSET 0
#define REGF_MULT_R_BITS 4
#define REGF_MULT_R_MASK (((1 << 4) - 1) << 0)
#define REGF_MULT_G_OFFSET 8
#define REGF_MULT_G_BITS 4
#define REGF_MULT_G_MASK (((1 << 4) - 1) << 8)
#define REGF_MULT_B_OFFSET 16
#define REGF_MULT_B_BITS 4
#define REGF_MULT_B_MASK (((1 << 4) - 1) << 16)
/* DEHAZE_STORE_SAMPLE_CFG 0x0020 */
#define REGF_DEHAZE_SAMPLEH_OFFSET 0
#define REGF_DEHAZE_SAMPLEH_BITS 7
#define REGF_DEHAZE_SAMPLEH_MASK (((1 << 7) - 1) << 0)
#define REGF_DEHAZE_SAMPLEV_OFFSET 8
#define REGF_DEHAZE_SAMPLEV_BITS 7
#define REGF_DEHAZE_SAMPLEV_MASK (((1 << 7) - 1) << 8)
/* DEHAZE_IPAIR_HAZE_THD 0x0024 */
#define REGF_HAZE_THD1_OFFSET 0
#define REGF_HAZE_THD1_BITS 8
#define REGF_HAZE_THD1_MASK (((1 << 8) - 1) << 0)
#define REGF_HAZE_THD2_OFFSET 8
#define REGF_HAZE_THD2_BITS 8
#define REGF_HAZE_THD2_MASK (((1 << 8) - 1) << 8)
#define REGF_VOTE_THD2_OFFSET 16
#define REGF_VOTE_THD2_BITS 5
#define REGF_VOTE_THD2_MASK (((1 << 5) - 1) << 16)
/* DEHAZE_IPAIR_PHASE1_MULT_PARAM 0x0028 */
#define REGF_PHASE1_PARAM_OFFSET 0
#define REGF_PHASE1_PARAM_BITS 8
#define REGF_PHASE1_PARAM_MASK (((1 << 8) - 1) << 0)
#define REGF_PHASE1_B_OFFSET 8
#define REGF_PHASE1_B_BITS 5
#define REGF_PHASE1_B_MASK (((1 << 5) - 1) << 8)
/* DEHAZE_IPAIR_PHASE3_MULT_PARAM_L 0x002C */
#define REGF_PHASE3_PARAM_OFFSET 0
#define REGF_PHASE3_PARAM_BITS 8
#define REGF_PHASE3_PARAM_MASK (((1 << 8) - 1) << 0)
/* DEHAZE_HISTO_SUM 0x0030 */
#define HISTO_SUM_OFFSET 0
#define HISTO_SUM_BITS 24
#define HISTO_SUM_MASK (((1 << 24) - 1) << 0)
/* DEHAZE_HISTO_LIMIT_FACTOR 0x0034 */
#define HISTO_LIMIT_FACTOR_OFFSET 0
#define HISTO_LIMIT_FACTOR_BITS 8
#define HISTO_LIMIT_FACTOR_MASK (((1 << 8) - 1) << 0)
#define HISTO_LIMIT_MAX_OFFSET 8
#define HISTO_LIMIT_MAX_BITS 16
#define HISTO_LIMIT_MAX_MASK (((1 << 16) - 1) << 8)
/* DEHAZE_CURVE_NORMALIZE_FACTOR 0x0038 */
#define CURVE_NORMALIZE_FACTOR_OFFSET 0
#define CURVE_NORMALIZE_FACTOR_BITS 24
#define CURVE_NORMALIZE_FACTOR_MASK (((1 << 24) - 1) << 0)
/* DEHAZE_CURVE_OLD_FLAG 0x003C */
#define CURVE_OLD_FLAG_OFFSET 0
#define CURVE_OLD_FLAG_BITS 1
#define CURVE_OLD_FLAG_MASK (((1 << 1) - 1) << 0)
/* DEHAZE_INTERRUPT_EN 0x0040 */
#define DEHAZE_PARTONE_DONE_INT_EN_OFFSET 0
#define DEHAZE_PARTONE_DONE_INT_EN_BITS 1
#define DEHAZE_PARTONE_DONE_INT_EN_MASK (((1 << 1) - 1) << 0)
#define DEHAZE_PARTTWO_DONE_INT_EN_OFFSET 1
#define DEHAZE_PARTTWO_DONE_INT_EN_BITS 1
#define DEHAZE_PARTTWO_DONE_INT_EN_MASK (((1 << 1) - 1) << 1)
#define DEHAZE_CURVEBLEND_DONE_INT_EN_OFFSET 2
#define DEHAZE_CURVEBLEND_DONE_INT_EN_BITS 1
#define DEHAZE_CURVEBLEND_DONE_INT_EN_MASK (((1 << 1) - 1) << 2)
/* DEHAZE_INTERRUPT_FLAG 0x0044 */
#define DEHAZE_PARTONE_DONE_INT_CLR_OFFSET 0
#define DEHAZE_PARTONE_DONE_INT_CLR_BITS 1
#define DEHAZE_PARTONE_DONE_INT_CLR_MASK (((1 << 1) - 1) << 0)
#define DEHAZE_PARTTWO_DONE_INT_CLR_OFFSET 1
#define DEHAZE_PARTTWO_DONE_INT_CLR_BITS 1
#define DEHAZE_PARTTWO_DONE_INT_CLR_MASK (((1 << 1) - 1) << 1)
#define DEHAZE_CURVEBLEND_DONE_INT_CLR_OFFSET 2
#define DEHAZE_CURVEBLEND_DONE_INT_CLR_BITS 1
#define DEHAZE_CURVEBLEND_DONE_INT_CLR_MASK (((1 << 1) - 1) << 2)
/* DEHAZE_LEVEL_CTRL 0x0048 */
#define FORCE_DEHAZE_LEVEL_OFFSET 0
#define FORCE_DEHAZE_LEVEL_BITS 1
#define FORCE_DEHAZE_LEVEL_MASK (((1 << 1) - 1) << 0)
#define DEHAZE_LEVEL_UPDATE_OFFSET 1
#define DEHAZE_LEVEL_UPDATE_BITS 1
#define DEHAZE_LEVEL_UPDATE_MASK (((1 << 1) - 1) << 1)
/* DEHAZE_LEVEL_STEP 0x004C */
#define REGF_DEHAZE_LEVEL_OFFSET 0
#define REGF_DEHAZE_LEVEL_BITS 8
#define REGF_DEHAZE_LEVEL_MASK (((1 << 8) - 1) << 0)
#define REGF_DEHAZE_LEVEL_STEP_OFFSET 8
#define REGF_DEHAZE_LEVEL_STEP_BITS 8
#define REGF_DEHAZE_LEVEL_STEP_MASK (((1 << 8) - 1) << 8)
/* DEHAZE_BLEND_TH 0x0050 */
#define REGF_BLEND_HAZE_THD1_OFFSET 0
#define REGF_BLEND_HAZE_THD1_BITS 8
#define REGF_BLEND_HAZE_THD1_MASK (((1 << 8) - 1) << 0)
#define REGF_BLEND_HAZE_THD2_OFFSET 8
#define REGF_BLEND_HAZE_THD2_BITS 8
#define REGF_BLEND_HAZE_THD2_MASK (((1 << 8) - 1) << 8)
#define REGF_BLEND_WEIGHT_THD2_OFFSET 16
#define REGF_BLEND_WEIGHT_THD2_BITS 9
#define REGF_BLEND_WEIGHT_THD2_MASK (((1 << 9) - 1) << 16)
/* DEHAZE_BLEND_HAZE_K 0x0054 */
#define REGF_BLEND_HAZE_K1_OFFSET 0
#define REGF_BLEND_HAZE_K1_BITS 12
#define REGF_BLEND_HAZE_K1_MASK (((1 << 12) - 1) << 0)
#define REGF_BLEND_HAZE_K2_OFFSET 16
#define REGF_BLEND_HAZE_K2_BITS 12
#define REGF_BLEND_HAZE_K2_MASK (((1 << 12) - 1) << 16)
/* DEHAZE_LOC_CFG 0x0058 */
#define REGF_DEHAZE_LOC_DIR_OFFSET 0
#define REGF_DEHAZE_LOC_DIR_BITS 2
#define REGF_DEHAZE_LOC_DIR_MASK (((1 << 2) - 1) << 0)
#define REGF_DEHAZE_LOC_MIN_OFFSET 8
#define REGF_DEHAZE_LOC_MIN_BITS 6
#define REGF_DEHAZE_LOC_MIN_MASK (((1 << 6) - 1) << 8)
#define REGF_DEHAZE_LOC_K_OFFSET 16
#define REGF_DEHAZE_LOC_K_BITS 12
#define REGF_DEHAZE_LOC_K_MASK (((1 << 12) - 1) << 16)
/* DEHAZE_DARK_MEAN_WIN 0x005C */
#define REGF_DARK_MEAN_X_START_OFFSET 0
#define REGF_DARK_MEAN_X_START_BITS 6
#define REGF_DARK_MEAN_X_START_MASK (((1 << 6) - 1) << 0)
#define REGF_DARK_MEAN_X_END_OFFSET 8
#define REGF_DARK_MEAN_X_END_BITS 6
#define REGF_DARK_MEAN_X_END_MASK (((1 << 6) - 1) << 8)
#define REGF_DARK_MEAN_Y_START_OFFSET 16
#define REGF_DARK_MEAN_Y_START_BITS 5
#define REGF_DARK_MEAN_Y_START_MASK (((1 << 5) - 1) << 16)
#define REGF_DARK_MEAN_Y_END_OFFSET 24
#define REGF_DARK_MEAN_Y_END_BITS 5
#define REGF_DARK_MEAN_Y_END_MASK (((1 << 5) - 1) << 24)
/* DEHAZE_DARK_MEAN_PARAM 0x0060 */
#define REGF_DARK_MEAN_K_OFFSET 0
#define REGF_DARK_MEAN_K_BITS 8
#define REGF_DARK_MEAN_K_MASK (((1 << 8) - 1) << 0)
#define DARK_MEAN_OFFSET 8
#define DARK_MEAN_BITS 8
#define DARK_MEAN_MASK (((1 << 8) - 1) << 8)
/* DEHAZE_GRADIENT_WIN 0x0064 */
#define REGF_GRADIENT_MEAN_X_START_OFFSET 0
#define REGF_GRADIENT_MEAN_X_START_BITS 6
#define REGF_GRADIENT_MEAN_X_START_MASK (((1 << 6) - 1) << 0)
#define REGF_GRADIENT_MEAN_X_END_OFFSET 8
#define REGF_GRADIENT_MEAN_X_END_BITS 6
#define REGF_GRADIENT_MEAN_X_END_MASK (((1 << 6) - 1) << 8)
#define REGF_GRADIENT_MEAN_Y_START_OFFSET 16
#define REGF_GRADIENT_MEAN_Y_START_BITS 5
#define REGF_GRADIENT_MEAN_Y_START_MASK (((1 << 5) - 1) << 16)
#define REGF_GRADIENT_MEAN_Y_END_OFFSET 24
#define REGF_GRADIENT_MEAN_Y_END_BITS 5
#define REGF_GRADIENT_MEAN_Y_END_MASK (((1 << 5) - 1) << 24)
/* DEHAZE_GRADIENT_MEAN_PARAM 0x0068 */
#define REGF_GRADIENT_MEAN_K_OFFSET 0
#define REGF_GRADIENT_MEAN_K_BITS 8
#define REGF_GRADIENT_MEAN_K_MASK (((1 << 8) - 1) << 0)
#define GRADIENT_MEAN_OFFSET 8
#define GRADIENT_MEAN_BITS 8
#define GRADIENT_MEAN_MASK (((1 << 8) - 1) << 8)
/* DEHAZE_Y_CHANNEL_MAX 0x006C */
#define Y_CHANNEL_MAX_OFFSET 0
#define Y_CHANNEL_MAX_BITS 8
#define Y_CHANNEL_MAX_MASK (((1 << 8) - 1) << 0)
/* DEHAZE_GRADIENT_MEAN 0x0070 */
#define MEM_INIT_VALUE_OFFSET 0
#define MEM_INIT_VALUE_BITS 16
#define MEM_INIT_VALUE_MASK (((1 << 16) - 1) << 0)
/* DEHAZE_AUTO_ENABLE 0x0074 */
#define AUTO_DEHAZE_EN_OFFSET 0
#define AUTO_DEHAZE_EN_BITS 1
#define AUTO_DEHAZE_EN_MASK (((1 << 1) - 1) << 0)

#endif /* _ISP_REG_DEHAZE_H_INC_ */

