#ifndef _ISP_REG_VIRTUAL_H_INC_
#define _ISP_REG_VIRTUAL_H_INC_

#include <isp_reg.h>
#include <isp_reg_base.h>

#define VINTP_NOISE_COFF0 (VIRTUAL_REG_BASE + 0x0000)
#define VINTP_NOISE_COFF_NUM 9
#define VINTP_ALPHA_BLEND_EDGE_THD0 (VIRTUAL_REG_BASE + 0x0024)
#define VINTP_ALPHA_BLEND_EDGE_THD1 (VIRTUAL_REG_BASE + 0x0028)
#define VSPE_Y_OFFSET (VIRTUAL_REG_BASE + 0x002C)
#define VSPE_Y_CONTRAST (VIRTUAL_REG_BASE + 0x0030)
#define VSPE_UV_GAIN (VIRTUAL_REG_BASE + 0x0034)
#define VWDR_LEVEL (VIRTUAL_REG_BASE + 0x0038)
#define VDEHAZE_LEVEL (VIRTUAL_REG_BASE + 0x003C)
#define VEEH_M_SUPPRESS (VIRTUAL_REG_BASE + 0x0040)
#define VEEH_SH_RATE0 (VIRTUAL_REG_BASE + 0x0044)
#define VEEH_SH_RATE1 (VIRTUAL_REG_BASE + 0x0048)
#define VCAC_SAT_THD0 (VIRTUAL_REG_BASE + 0x004C)
#define VCAC_SAT_THD1 (VIRTUAL_REG_BASE + 0x0050)
#define VDRC_AUTO_DISABLE (VIRTUAL_REG_BASE + 0x0054)
#define VDRC_RATE_CONFIG (VIRTUAL_REG_BASE + 0x0058)
#define VSHARPNESS (VIRTUAL_REG_BASE + 0x005C)
#define VSATURATION (VIRTUAL_REG_BASE + 0x0060)
#define VCONTRAST (VIRTUAL_REG_BASE + 0x0064)
#define VNR_LEVEL (VIRTUAL_REG_BASE + 0x0068)
#define VDE_LEVEL (VIRTUAL_REG_BASE + 0x006C)
#define VTM_TARGET (VIRTUAL_REG_BASE + 0x0070)
#define VSENSOR_MIRROR_FLIP (VIRTUAL_REG_BASE + 0x0074)
#define VSENSOR_MIRROR_MASK (1 << 0)
#define VSENSOR_FLIP_MASK (1 << 1)
#define VSENSOR_FLIP_OFFSET 1

#endif /* _ISP_REG_VIRTUAL_H_INC_ */
