#ifndef _ISP_REG_BLC_H_INC_
#define _ISP_REG_BLC_H_INC_

#include <isp_reg.h>
#include <isp_reg_base.h>

#define BLC_LE_OFFSET_GR (BLC_LONGEXP_REG_BASE + 0x0008)
#define BLC_LE_GAIN_GR (BLC_LONGEXP_REG_BASE + 0x000C)
#define BLC_LE_OFFSET_R (BLC_LONGEXP_REG_BASE + 0x0010)
#define BLC_LE_GAIN_R (BLC_LONGEXP_REG_BASE + 0x0014)
#define BLC_LE_OFFSET_B (BLC_LONGEXP_REG_BASE + 0x0018)
#define BLC_LE_GAIN_B (BLC_LONGEXP_REG_BASE + 0x001C)
#define BLC_LE_OFFSET_GB (BLC_LONGEXP_REG_BASE + 0x0020)
#define BLC_LE_GAIN_GB (BLC_LONGEXP_REG_BASE + 0x0024)
#define BLC_LE_SYNC (BLC_LONGEXP_REG_BASE + 0x0028)

#define BLC_SE_OFFSET_GR (BLC_SHORTEXP_REG_BASE + 0x0008)
#define BLC_SE_GAIN_GR (BLC_SHORTEXP_REG_BASE + 0x000C)
#define BLC_SE_OFFSET_R (BLC_SHORTEXP_REG_BASE + 0x0010)
#define BLC_SE_GAIN_R (BLC_SHORTEXP_REG_BASE + 0x0014)
#define BLC_SE_OFFSET_B (BLC_SHORTEXP_REG_BASE + 0x0018)
#define BLC_SE_GAIN_B (BLC_SHORTEXP_REG_BASE + 0x001C)
#define BLC_SE_OFFSET_GB (BLC_SHORTEXP_REG_BASE + 0x0020)
#define BLC_SE_GAIN_GB (BLC_SHORTEXP_REG_BASE + 0x0024)
#define BLC_SE_SYNC (BLC_SHORTEXP_REG_BASE + 0x0028)

/* BLC_OFFSET_GR 0x0008 */
#define BLC_OFFSET_G1_OFFSET 0
#define BLC_OFFSET_G1_BITS 10
#define BLC_OFFSET_G1_MASK (((1 << 10) - 1) << 0)
/* BLC_GAIN_GR 0x000C */
#define BLC_OFFSET_GAIN_G1_OFFSET 0
#define BLC_OFFSET_GAIN_G1_BITS 12
#define BLC_OFFSET_GAIN_G1_MASK (((1 << 12) - 1) << 0)
/* BLC_OFFSET_R 0x0010 */
#define BLC_OFFSET_R_OFFSET 0
#define BLC_OFFSET_R_BITS 10
#define BLC_OFFSET_R_MASK (((1 << 10) - 1) << 0)
/* BLC_GAIN_R 0x0014 */
#define BLC_OFFSET_GAIN_R_OFFSET 0
#define BLC_OFFSET_GAIN_R_BITS 12
#define BLC_OFFSET_GAIN_R_MASK (((1 << 12) - 1) << 0)
/* BLC_OFFSET_B 0x0018 */
#define BLC_OFFSET_B_OFFSET 0
#define BLC_OFFSET_B_BITS 10
#define BLC_OFFSET_B_MASK (((1 << 10) - 1) << 0)
/* BLC_GAIN_B 0x001C */
#define BLC_OFFSET_GAIN_B_OFFSET 0
#define BLC_OFFSET_GAIN_B_BITS 12
#define BLC_OFFSET_GAIN_B_MASK (((1 << 12) - 1) << 0)
/* BLC_OFFSET_GB 0x0020 */
#define BLC_OFFSET_G2_OFFSET 0
#define BLC_OFFSET_G2_BITS 10
#define BLC_OFFSET_G2_MASK (((1 << 10) - 1) << 0)
/* BLC_GAIN_GB 0x0024 */
#define BLC_OFFSET_GAIN_G2_OFFSET 0
#define BLC_OFFSET_GAIN_G2_BITS 12
#define BLC_OFFSET_GAIN_G2_MASK (((1 << 12) - 1) << 0)
/* BLC_SYNC 0x0028 */
#define BLC_REGISTER_LOAD_OFFSET 0
#define BLC_REGISTER_LOAD_BITS 1
#define BLC_REGISTER_LOAD_MASK (((1 << 1) - 1) << 0)

#endif /* _ISP_REG_BLC_H_INC_ */

