/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.5 */

#include "isp_algo_param.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(isp_algo_param_header_t, isp_algo_param_header_t, AUTO)


PB_BIND(isp_algo_param_ae_t, isp_algo_param_ae_t, AUTO)


PB_BIND(isp_algo_point_t, isp_algo_point_t, AUTO)


PB_BIND(isp_algo_param_awb_t, isp_algo_param_awb_t, AUTO)


PB_BIND(isp_algo_param_flick_t, isp_algo_param_flick_t, AUTO)


PB_BIND(isp_algo_param_wdr_t, isp_algo_param_wdr_t, AUTO)


PB_BIND(isp_algo_param_blc_t, isp_algo_param_blc_t, AUTO)


PB_BIND(isp_algo_param_nlsc_t, isp_algo_param_nlsc_t, AUTO)


PB_BIND(isp_algo_param_ccm_t, isp_algo_param_ccm_t, AUTO)


PB_BIND(isp_algo_param_gamma_t, isp_algo_param_gamma_t, AUTO)


PB_BIND(isp_algo_param_ygc_t, isp_algo_param_ygc_t, AUTO)


PB_BIND(isp_algo_param_uvtune_t, isp_algo_param_uvtune_t, AUTO)


PB_BIND(isp_algo_param_spe_t, isp_algo_param_spe_t, AUTO)


PB_BIND(isp_algo_param_texture_t, isp_algo_param_texture_t, AUTO)


PB_BIND(isp_algo_param_high_temp_t, isp_algo_param_high_temp_t, AUTO)


PB_BIND(isp_algo_param_tm_t, isp_algo_param_tm_t, AUTO)


PB_BIND(isp_algo_param_snr_t, isp_algo_param_snr_t, AUTO)


PB_BIND(isp_algo_param_md_t, isp_algo_param_md_t, AUTO)


PB_BIND(isp_algo_param_t, isp_algo_param_t, 2)



