/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.5 */

#include "isp_statis.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(isp_statis_raw_t, isp_statis_raw_t, AUTO)


PB_BIND(isp_statis_awb_t, isp_statis_awb_t, 2)


PB_BIND(isp_statis_ae_hdr_t, isp_statis_ae_hdr_t, AUTO)


PB_BIND(isp_statis_ae_t, isp_statis_ae_t, AUTO)


PB_BIND(isp_statis_af_t, isp_statis_af_t, AUTO)


PB_BIND(isp_statis_flick_t, isp_statis_flick_t, AUTO)


PB_BIND(isp_statis_y_t, isp_statis_y_t, AUTO)


PB_BIND(isp_statis_t, isp_statis_t, 2)



