/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.5 */

#ifndef PB_ISP_ALGO_PARAM_PB_H_INCLUDED
#define PB_ISP_ALGO_PARAM_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _isp_algo_param_ae_t { 
    uint16_t y_mean; 
    float gain[2]; 
    float exposure[2]; 
    float over_ratio[2]; 
    uint32_t hist_mean[2]; 
    uint8_t is_stable[2]; 
    float saturated_ratio; 
    bool ae_ctrl_force; 
    uint8_t sort_gain_index; 
    uint32_t ratio_range_index; 
    uint32_t cur_fast_ae_count; 
    uint32_t cur_y_target; 
    float cur_dyn_fps; 
    uint8_t cur_drc_region; 
} isp_algo_param_ae_t;

typedef struct _isp_algo_param_blc_t { 
    uint8_t ct_index; 
    uint8_t gain_index; 
    uint8_t ht_index; 
} isp_algo_param_blc_t;

typedef struct _isp_algo_param_ccm_t { 
    uint8_t ct_index; 
    uint8_t gain_index; 
    uint8_t ht_index; 
} isp_algo_param_ccm_t;

typedef struct _isp_algo_param_flick_t { 
    uint16_t insert_dummy_line; 
    uint32_t cur_freq; 
} isp_algo_param_flick_t;

typedef struct _isp_algo_param_gamma_t { 
    uint8_t ratio_index; 
    uint8_t gain_index; 
    uint8_t ht_index; 
} isp_algo_param_gamma_t;

typedef struct _isp_algo_param_header_t { 
    uint32_t magic; 
    uint32_t version; 
} isp_algo_param_header_t;

typedef struct _isp_algo_param_high_temp_t { 
    bool high_temp_en; 
} isp_algo_param_high_temp_t;

typedef struct _isp_algo_param_md_t { 
    uint16_t md_val; 
    uint8_t gain_index; 
} isp_algo_param_md_t;

typedef struct _isp_algo_param_nlsc_t { 
    uint8_t ct_index; 
    uint8_t gain_index; 
} isp_algo_param_nlsc_t;

typedef struct _isp_algo_param_snr_t { 
    uint8_t gain_index; 
} isp_algo_param_snr_t;

typedef struct _isp_algo_param_spe_t { 
    uint8_t ct_index; 
} isp_algo_param_spe_t;

typedef struct _isp_algo_param_texture_t { 
    uint8_t ratio_index; 
    uint8_t gain_index; 
} isp_algo_param_texture_t;

typedef struct _isp_algo_param_tm_t { 
    uint8_t gain_index; 
    uint8_t ht_index; 
} isp_algo_param_tm_t;

typedef struct _isp_algo_param_uvtune_t { 
    uint8_t ct_index; 
    uint8_t gain_index; 
} isp_algo_param_uvtune_t;

typedef struct _isp_algo_param_wdr_t { 
    uint32_t day_night; 
    uint8_t low_bound; 
    uint8_t wdr_level; 
    uint32_t hist_contrast_origin; 
    uint32_t hist_contrast; 
} isp_algo_param_wdr_t;

typedef struct _isp_algo_param_ygc_t { 
    uint8_t ratio_index; 
    uint8_t gain_index; 
    uint8_t ht_index; 
} isp_algo_param_ygc_t;

typedef struct _isp_algo_point_t { 
    uint16_t x; 
    uint16_t y; 
} isp_algo_point_t;

typedef struct _isp_algo_param_awb_t { 
    isp_algo_point_t gray_gain; 
    isp_algo_point_t green_gain; 
    isp_algo_point_t rough_gain; 
    isp_algo_point_t result_gain; 
    uint32_t color_temperature; 
    bool awb_ctrl_force; 
    uint8_t adj_ct_index; 
    uint8_t adj_gain_index; 
    uint32_t white_num; 
    uint32_t rg_sum; 
    uint32_t bg_sum; 
} isp_algo_param_awb_t;

typedef struct _isp_algo_param_t { 
    isp_algo_param_header_t header; 
    isp_algo_param_ae_t ae; 
    isp_algo_param_awb_t awb; 
    isp_algo_param_flick_t flick; 
    isp_algo_param_wdr_t wdr; 
    isp_algo_param_blc_t blc; 
    isp_algo_param_nlsc_t nlsc; 
    isp_algo_param_ccm_t ccm; 
    isp_algo_param_gamma_t gamma; 
    isp_algo_param_ygc_t ygc; 
    isp_algo_param_uvtune_t uvtune; 
    isp_algo_param_spe_t spe; 
    isp_algo_param_texture_t texture; 
    isp_algo_param_high_temp_t high_temp; 
    isp_algo_param_tm_t tm; 
    isp_algo_param_snr_t snr; 
    isp_algo_param_md_t md; 
} isp_algo_param_t;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define isp_algo_param_header_t_init_default     {0, 0}
#define isp_algo_param_ae_t_init_default         {0, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, 0, 0, 0, 0, 0, 0, 0, 0}
#define isp_algo_point_t_init_default            {0, 0}
#define isp_algo_param_awb_t_init_default        {isp_algo_point_t_init_default, isp_algo_point_t_init_default, isp_algo_point_t_init_default, isp_algo_point_t_init_default, 0, 0, 0, 0, 0, 0, 0}
#define isp_algo_param_flick_t_init_default      {0, 0}
#define isp_algo_param_wdr_t_init_default        {0, 0, 0, 0, 0}
#define isp_algo_param_blc_t_init_default        {0, 0, 0}
#define isp_algo_param_nlsc_t_init_default       {0, 0}
#define isp_algo_param_ccm_t_init_default        {0, 0, 0}
#define isp_algo_param_gamma_t_init_default      {0, 0, 0}
#define isp_algo_param_ygc_t_init_default        {0, 0, 0}
#define isp_algo_param_uvtune_t_init_default     {0, 0}
#define isp_algo_param_spe_t_init_default        {0}
#define isp_algo_param_texture_t_init_default    {0, 0}
#define isp_algo_param_high_temp_t_init_default  {0}
#define isp_algo_param_tm_t_init_default         {0, 0}
#define isp_algo_param_snr_t_init_default        {0}
#define isp_algo_param_md_t_init_default         {0, 0}
#define isp_algo_param_t_init_default            {isp_algo_param_header_t_init_default, isp_algo_param_ae_t_init_default, isp_algo_param_awb_t_init_default, isp_algo_param_flick_t_init_default, isp_algo_param_wdr_t_init_default, isp_algo_param_blc_t_init_default, isp_algo_param_nlsc_t_init_default, isp_algo_param_ccm_t_init_default, isp_algo_param_gamma_t_init_default, isp_algo_param_ygc_t_init_default, isp_algo_param_uvtune_t_init_default, isp_algo_param_spe_t_init_default, isp_algo_param_texture_t_init_default, isp_algo_param_high_temp_t_init_default, isp_algo_param_tm_t_init_default, isp_algo_param_snr_t_init_default, isp_algo_param_md_t_init_default}
#define isp_algo_param_header_t_init_zero        {0, 0}
#define isp_algo_param_ae_t_init_zero            {0, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, 0, 0, 0, 0, 0, 0, 0, 0}
#define isp_algo_point_t_init_zero               {0, 0}
#define isp_algo_param_awb_t_init_zero           {isp_algo_point_t_init_zero, isp_algo_point_t_init_zero, isp_algo_point_t_init_zero, isp_algo_point_t_init_zero, 0, 0, 0, 0, 0, 0, 0}
#define isp_algo_param_flick_t_init_zero         {0, 0}
#define isp_algo_param_wdr_t_init_zero           {0, 0, 0, 0, 0}
#define isp_algo_param_blc_t_init_zero           {0, 0, 0}
#define isp_algo_param_nlsc_t_init_zero          {0, 0}
#define isp_algo_param_ccm_t_init_zero           {0, 0, 0}
#define isp_algo_param_gamma_t_init_zero         {0, 0, 0}
#define isp_algo_param_ygc_t_init_zero           {0, 0, 0}
#define isp_algo_param_uvtune_t_init_zero        {0, 0}
#define isp_algo_param_spe_t_init_zero           {0}
#define isp_algo_param_texture_t_init_zero       {0, 0}
#define isp_algo_param_high_temp_t_init_zero     {0}
#define isp_algo_param_tm_t_init_zero            {0, 0}
#define isp_algo_param_snr_t_init_zero           {0}
#define isp_algo_param_md_t_init_zero            {0, 0}
#define isp_algo_param_t_init_zero               {isp_algo_param_header_t_init_zero, isp_algo_param_ae_t_init_zero, isp_algo_param_awb_t_init_zero, isp_algo_param_flick_t_init_zero, isp_algo_param_wdr_t_init_zero, isp_algo_param_blc_t_init_zero, isp_algo_param_nlsc_t_init_zero, isp_algo_param_ccm_t_init_zero, isp_algo_param_gamma_t_init_zero, isp_algo_param_ygc_t_init_zero, isp_algo_param_uvtune_t_init_zero, isp_algo_param_spe_t_init_zero, isp_algo_param_texture_t_init_zero, isp_algo_param_high_temp_t_init_zero, isp_algo_param_tm_t_init_zero, isp_algo_param_snr_t_init_zero, isp_algo_param_md_t_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define isp_algo_param_ae_t_y_mean_tag           1
#define isp_algo_param_ae_t_gain_tag             2
#define isp_algo_param_ae_t_exposure_tag         3
#define isp_algo_param_ae_t_over_ratio_tag       4
#define isp_algo_param_ae_t_hist_mean_tag        5
#define isp_algo_param_ae_t_is_stable_tag        6
#define isp_algo_param_ae_t_saturated_ratio_tag  7
#define isp_algo_param_ae_t_ae_ctrl_force_tag    8
#define isp_algo_param_ae_t_sort_gain_index_tag  9
#define isp_algo_param_ae_t_ratio_range_index_tag 10
#define isp_algo_param_ae_t_cur_fast_ae_count_tag 11
#define isp_algo_param_ae_t_cur_y_target_tag     12
#define isp_algo_param_ae_t_cur_dyn_fps_tag      13
#define isp_algo_param_ae_t_cur_drc_region_tag   14
#define isp_algo_param_blc_t_ct_index_tag        1
#define isp_algo_param_blc_t_gain_index_tag      2
#define isp_algo_param_blc_t_ht_index_tag        3
#define isp_algo_param_ccm_t_ct_index_tag        1
#define isp_algo_param_ccm_t_gain_index_tag      2
#define isp_algo_param_ccm_t_ht_index_tag        3
#define isp_algo_param_flick_t_insert_dummy_line_tag 1
#define isp_algo_param_flick_t_cur_freq_tag      2
#define isp_algo_param_gamma_t_ratio_index_tag   1
#define isp_algo_param_gamma_t_gain_index_tag    2
#define isp_algo_param_gamma_t_ht_index_tag      3
#define isp_algo_param_header_t_magic_tag        1
#define isp_algo_param_header_t_version_tag      2
#define isp_algo_param_high_temp_t_high_temp_en_tag 1
#define isp_algo_param_md_t_md_val_tag           1
#define isp_algo_param_md_t_gain_index_tag       2
#define isp_algo_param_nlsc_t_ct_index_tag       1
#define isp_algo_param_nlsc_t_gain_index_tag     2
#define isp_algo_param_snr_t_gain_index_tag      2
#define isp_algo_param_spe_t_ct_index_tag        1
#define isp_algo_param_texture_t_ratio_index_tag 1
#define isp_algo_param_texture_t_gain_index_tag  2
#define isp_algo_param_tm_t_gain_index_tag       2
#define isp_algo_param_tm_t_ht_index_tag         3
#define isp_algo_param_uvtune_t_ct_index_tag     1
#define isp_algo_param_uvtune_t_gain_index_tag   2
#define isp_algo_param_wdr_t_day_night_tag       1
#define isp_algo_param_wdr_t_low_bound_tag       2
#define isp_algo_param_wdr_t_wdr_level_tag       3
#define isp_algo_param_wdr_t_hist_contrast_origin_tag 4
#define isp_algo_param_wdr_t_hist_contrast_tag   5
#define isp_algo_param_ygc_t_ratio_index_tag     1
#define isp_algo_param_ygc_t_gain_index_tag      2
#define isp_algo_param_ygc_t_ht_index_tag        3
#define isp_algo_point_t_x_tag                   1
#define isp_algo_point_t_y_tag                   2
#define isp_algo_param_awb_t_gray_gain_tag       1
#define isp_algo_param_awb_t_green_gain_tag      2
#define isp_algo_param_awb_t_rough_gain_tag      3
#define isp_algo_param_awb_t_result_gain_tag     4
#define isp_algo_param_awb_t_color_temperature_tag 5
#define isp_algo_param_awb_t_awb_ctrl_force_tag  6
#define isp_algo_param_awb_t_adj_ct_index_tag    7
#define isp_algo_param_awb_t_adj_gain_index_tag  8
#define isp_algo_param_awb_t_white_num_tag       9
#define isp_algo_param_awb_t_rg_sum_tag          10
#define isp_algo_param_awb_t_bg_sum_tag          11
#define isp_algo_param_t_header_tag              1
#define isp_algo_param_t_ae_tag                  2
#define isp_algo_param_t_awb_tag                 3
#define isp_algo_param_t_flick_tag               4
#define isp_algo_param_t_wdr_tag                 5
#define isp_algo_param_t_blc_tag                 6
#define isp_algo_param_t_nlsc_tag                7
#define isp_algo_param_t_ccm_tag                 8
#define isp_algo_param_t_gamma_tag               9
#define isp_algo_param_t_ygc_tag                 10
#define isp_algo_param_t_uvtune_tag              11
#define isp_algo_param_t_spe_tag                 12
#define isp_algo_param_t_texture_tag             13
#define isp_algo_param_t_high_temp_tag           14
#define isp_algo_param_t_tm_tag                  15
#define isp_algo_param_t_snr_tag                 16
#define isp_algo_param_t_md_tag                  17

/* Struct field encoding specification for nanopb */
#define isp_algo_param_header_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   magic,             1) \
X(a, STATIC,   SINGULAR, UINT32,   version,           2)
#define isp_algo_param_header_t_CALLBACK NULL
#define isp_algo_param_header_t_DEFAULT NULL

#define isp_algo_param_ae_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   y_mean,            1) \
X(a, STATIC,   FIXARRAY, FLOAT,    gain,              2) \
X(a, STATIC,   FIXARRAY, FLOAT,    exposure,          3) \
X(a, STATIC,   FIXARRAY, FLOAT,    over_ratio,        4) \
X(a, STATIC,   FIXARRAY, UINT32,   hist_mean,         5) \
X(a, STATIC,   FIXARRAY, UINT32,   is_stable,         6) \
X(a, STATIC,   SINGULAR, FLOAT,    saturated_ratio,   7) \
X(a, STATIC,   SINGULAR, BOOL,     ae_ctrl_force,     8) \
X(a, STATIC,   SINGULAR, UINT32,   sort_gain_index,   9) \
X(a, STATIC,   SINGULAR, UINT32,   ratio_range_index,  10) \
X(a, STATIC,   SINGULAR, UINT32,   cur_fast_ae_count,  11) \
X(a, STATIC,   SINGULAR, UINT32,   cur_y_target,     12) \
X(a, STATIC,   SINGULAR, FLOAT,    cur_dyn_fps,      13) \
X(a, STATIC,   SINGULAR, UINT32,   cur_drc_region,   14)
#define isp_algo_param_ae_t_CALLBACK NULL
#define isp_algo_param_ae_t_DEFAULT NULL

#define isp_algo_point_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   x,                 1) \
X(a, STATIC,   SINGULAR, UINT32,   y,                 2)
#define isp_algo_point_t_CALLBACK NULL
#define isp_algo_point_t_DEFAULT NULL

#define isp_algo_param_awb_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, MESSAGE,  gray_gain,         1) \
X(a, STATIC,   SINGULAR, MESSAGE,  green_gain,        2) \
X(a, STATIC,   SINGULAR, MESSAGE,  rough_gain,        3) \
X(a, STATIC,   SINGULAR, MESSAGE,  result_gain,       4) \
X(a, STATIC,   SINGULAR, UINT32,   color_temperature,   5) \
X(a, STATIC,   SINGULAR, BOOL,     awb_ctrl_force,    6) \
X(a, STATIC,   SINGULAR, UINT32,   adj_ct_index,      7) \
X(a, STATIC,   SINGULAR, UINT32,   adj_gain_index,    8) \
X(a, STATIC,   SINGULAR, UINT32,   white_num,         9) \
X(a, STATIC,   SINGULAR, UINT32,   rg_sum,           10) \
X(a, STATIC,   SINGULAR, UINT32,   bg_sum,           11)
#define isp_algo_param_awb_t_CALLBACK NULL
#define isp_algo_param_awb_t_DEFAULT NULL
#define isp_algo_param_awb_t_gray_gain_MSGTYPE isp_algo_point_t
#define isp_algo_param_awb_t_green_gain_MSGTYPE isp_algo_point_t
#define isp_algo_param_awb_t_rough_gain_MSGTYPE isp_algo_point_t
#define isp_algo_param_awb_t_result_gain_MSGTYPE isp_algo_point_t

#define isp_algo_param_flick_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   insert_dummy_line,   1) \
X(a, STATIC,   SINGULAR, UINT32,   cur_freq,          2)
#define isp_algo_param_flick_t_CALLBACK NULL
#define isp_algo_param_flick_t_DEFAULT NULL

#define isp_algo_param_wdr_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   day_night,         1) \
X(a, STATIC,   SINGULAR, UINT32,   low_bound,         2) \
X(a, STATIC,   SINGULAR, UINT32,   wdr_level,         3) \
X(a, STATIC,   SINGULAR, UINT32,   hist_contrast_origin,   4) \
X(a, STATIC,   SINGULAR, UINT32,   hist_contrast,     5)
#define isp_algo_param_wdr_t_CALLBACK NULL
#define isp_algo_param_wdr_t_DEFAULT NULL

#define isp_algo_param_blc_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   ct_index,          1) \
X(a, STATIC,   SINGULAR, UINT32,   gain_index,        2) \
X(a, STATIC,   SINGULAR, UINT32,   ht_index,          3)
#define isp_algo_param_blc_t_CALLBACK NULL
#define isp_algo_param_blc_t_DEFAULT NULL

#define isp_algo_param_nlsc_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   ct_index,          1) \
X(a, STATIC,   SINGULAR, UINT32,   gain_index,        2)
#define isp_algo_param_nlsc_t_CALLBACK NULL
#define isp_algo_param_nlsc_t_DEFAULT NULL

#define isp_algo_param_ccm_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   ct_index,          1) \
X(a, STATIC,   SINGULAR, UINT32,   gain_index,        2) \
X(a, STATIC,   SINGULAR, UINT32,   ht_index,          3)
#define isp_algo_param_ccm_t_CALLBACK NULL
#define isp_algo_param_ccm_t_DEFAULT NULL

#define isp_algo_param_gamma_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   ratio_index,       1) \
X(a, STATIC,   SINGULAR, UINT32,   gain_index,        2) \
X(a, STATIC,   SINGULAR, UINT32,   ht_index,          3)
#define isp_algo_param_gamma_t_CALLBACK NULL
#define isp_algo_param_gamma_t_DEFAULT NULL

#define isp_algo_param_ygc_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   ratio_index,       1) \
X(a, STATIC,   SINGULAR, UINT32,   gain_index,        2) \
X(a, STATIC,   SINGULAR, UINT32,   ht_index,          3)
#define isp_algo_param_ygc_t_CALLBACK NULL
#define isp_algo_param_ygc_t_DEFAULT NULL

#define isp_algo_param_uvtune_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   ct_index,          1) \
X(a, STATIC,   SINGULAR, UINT32,   gain_index,        2)
#define isp_algo_param_uvtune_t_CALLBACK NULL
#define isp_algo_param_uvtune_t_DEFAULT NULL

#define isp_algo_param_spe_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   ct_index,          1)
#define isp_algo_param_spe_t_CALLBACK NULL
#define isp_algo_param_spe_t_DEFAULT NULL

#define isp_algo_param_texture_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   ratio_index,       1) \
X(a, STATIC,   SINGULAR, UINT32,   gain_index,        2)
#define isp_algo_param_texture_t_CALLBACK NULL
#define isp_algo_param_texture_t_DEFAULT NULL

#define isp_algo_param_high_temp_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     high_temp_en,      1)
#define isp_algo_param_high_temp_t_CALLBACK NULL
#define isp_algo_param_high_temp_t_DEFAULT NULL

#define isp_algo_param_tm_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   gain_index,        2) \
X(a, STATIC,   SINGULAR, UINT32,   ht_index,          3)
#define isp_algo_param_tm_t_CALLBACK NULL
#define isp_algo_param_tm_t_DEFAULT NULL

#define isp_algo_param_snr_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   gain_index,        2)
#define isp_algo_param_snr_t_CALLBACK NULL
#define isp_algo_param_snr_t_DEFAULT NULL

#define isp_algo_param_md_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   md_val,            1) \
X(a, STATIC,   SINGULAR, UINT32,   gain_index,        2)
#define isp_algo_param_md_t_CALLBACK NULL
#define isp_algo_param_md_t_DEFAULT NULL

#define isp_algo_param_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, MESSAGE,  header,            1) \
X(a, STATIC,   SINGULAR, MESSAGE,  ae,                2) \
X(a, STATIC,   SINGULAR, MESSAGE,  awb,               3) \
X(a, STATIC,   SINGULAR, MESSAGE,  flick,             4) \
X(a, STATIC,   SINGULAR, MESSAGE,  wdr,               5) \
X(a, STATIC,   SINGULAR, MESSAGE,  blc,               6) \
X(a, STATIC,   SINGULAR, MESSAGE,  nlsc,              7) \
X(a, STATIC,   SINGULAR, MESSAGE,  ccm,               8) \
X(a, STATIC,   SINGULAR, MESSAGE,  gamma,             9) \
X(a, STATIC,   SINGULAR, MESSAGE,  ygc,              10) \
X(a, STATIC,   SINGULAR, MESSAGE,  uvtune,           11) \
X(a, STATIC,   SINGULAR, MESSAGE,  spe,              12) \
X(a, STATIC,   SINGULAR, MESSAGE,  texture,          13) \
X(a, STATIC,   SINGULAR, MESSAGE,  high_temp,        14) \
X(a, STATIC,   SINGULAR, MESSAGE,  tm,               15) \
X(a, STATIC,   SINGULAR, MESSAGE,  snr,              16) \
X(a, STATIC,   SINGULAR, MESSAGE,  md,               17)
#define isp_algo_param_t_CALLBACK NULL
#define isp_algo_param_t_DEFAULT NULL
#define isp_algo_param_t_header_MSGTYPE isp_algo_param_header_t
#define isp_algo_param_t_ae_MSGTYPE isp_algo_param_ae_t
#define isp_algo_param_t_awb_MSGTYPE isp_algo_param_awb_t
#define isp_algo_param_t_flick_MSGTYPE isp_algo_param_flick_t
#define isp_algo_param_t_wdr_MSGTYPE isp_algo_param_wdr_t
#define isp_algo_param_t_blc_MSGTYPE isp_algo_param_blc_t
#define isp_algo_param_t_nlsc_MSGTYPE isp_algo_param_nlsc_t
#define isp_algo_param_t_ccm_MSGTYPE isp_algo_param_ccm_t
#define isp_algo_param_t_gamma_MSGTYPE isp_algo_param_gamma_t
#define isp_algo_param_t_ygc_MSGTYPE isp_algo_param_ygc_t
#define isp_algo_param_t_uvtune_MSGTYPE isp_algo_param_uvtune_t
#define isp_algo_param_t_spe_MSGTYPE isp_algo_param_spe_t
#define isp_algo_param_t_texture_MSGTYPE isp_algo_param_texture_t
#define isp_algo_param_t_high_temp_MSGTYPE isp_algo_param_high_temp_t
#define isp_algo_param_t_tm_MSGTYPE isp_algo_param_tm_t
#define isp_algo_param_t_snr_MSGTYPE isp_algo_param_snr_t
#define isp_algo_param_t_md_MSGTYPE isp_algo_param_md_t

extern const pb_msgdesc_t isp_algo_param_header_t_msg;
extern const pb_msgdesc_t isp_algo_param_ae_t_msg;
extern const pb_msgdesc_t isp_algo_point_t_msg;
extern const pb_msgdesc_t isp_algo_param_awb_t_msg;
extern const pb_msgdesc_t isp_algo_param_flick_t_msg;
extern const pb_msgdesc_t isp_algo_param_wdr_t_msg;
extern const pb_msgdesc_t isp_algo_param_blc_t_msg;
extern const pb_msgdesc_t isp_algo_param_nlsc_t_msg;
extern const pb_msgdesc_t isp_algo_param_ccm_t_msg;
extern const pb_msgdesc_t isp_algo_param_gamma_t_msg;
extern const pb_msgdesc_t isp_algo_param_ygc_t_msg;
extern const pb_msgdesc_t isp_algo_param_uvtune_t_msg;
extern const pb_msgdesc_t isp_algo_param_spe_t_msg;
extern const pb_msgdesc_t isp_algo_param_texture_t_msg;
extern const pb_msgdesc_t isp_algo_param_high_temp_t_msg;
extern const pb_msgdesc_t isp_algo_param_tm_t_msg;
extern const pb_msgdesc_t isp_algo_param_snr_t_msg;
extern const pb_msgdesc_t isp_algo_param_md_t_msg;
extern const pb_msgdesc_t isp_algo_param_t_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define isp_algo_param_header_t_fields &isp_algo_param_header_t_msg
#define isp_algo_param_ae_t_fields &isp_algo_param_ae_t_msg
#define isp_algo_point_t_fields &isp_algo_point_t_msg
#define isp_algo_param_awb_t_fields &isp_algo_param_awb_t_msg
#define isp_algo_param_flick_t_fields &isp_algo_param_flick_t_msg
#define isp_algo_param_wdr_t_fields &isp_algo_param_wdr_t_msg
#define isp_algo_param_blc_t_fields &isp_algo_param_blc_t_msg
#define isp_algo_param_nlsc_t_fields &isp_algo_param_nlsc_t_msg
#define isp_algo_param_ccm_t_fields &isp_algo_param_ccm_t_msg
#define isp_algo_param_gamma_t_fields &isp_algo_param_gamma_t_msg
#define isp_algo_param_ygc_t_fields &isp_algo_param_ygc_t_msg
#define isp_algo_param_uvtune_t_fields &isp_algo_param_uvtune_t_msg
#define isp_algo_param_spe_t_fields &isp_algo_param_spe_t_msg
#define isp_algo_param_texture_t_fields &isp_algo_param_texture_t_msg
#define isp_algo_param_high_temp_t_fields &isp_algo_param_high_temp_t_msg
#define isp_algo_param_tm_t_fields &isp_algo_param_tm_t_msg
#define isp_algo_param_snr_t_fields &isp_algo_param_snr_t_msg
#define isp_algo_param_md_t_fields &isp_algo_param_md_t_msg
#define isp_algo_param_t_fields &isp_algo_param_t_msg

/* Maximum encoded size of messages (where known) */
#define isp_algo_param_ae_t_size                 88
#define isp_algo_param_awb_t_size                72
#define isp_algo_param_blc_t_size                9
#define isp_algo_param_ccm_t_size                9
#define isp_algo_param_flick_t_size              10
#define isp_algo_param_gamma_t_size              9
#define isp_algo_param_header_t_size             12
#define isp_algo_param_high_temp_t_size          2
#define isp_algo_param_md_t_size                 7
#define isp_algo_param_nlsc_t_size               6
#define isp_algo_param_snr_t_size                3
#define isp_algo_param_spe_t_size                3
#define isp_algo_param_t_size                    317
#define isp_algo_param_texture_t_size            6
#define isp_algo_param_tm_t_size                 6
#define isp_algo_param_uvtune_t_size             6
#define isp_algo_param_wdr_t_size                24
#define isp_algo_param_ygc_t_size                9
#define isp_algo_point_t_size                    8

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
