/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.5 */

#ifndef PB_ISP_STATIS_PB_H_INCLUDED
#define PB_ISP_STATIS_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _isp_statis_ae_hdr_t { 
    pb_callback_t y_mean; 
    pb_callback_t hist; 
} isp_statis_ae_hdr_t;

typedef struct _isp_statis_af_t { 
    pb_callback_t edges; 
    pb_callback_t num0; 
    pb_callback_t sum0; 
    pb_callback_t num1; 
    pb_callback_t sum1; 
} isp_statis_af_t;

typedef struct _isp_statis_awb_t { 
    pb_callback_t r_mean; 
    pb_callback_t g_mean; 
    pb_callback_t b_mean; 
    pb_callback_t y_mean; 
    pb_callback_t rg; 
    pb_callback_t bg; 
    pb_callback_t pixels; 
    pb_callback_t illum_white_pixels; 
    pb_callback_t fine_r_sum; 
    pb_callback_t fine_g_sum; 
    pb_callback_t fine_b_sum; 
    pb_callback_t fine_white_pixels; 
} isp_statis_awb_t;

typedef struct _isp_statis_flick_t { 
    pb_callback_t valid; 
    pb_callback_t fft_sum_2_9; 
    pb_callback_t fft_sum_2_127; 
} isp_statis_flick_t;

typedef struct _isp_statis_raw_t { 
    pb_callback_t r_mean; 
    pb_callback_t gr_mean; 
    pb_callback_t gb_mean; 
    pb_callback_t b_mean; 
    pb_callback_t y_mean; 
    pb_callback_t rg; 
    pb_callback_t bg; 
    pb_callback_t pixels; 
} isp_statis_raw_t;

typedef struct _isp_statis_y_t { 
    pb_callback_t y_mean; 
    pb_callback_t hist; 
} isp_statis_y_t;

typedef struct _isp_statis_ae_t { 
    pb_callback_t y_mean; 
    pb_callback_t hist; 
    isp_statis_ae_hdr_t hdr[2]; 
} isp_statis_ae_t;

typedef struct _isp_statis_t { 
    pb_callback_t frame_count; 
    isp_statis_raw_t raw; 
    isp_statis_awb_t awb; 
    isp_statis_ae_t ae; 
    isp_statis_af_t af; 
    isp_statis_flick_t flick; 
    isp_statis_y_t y; 
} isp_statis_t;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define isp_statis_raw_t_init_default            {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define isp_statis_awb_t_init_default            {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define isp_statis_ae_hdr_t_init_default         {{{NULL}, NULL}, {{NULL}, NULL}}
#define isp_statis_ae_t_init_default             {{{NULL}, NULL}, {{NULL}, NULL}, {isp_statis_ae_hdr_t_init_default, isp_statis_ae_hdr_t_init_default}}
#define isp_statis_af_t_init_default             {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define isp_statis_flick_t_init_default          {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define isp_statis_y_t_init_default              {{{NULL}, NULL}, {{NULL}, NULL}}
#define isp_statis_t_init_default                {{{NULL}, NULL}, isp_statis_raw_t_init_default, isp_statis_awb_t_init_default, isp_statis_ae_t_init_default, isp_statis_af_t_init_default, isp_statis_flick_t_init_default, isp_statis_y_t_init_default}
#define isp_statis_raw_t_init_zero               {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define isp_statis_awb_t_init_zero               {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define isp_statis_ae_hdr_t_init_zero            {{{NULL}, NULL}, {{NULL}, NULL}}
#define isp_statis_ae_t_init_zero                {{{NULL}, NULL}, {{NULL}, NULL}, {isp_statis_ae_hdr_t_init_zero, isp_statis_ae_hdr_t_init_zero}}
#define isp_statis_af_t_init_zero                {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define isp_statis_flick_t_init_zero             {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define isp_statis_y_t_init_zero                 {{{NULL}, NULL}, {{NULL}, NULL}}
#define isp_statis_t_init_zero                   {{{NULL}, NULL}, isp_statis_raw_t_init_zero, isp_statis_awb_t_init_zero, isp_statis_ae_t_init_zero, isp_statis_af_t_init_zero, isp_statis_flick_t_init_zero, isp_statis_y_t_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define isp_statis_ae_hdr_t_y_mean_tag           1
#define isp_statis_ae_hdr_t_hist_tag             2
#define isp_statis_af_t_edges_tag                1
#define isp_statis_af_t_num0_tag                 2
#define isp_statis_af_t_sum0_tag                 3
#define isp_statis_af_t_num1_tag                 4
#define isp_statis_af_t_sum1_tag                 5
#define isp_statis_awb_t_r_mean_tag              1
#define isp_statis_awb_t_g_mean_tag              2
#define isp_statis_awb_t_b_mean_tag              3
#define isp_statis_awb_t_y_mean_tag              4
#define isp_statis_awb_t_rg_tag                  5
#define isp_statis_awb_t_bg_tag                  6
#define isp_statis_awb_t_pixels_tag              7
#define isp_statis_awb_t_illum_white_pixels_tag  8
#define isp_statis_awb_t_fine_r_sum_tag          9
#define isp_statis_awb_t_fine_g_sum_tag          10
#define isp_statis_awb_t_fine_b_sum_tag          11
#define isp_statis_awb_t_fine_white_pixels_tag   12
#define isp_statis_flick_t_valid_tag             1
#define isp_statis_flick_t_fft_sum_2_9_tag       2
#define isp_statis_flick_t_fft_sum_2_127_tag     3
#define isp_statis_raw_t_r_mean_tag              1
#define isp_statis_raw_t_gr_mean_tag             2
#define isp_statis_raw_t_gb_mean_tag             3
#define isp_statis_raw_t_b_mean_tag              4
#define isp_statis_raw_t_y_mean_tag              5
#define isp_statis_raw_t_rg_tag                  6
#define isp_statis_raw_t_bg_tag                  7
#define isp_statis_raw_t_pixels_tag              8
#define isp_statis_y_t_y_mean_tag                1
#define isp_statis_y_t_hist_tag                  2
#define isp_statis_ae_t_y_mean_tag               1
#define isp_statis_ae_t_hist_tag                 2
#define isp_statis_ae_t_hdr_tag                  3
#define isp_statis_t_frame_count_tag             1
#define isp_statis_t_raw_tag                     2
#define isp_statis_t_awb_tag                     3
#define isp_statis_t_ae_tag                      4
#define isp_statis_t_af_tag                      5
#define isp_statis_t_flick_tag                   6
#define isp_statis_t_y_tag                       7

/* Struct field encoding specification for nanopb */
#define isp_statis_raw_t_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, FIXED32,  r_mean,            1) \
X(a, CALLBACK, REPEATED, FIXED32,  gr_mean,           2) \
X(a, CALLBACK, REPEATED, FIXED32,  gb_mean,           3) \
X(a, CALLBACK, REPEATED, FIXED32,  b_mean,            4) \
X(a, CALLBACK, REPEATED, FIXED32,  y_mean,            5) \
X(a, CALLBACK, REPEATED, FIXED32,  rg,                6) \
X(a, CALLBACK, REPEATED, FIXED32,  bg,                7) \
X(a, CALLBACK, REPEATED, FIXED32,  pixels,            8)
#define isp_statis_raw_t_CALLBACK pb_default_field_callback
#define isp_statis_raw_t_DEFAULT NULL

#define isp_statis_awb_t_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, FIXED32,  r_mean,            1) \
X(a, CALLBACK, REPEATED, FIXED32,  g_mean,            2) \
X(a, CALLBACK, REPEATED, FIXED32,  b_mean,            3) \
X(a, CALLBACK, REPEATED, FIXED32,  y_mean,            4) \
X(a, CALLBACK, REPEATED, FIXED32,  rg,                5) \
X(a, CALLBACK, REPEATED, FIXED32,  bg,                6) \
X(a, CALLBACK, REPEATED, FIXED32,  pixels,            7) \
X(a, CALLBACK, REPEATED, FIXED32,  illum_white_pixels,   8) \
X(a, CALLBACK, SINGULAR, FIXED32,  fine_r_sum,        9) \
X(a, CALLBACK, SINGULAR, FIXED32,  fine_g_sum,       10) \
X(a, CALLBACK, SINGULAR, FIXED32,  fine_b_sum,       11) \
X(a, CALLBACK, SINGULAR, FIXED32,  fine_white_pixels,  12)
#define isp_statis_awb_t_CALLBACK pb_default_field_callback
#define isp_statis_awb_t_DEFAULT NULL

#define isp_statis_ae_hdr_t_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, FIXED32,  y_mean,            1) \
X(a, CALLBACK, REPEATED, FIXED32,  hist,              2)
#define isp_statis_ae_hdr_t_CALLBACK pb_default_field_callback
#define isp_statis_ae_hdr_t_DEFAULT NULL

#define isp_statis_ae_t_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, FIXED32,  y_mean,            1) \
X(a, CALLBACK, REPEATED, FIXED32,  hist,              2) \
X(a, STATIC,   FIXARRAY, MESSAGE,  hdr,               3)
#define isp_statis_ae_t_CALLBACK pb_default_field_callback
#define isp_statis_ae_t_DEFAULT NULL
#define isp_statis_ae_t_hdr_MSGTYPE isp_statis_ae_hdr_t

#define isp_statis_af_t_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, FIXED32,  edges,             1) \
X(a, CALLBACK, SINGULAR, FIXED32,  num0,              2) \
X(a, CALLBACK, SINGULAR, FIXED32,  sum0,              3) \
X(a, CALLBACK, SINGULAR, FIXED32,  num1,              4) \
X(a, CALLBACK, SINGULAR, FIXED32,  sum1,              5)
#define isp_statis_af_t_CALLBACK pb_default_field_callback
#define isp_statis_af_t_DEFAULT NULL

#define isp_statis_flick_t_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, FIXED32,  valid,             1) \
X(a, CALLBACK, SINGULAR, FIXED32,  fft_sum_2_9,       2) \
X(a, CALLBACK, SINGULAR, FIXED32,  fft_sum_2_127,     3)
#define isp_statis_flick_t_CALLBACK pb_default_field_callback
#define isp_statis_flick_t_DEFAULT NULL

#define isp_statis_y_t_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, FIXED32,  y_mean,            1) \
X(a, CALLBACK, REPEATED, FIXED32,  hist,              2)
#define isp_statis_y_t_CALLBACK pb_default_field_callback
#define isp_statis_y_t_DEFAULT NULL

#define isp_statis_t_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, FIXED32,  frame_count,       1) \
X(a, STATIC,   SINGULAR, MESSAGE,  raw,               2) \
X(a, STATIC,   SINGULAR, MESSAGE,  awb,               3) \
X(a, STATIC,   SINGULAR, MESSAGE,  ae,                4) \
X(a, STATIC,   SINGULAR, MESSAGE,  af,                5) \
X(a, STATIC,   SINGULAR, MESSAGE,  flick,             6) \
X(a, STATIC,   SINGULAR, MESSAGE,  y,                 7)
#define isp_statis_t_CALLBACK pb_default_field_callback
#define isp_statis_t_DEFAULT NULL
#define isp_statis_t_raw_MSGTYPE isp_statis_raw_t
#define isp_statis_t_awb_MSGTYPE isp_statis_awb_t
#define isp_statis_t_ae_MSGTYPE isp_statis_ae_t
#define isp_statis_t_af_MSGTYPE isp_statis_af_t
#define isp_statis_t_flick_MSGTYPE isp_statis_flick_t
#define isp_statis_t_y_MSGTYPE isp_statis_y_t

extern const pb_msgdesc_t isp_statis_raw_t_msg;
extern const pb_msgdesc_t isp_statis_awb_t_msg;
extern const pb_msgdesc_t isp_statis_ae_hdr_t_msg;
extern const pb_msgdesc_t isp_statis_ae_t_msg;
extern const pb_msgdesc_t isp_statis_af_t_msg;
extern const pb_msgdesc_t isp_statis_flick_t_msg;
extern const pb_msgdesc_t isp_statis_y_t_msg;
extern const pb_msgdesc_t isp_statis_t_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define isp_statis_raw_t_fields &isp_statis_raw_t_msg
#define isp_statis_awb_t_fields &isp_statis_awb_t_msg
#define isp_statis_ae_hdr_t_fields &isp_statis_ae_hdr_t_msg
#define isp_statis_ae_t_fields &isp_statis_ae_t_msg
#define isp_statis_af_t_fields &isp_statis_af_t_msg
#define isp_statis_flick_t_fields &isp_statis_flick_t_msg
#define isp_statis_y_t_fields &isp_statis_y_t_msg
#define isp_statis_t_fields &isp_statis_t_msg

/* Maximum encoded size of messages (where known) */
/* isp_statis_raw_t_size depends on runtime parameters */
/* isp_statis_awb_t_size depends on runtime parameters */
/* isp_statis_ae_hdr_t_size depends on runtime parameters */
/* isp_statis_ae_t_size depends on runtime parameters */
/* isp_statis_af_t_size depends on runtime parameters */
/* isp_statis_flick_t_size depends on runtime parameters */
/* isp_statis_y_t_size depends on runtime parameters */
/* isp_statis_t_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
