/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.5 */

#include "isp_iq_table.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(isp_iq_header_t, isp_iq_header_t, AUTO)


PB_BIND(isp_iq_bound_t, isp_iq_bound_t, AUTO)


PB_BIND(isp_iq_bounds_t, isp_iq_bounds_t, AUTO)


PB_BIND(isp_iq_hysteresis_bounds_t, isp_iq_hysteresis_bounds_t, AUTO)


PB_BIND(isp_iq_point_t, isp_iq_point_t, AUTO)


PB_BIND(isp_iq_blc_dyn_gain_t, isp_iq_blc_dyn_gain_t, AUTO)


PB_BIND(isp_iq_blc_offset_t, isp_iq_blc_offset_t, AUTO)


PB_BIND(isp_iq_blc_ct_item_t, isp_iq_blc_ct_item_t, AUTO)


PB_BIND(isp_iq_blc_dyn_ct_t, isp_iq_blc_dyn_ct_t, AUTO)


PB_BIND(isp_iq_blc_dyn_ht_t, isp_iq_blc_dyn_ht_t, AUTO)


PB_BIND(isp_iq_blc_t, isp_iq_blc_t, AUTO)


PB_BIND(isp_iq_nlsc_common_t, isp_iq_nlsc_common_t, AUTO)


PB_BIND(isp_iq_nlsc_dyn_gain_t, isp_iq_nlsc_dyn_gain_t, AUTO)


PB_BIND(isp_iq_nlsc_adj_t, isp_iq_nlsc_adj_t, AUTO)


PB_BIND(isp_iq_nlsc_ct_item_t, isp_iq_nlsc_ct_item_t, AUTO)


PB_BIND(isp_iq_nlsc_dyn_ct_t, isp_iq_nlsc_dyn_ct_t, AUTO)


PB_BIND(isp_iq_nlsc_t, isp_iq_nlsc_t, AUTO)


PB_BIND(isp_iq_mlsc_t, isp_iq_mlsc_t, AUTO)


PB_BIND(isp_iq_ae1_dyn_sort_table_t, isp_iq_ae1_dyn_sort_table_t, AUTO)


PB_BIND(isp_iq_ae1_dyn_target_t, isp_iq_ae1_dyn_target_t, AUTO)


PB_BIND(isp_iq_range_t, isp_iq_range_t, AUTO)


PB_BIND(isp_iq_ae1_dyn_ratio_range_t, isp_iq_ae1_dyn_ratio_range_t, AUTO)


PB_BIND(isp_iq_ae1_ratio_inc_ctrl_t, isp_iq_ae1_ratio_inc_ctrl_t, AUTO)


PB_BIND(isp_iq_ae1_hdr_t, isp_iq_ae1_hdr_t, 2)


PB_BIND(isp_iq_ae1_t, isp_iq_ae1_t, 2)


PB_BIND(isp_iq_ae_t, isp_iq_ae_t, 2)


PB_BIND(isp_iq_awb1_weight_table_t, isp_iq_awb1_weight_table_t, AUTO)


PB_BIND(isp_iq_awb1_green_t, isp_iq_awb1_green_t, AUTO)


PB_BIND(isp_iq_awb1_mixct_t, isp_iq_awb1_mixct_t, AUTO)


PB_BIND(isp_iq_awb1_rough_limit_t, isp_iq_awb1_rough_limit_t, AUTO)


PB_BIND(isp_iq_awb1_fine_limit_t, isp_iq_awb1_fine_limit_t, AUTO)


PB_BIND(isp_iq_awb1_illums_t, isp_iq_awb1_illums_t, AUTO)


PB_BIND(isp_iq_awb1_stat_config_t, isp_iq_awb1_stat_config_t, AUTO)


PB_BIND(isp_iq_awb1_t, isp_iq_awb1_t, 2)


PB_BIND(isp_iq_awb_gain_adj_t, isp_iq_awb_gain_adj_t, AUTO)


PB_BIND(isp_iq_awb_ct_item_t, isp_iq_awb_ct_item_t, AUTO)


PB_BIND(isp_iq_awb_dyn_ct_t, isp_iq_awb_dyn_ct_t, AUTO)


PB_BIND(isp_iq_awb_dyn_gain_t, isp_iq_awb_dyn_gain_t, AUTO)


PB_BIND(isp_iq_awb_t, isp_iq_awb_t, 2)


PB_BIND(isp_iq_af1_block_t, isp_iq_af1_block_t, AUTO)


PB_BIND(isp_iq_af1_t, isp_iq_af1_t, AUTO)


PB_BIND(isp_iq_af_t, isp_iq_af_t, AUTO)


PB_BIND(isp_iq_ccm_item_t, isp_iq_ccm_item_t, AUTO)


PB_BIND(isp_iq_ccm_ct_item_t, isp_iq_ccm_ct_item_t, AUTO)


PB_BIND(isp_iq_ccm_dyn_ct_t, isp_iq_ccm_dyn_ct_t, AUTO)


PB_BIND(isp_iq_ccm_dyn_gain_t, isp_iq_ccm_dyn_gain_t, AUTO)


PB_BIND(isp_iq_ccm_dyn_ht_t, isp_iq_ccm_dyn_ht_t, AUTO)


PB_BIND(isp_iq_ccm_t, isp_iq_ccm_t, AUTO)


PB_BIND(isp_iq_gamma_item_t, isp_iq_gamma_item_t, AUTO)


PB_BIND(isp_iq_gamma_ratio_item_t, isp_iq_gamma_ratio_item_t, AUTO)


PB_BIND(isp_iq_gamma_dyn_ratio_t, isp_iq_gamma_dyn_ratio_t, AUTO)


PB_BIND(isp_iq_gamma_dyn_ht_t, isp_iq_gamma_dyn_ht_t, AUTO)


PB_BIND(isp_iq_gamma_dyn_gain_t, isp_iq_gamma_dyn_gain_t, AUTO)


PB_BIND(isp_iq_gamma_t, isp_iq_gamma_t, AUTO)


PB_BIND(isp_iq_wdr1_t, isp_iq_wdr1_t, AUTO)


PB_BIND(isp_iq_wdr_t, isp_iq_wdr_t, AUTO)


PB_BIND(isp_iq_ygc_item_t, isp_iq_ygc_item_t, AUTO)


PB_BIND(isp_iq_ygc_ratio_item_t, isp_iq_ygc_ratio_item_t, AUTO)


PB_BIND(isp_iq_ygc_dyn_ratio_t, isp_iq_ygc_dyn_ratio_t, AUTO)


PB_BIND(isp_iq_ygc_dyn_gain_t, isp_iq_ygc_dyn_gain_t, AUTO)


PB_BIND(isp_iq_ygc_dyn_ht_t, isp_iq_ygc_dyn_ht_t, AUTO)


PB_BIND(isp_iq_ygc_t, isp_iq_ygc_t, AUTO)


PB_BIND(isp_iq_tm_item_t, isp_iq_tm_item_t, AUTO)


PB_BIND(isp_iq_tm_dyn_gain_t, isp_iq_tm_dyn_gain_t, AUTO)


PB_BIND(isp_iq_tm_dyn_ht_t, isp_iq_tm_dyn_ht_t, AUTO)


PB_BIND(isp_iq_tm_t, isp_iq_tm_t, AUTO)


PB_BIND(isp_iq_snr_item_t, isp_iq_snr_item_t, AUTO)


PB_BIND(isp_iq_snr_dyn_gain_t, isp_iq_snr_dyn_gain_t, AUTO)


PB_BIND(isp_iq_snr_t, isp_iq_snr_t, AUTO)


PB_BIND(isp_iq_uvtune_dyn_gain_t, isp_iq_uvtune_dyn_gain_t, AUTO)


PB_BIND(isp_iq_uvtune_item_t, isp_iq_uvtune_item_t, AUTO)


PB_BIND(isp_iq_uvtune_ct_item_t, isp_iq_uvtune_ct_item_t, AUTO)


PB_BIND(isp_iq_uvtune_dyn_ct_t, isp_iq_uvtune_dyn_ct_t, AUTO)


PB_BIND(isp_iq_uvtune_t, isp_iq_uvtune_t, AUTO)


PB_BIND(isp_iq_uv_offset_item_t, isp_iq_uv_offset_item_t, AUTO)


PB_BIND(isp_iq_uv_offset_t, isp_iq_uv_offset_t, AUTO)


PB_BIND(isp_iq_spe_t, isp_iq_spe_t, AUTO)


PB_BIND(isp_iq_texture_static_t, isp_iq_texture_static_t, AUTO)


PB_BIND(isp_iq_level_t, isp_iq_level_t, AUTO)


PB_BIND(isp_iq_texture_dynamic_offset_t, isp_iq_texture_dynamic_offset_t, AUTO)


PB_BIND(isp_iq_texture_dynamic_value_t, isp_iq_texture_dynamic_value_t, AUTO)


PB_BIND(isp_iq_texture_dynamic_t, isp_iq_texture_dynamic_t, 2)


PB_BIND(isp_iq_texture_dyn_ratio_gain_t, isp_iq_texture_dyn_ratio_gain_t, AUTO)


PB_BIND(isp_iq_texture_dyn_ratio_item_t, isp_iq_texture_dyn_ratio_item_t, AUTO)


PB_BIND(isp_iq_texture_dyn_ratio_t, isp_iq_texture_dyn_ratio_t, 2)


PB_BIND(isp_iq_texture_t, isp_iq_texture_t, 2)


PB_BIND(isp_iq_daynight_t, isp_iq_daynight_t, AUTO)


PB_BIND(isp_iq_high_temp_t, isp_iq_high_temp_t, AUTO)


PB_BIND(isp_iq_md_decay_ratio_t, isp_iq_md_decay_ratio_t, AUTO)


PB_BIND(isp_iq_md_item_t, isp_iq_md_item_t, AUTO)


PB_BIND(isp_iq_md_dyn_gain_t, isp_iq_md_dyn_gain_t, AUTO)


PB_BIND(isp_iq_md_t, isp_iq_md_t, AUTO)


PB_BIND(isp_iq_table_t, isp_iq_table_t, AUTO)



