/* Auto generated by cmake. Please do not modify! */

#include <isp_mod.h>
#include <isp_debug.h>
typedef int (*reg_mod_func)(void);
typedef void (*unreg_mod_func)(void);

#define MODULES_REG_FUNC_DECLARATION(mod) \
int isp_register_mod_##mod(void); \
void isp_unregister_mod_##mod(void);

MODULES_REG_FUNC_DECLARATION(gamma);
MODULES_REG_FUNC_DECLARATION(eeh);
MODULES_REG_FUNC_DECLARATION(interface);
MODULES_REG_FUNC_DECLARATION(iq);
MODULES_REG_FUNC_DECLARATION(af);
MODULES_REG_FUNC_DECLARATION(spe);
MODULES_REG_FUNC_DECLARATION(ccm);
MODULES_REG_FUNC_DECLARATION(nlsc);
MODULES_REG_FUNC_DECLARATION(global);
MODULES_REG_FUNC_DECLARATION(statis);
MODULES_REG_FUNC_DECLARATION(intp);
MODULES_REG_FUNC_DECLARATION(ystat);
MODULES_REG_FUNC_DECLARATION(crop);
MODULES_REG_FUNC_DECLARATION(ldc);
MODULES_REG_FUNC_DECLARATION(ygc);
MODULES_REG_FUNC_DECLARATION(wdr);
MODULES_REG_FUNC_DECLARATION(dehaze);
MODULES_REG_FUNC_DECLARATION(rawstat);
MODULES_REG_FUNC_DECLARATION(mlsc);
MODULES_REG_FUNC_DECLARATION(rgb2yuv);
//MODULES_REG_FUNC_DECLARATION(mipiout);
MODULES_REG_FUNC_DECLARATION(blc);
MODULES_REG_FUNC_DECLARATION(ygamma);
MODULES_REG_FUNC_DECLARATION(flick);
MODULES_REG_FUNC_DECLARATION(awb);
MODULES_REG_FUNC_DECLARATION(tnr);
MODULES_REG_FUNC_DECLARATION(uvtune);
MODULES_REG_FUNC_DECLARATION(mask);
MODULES_REG_FUNC_DECLARATION(vctrl);
MODULES_REG_FUNC_DECLARATION(control);
MODULES_REG_FUNC_DECLARATION(sensor);
MODULES_REG_FUNC_DECLARATION(ae);
MODULES_REG_FUNC_DECLARATION(mcrop);
MODULES_REG_FUNC_DECLARATION(tm);
MODULES_REG_FUNC_DECLARATION(snr);
MODULES_REG_FUNC_DECLARATION(md);

static reg_mod_func reg_mod_funcs[] = {
	isp_register_mod_gamma,
	isp_register_mod_eeh,
	isp_register_mod_interface,
	isp_register_mod_iq,
	isp_register_mod_af,
	isp_register_mod_spe,
	isp_register_mod_ccm,
	isp_register_mod_nlsc,
	isp_register_mod_global,
	isp_register_mod_statis,
	isp_register_mod_intp,
	isp_register_mod_ystat,
	isp_register_mod_crop,
	isp_register_mod_ldc,
	isp_register_mod_ygc,
	isp_register_mod_wdr,
	isp_register_mod_dehaze,
	isp_register_mod_rawstat,
	isp_register_mod_mlsc,
	isp_register_mod_rgb2yuv,
	//isp_register_mod_mipiout,
	isp_register_mod_blc,
	isp_register_mod_ygamma,
	isp_register_mod_flick,
	isp_register_mod_awb,
#ifdef __3DNR__
	isp_register_mod_tnr,
#endif
	isp_register_mod_uvtune,
	isp_register_mod_mask,
	isp_register_mod_vctrl,
	isp_register_mod_control,
	isp_register_mod_sensor,
	isp_register_mod_ae,
	isp_register_mod_mcrop,
	isp_register_mod_tm,
	isp_register_mod_snr,
	isp_register_mod_md,
};

static unreg_mod_func unreg_mod_funcs[] = {
	isp_unregister_mod_gamma,
	isp_unregister_mod_eeh,
	isp_unregister_mod_interface,
	isp_unregister_mod_iq,
	isp_unregister_mod_af,
	isp_unregister_mod_spe,
	isp_unregister_mod_ccm,
	isp_unregister_mod_nlsc,
	isp_unregister_mod_global,
	isp_unregister_mod_statis,
	isp_unregister_mod_intp,
	isp_unregister_mod_ystat,
	isp_unregister_mod_crop,
	isp_unregister_mod_ldc,
	isp_unregister_mod_ygc,
	isp_unregister_mod_wdr,
	isp_unregister_mod_dehaze,
	isp_unregister_mod_rawstat,
	isp_unregister_mod_mlsc,
	isp_unregister_mod_rgb2yuv,
	//isp_unregister_mod_mipiout,
	isp_unregister_mod_blc,
	isp_unregister_mod_ygamma,
	isp_unregister_mod_flick,
	isp_unregister_mod_awb,
	isp_unregister_mod_tnr,
	isp_unregister_mod_uvtune,
	isp_unregister_mod_mask,
	isp_unregister_mod_vctrl,
	isp_unregister_mod_control,
	isp_unregister_mod_sensor,
	isp_unregister_mod_ae,
	isp_unregister_mod_mcrop,
	isp_unregister_mod_tm,
	isp_unregister_mod_snr,
	isp_unregister_mod_md,
};

int isp_register_all_modules(void)
{
	int i;
	int ret;

	for (i = 0; i < (int)ARRAY_SIZE(reg_mod_funcs); i++) {
		ret = reg_mod_funcs[i]();
		if (ret)
			break;
	}
	if (ret)
		isp_unregister_all_modules();

	return ret;
}

void isp_unregister_all_modules(void)
{
	int i;

	for (i = 0; i < (int)ARRAY_SIZE(unreg_mod_funcs); i++)
		unreg_mod_funcs[i]();
}
