
/*
 * Realtek Semiconductor Corp.
 *
 * rts_camera_zoom_reg.h
 *
 * Copyright (C) 2019     Wil_shi<wil_shi@realsil.com.cn>
 */

#ifndef _U_RTS_CAMERA_ZOOM_REG_H
#define _U_RTS_CAMERA_ZOOM_REG_H

#define RTS_ZOOM_REG_SYS_CONTROL0		0
#define RTS_ZOOM_REG_SYS_CONTROL1		0x0004
#define RTS_ZOOM_REG_SYS_DATA_DELAY		0x0040
#define RTS_ZOOM_REG_SYS_IMAGE_SEL0		0x0048
#define RTS_ZOOM_REG_SYS_IMAGE_AI_CHAN_SEL	0x0078


#define RTS_ZOOM_REG_MCROP_STARTX		0x4c00
#define RTS_ZOOM_REG_MCROP_STARTY		0x4C04
#define RTS_ZOOM_REG_MCROP_FRAME_WIDTH		0x4c08
#define RTS_ZOOM_REG_MCROP_FRAME_HEIGHT		0x4c0c
#define RTS_ZOOM_REG_MCROP_LOAD			0x4c10


#define RTS_ZOOM_REG_BASE			0x10000
#define RTS_ZOOM_REG_CH0_CTRL			(RTS_ZOOM_REG_BASE + 0x0000)
#define RTS_ZOOM_REG_CH0_CROP_START		(RTS_ZOOM_REG_BASE + 0x0004)
#define RTS_ZOOM_REG_CH0_OUTPUT_SIZE		(RTS_ZOOM_REG_BASE + 0x0008)
#define RTS_ZOOM_REG_CH0_COEF0			(RTS_ZOOM_REG_BASE + 0x0010)
#define RTS_ZOOM_REG_CH0_COEF1			(RTS_ZOOM_REG_BASE + 0x0014)
#define RTS_ZOOM_REG_CH0_COEF2			(RTS_ZOOM_REG_BASE + 0x0018)
#define RTS_ZOOM_REG_CH0_COEF3			(RTS_ZOOM_REG_BASE + 0x001C)
#define RTS_ZOOM_REG_CH0_COEF4			(RTS_ZOOM_REG_BASE + 0x0020)
#define RTS_ZOOM_REG_CH0_STEP_V			(RTS_ZOOM_REG_BASE + 0x0048)
#define RTS_ZOOM_REG_CH0_STEP_H			(RTS_ZOOM_REG_BASE + 0x004C)
#define RTS_ZOOM_REG_CH0_REG_LOAD		(RTS_ZOOM_REG_BASE + 0x0024)
#define RTS_ZOOM_REG_CH_REG_OFFSET		0x80

#endif
