#ifndef RLX_REG_CRYPTO_H
#define RLX_REG_CRYPTO_H
#include "rlx_reg_base.h"

#define RLX_REG_KEY_DATA0			(AES_BASE + 0x00)
#define RLX_REG_KEY_DATA1			(AES_BASE + 0x04)
#define RLX_REG_KEY_DATA2			(AES_BASE + 0x08)
#define RLX_REG_KEY_DATA3			(AES_BASE + 0x0C)
#define RLX_REG_KEY_DATA4			(AES_BASE + 0x10)
#define RLX_REG_KEY_DATA5			(AES_BASE + 0x14)
#define RLX_REG_KEY_DATA6			(AES_BASE + 0x18)
#define RLX_REG_KEY_DATA7			(AES_BASE + 0x1C)
#define RLX_REG_IV_IN_DATA0			(AES_BASE + 0x20)
#define RLX_REG_IV_IN_DATA1			(AES_BASE + 0x24)
#define RLX_REG_IV_IN_DATA2			(AES_BASE + 0x28)
#define RLX_REG_IV_IN_DATA3			(AES_BASE + 0x2C)
#define RLX_REG_IV_OUT_DATA0		(AES_BASE + 0x30)
#define RLX_REG_IV_OUT_DATA1		(AES_BASE + 0x34)
#define RLX_REG_IV_OUT_DATA2		(AES_BASE + 0x38)
#define RLX_REG_IV_OUT_DATA3		(AES_BASE + 0x3C)
#define RLX_REG_IN_TABLE_ADDR		(AES_BASE + 0x40)
#define RLX_REG_IN_BUF_NUM			(AES_BASE + 0x44)
#define RLX_REG_OUT_TABLE_ADDR		(AES_BASE + 0x48)
#define RLX_REG_OUT_BUF_NUM			(AES_BASE + 0x4C)
#define RLX_REG_CIPHER_CTL			(AES_BASE + 0x50)
#define RLX_REG_CIPHER_INT_EN		(AES_BASE + 0x54)
#define RLX_REG_CIPHER_INT_FLAG		(AES_BASE + 0x58)
#define RLX_REG_CIPHER_STS			(AES_BASE + 0x5C)
#define RLX_REG_FINISH_BLOCK_NUM	(AES_BASE + 0x60)
#define RLX_REG_DATA_IN_LENGTH		(AES_BASE + 0x64)
#define RLX_REG_CIPHER_KEY			(AES_BASE + 0x200)

#endif	// RLX_REG_CRYPTO_H
