#ifndef RLX_REG_GPIO_H
#define RLX_REG_GPIO_H
#include "rlx_reg_base.h"

#define RLX_REG_XB2_GPIO_OE					(GPIO_BASE)
#define RLX_REG_XB2_GPIO_PULLCTRL			(GPIO_BASE + 0x04)
#define RLX_REG_XB2_GPIO_O					(GPIO_BASE + 0x08)
#define RLX_REG_XB2_GPIO_INT_EN				(GPIO_BASE + 0x0C)
#define RLX_REG_XB2_GPIO_INT_FLAG			(GPIO_BASE + 0x10)
#define RLX_REG_XB2_GPIO_DRV_SEL			(GPIO_BASE + 0x14)
#define RLX_REG_XB2_GPIO_SR_CTRL			(GPIO_BASE + 0x18)
#define RLX_REG_XB2_SPI_PAD_DRIVING			(GPIO_BASE + 0x2C)
#define RLX_REG_XB2_SHARE_GPIO_SELECT		(GPIO_BASE + 0x4C)
#define RLX_REG_XB2_SHARE_GPIO_OE			(GPIO_BASE + 0x50)
#define RLX_REG_XB2_SHARE_GPIO_PULLCTRL		(GPIO_BASE + 0x54)
#define RLX_REG_XB2_SHARE_GPIO_O			(GPIO_BASE + 0x58)
#define RLX_REG_XB2_SHARE_GPIO_INT_EN		(GPIO_BASE + 0x5C)
#define RLX_REG_XB2_SHARE_GPIO_INT_FLAG		(GPIO_BASE + 0x60)
#define RLX_REG_XB2_SHARE_GPIO_DRV_SEL		(GPIO_BASE + 0x64)
#define RLX_REG_XB2_SHARE_GPIO_SR_CTRL		(GPIO_BASE + 0x68)
#define RLX_REG_PWM_GPIO_ETN_LED_SEL		(GPIO_BASE + 0x6C)
#define RLX_REG_XB2_SHARE_GPIO_PULLCTRL1	(GPIO_BASE + 0x70)
#define RLX_REG_XB2_SHARE_GPIO_INT_EN1		(GPIO_BASE + 0x74)
#define RLX_REG_XB2_SHARE_GPIO_INT_FLAG1	(GPIO_BASE + 0x78)

#endif	// RLX_REG_GPIO_H
