#ifndef RLX_REG_SARADC_H
#define RLX_REG_SARADC_H
#include "rlx_reg_base.h"

#define RLX_REG_SYS_SAR_CFG			(SARADC_BASE)
#define RLX_REG_SYS_SAR_ADC_STABLE	(SARADC_BASE + 0x04)
#define RLX_REG_SYS_SAR_DAT0		(SARADC_BASE + 0x08)
#define RLX_REG_SYS_SAR_DAT1		(SARADC_BASE + 0x0C)
#define RLX_REG_SYS_SAR_DAT2		(SARADC_BASE + 0x10)
#define RLX_REG_SYS_SAR_DAT3		(SARADC_BASE + 0x14)
#define RLX_REG_SYS_SAR_DIV_CNT		(SARADC_BASE + 0x18)

#endif	// RLX_REG_SARADC_H
